<ol class="breadcrumb">
	<li><a href="<?php echo $this->url('operator')?>"><span class=" glyphicon glyphicon-home"></span> <?php echo $this->translate('Operator menu'); ?></a></li>
	<li class="active"><?php echo $this->translate('Account confirmation'); ?></li>
</ol>
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="panel-body">
			<div class="panel panel-danger">
				<div class="panel-heading">
					<h3><span class="glyphicon glyphicon-warning-sign"></span> <?php echo $this->translate('CAUTION: EXPIRY TIME EXCEEDED'); ?></h3>
				</div>
				<div class="panel-body">
					<h4><?php echo $this->translate('Injection prohibited unless authorized by Radio-Pharmacist'); ?>
					<p><strong><?php echo $this->translate('To Authorize: Please sign-in with authority account, or Cancel to end the injections.'); ?></strong></p>
					<div class="row">
						<div class="col-md-8 col-md-offset-2">
							<form role="form">
								<div id="inputgroup1" class="form-group">
									<label for="input1"><?php echo $this->translate('User'); ?></label>
									<input type="text" class="form-control" id="input1" placeholder="" autocomplete="off" />
								</div>
								<div id="inputgroup2" class="form-group">
									<label for="input2"><?php echo $this->translate('Password'); ?></label>
									<input type="password" class="form-control" id="input2" placeholder="" autocomplete="off" />
								</div>
							</form>
						</div>
					</div>
					<div class="row">
						<div class="col-md-3 col-md-offset-3">
							<button id="btn-next" type="button" class="btn btn-success btn-block" onClick="location.href='<?php echo $this->url('setup', array('action'=>'selectpatient'))?>'"><?php echo $this->translate('Valid'); ?></button>
						</div>
						<div class="col-md-3">
							<button id="btn-exit" type="button" class="btn btn-danger btn-block" onClick="location.href='<?php echo $this->url('operator')?>'"><?php echo $this->translate('Cancel'); ?></button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>