<ol class="breadcrumb">
	<li><a href="<?php echo $this->url('operator')?>"><span class=" glyphicon glyphicon-home"></span> <?php echo $this->translate('Operator menu'); ?></a></li>
	<li class="active"><?php echo $this->translate('Account confirmation'); ?></li>
</ol>
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="panel-body">
			<div class="panel panel-danger">
				<div class="panel-heading">
					<h3><span class="glyphicon glyphicon-warning-sign"></span> <?php echo $this->translate('CAUTION: EXPIRY TIME EXCEEDED'); ?></h3>
				</div>
				<div class="panel-body">
					<form name="formCheckPeremption" role="form" action="<?php echo $this->url('setup', array('action'=>'checkperemption'));?>" method="post">
						<h4><?php echo $this->translate('Injection prohibited unless authorized by Radio-Pharmacist'); ?>
						<p><strong><?php echo $this->translate('To Authorize: Please sign-in with authority account, or Cancel to end the injections.'); ?></strong></p>
						<div class="row">
							<div class="col-md-8 col-md-offset-2">
									<div class="form-group">
										<label for="login"><?php echo $this->translate('User'); ?></label>
										<input type="text" class="form-control" id="login" name="login" placeholder="" autocomplete="off" maxlength="100" required />
									</div>
									<div class="form-group">
										<label for="password"><?php echo $this->translate('Password'); ?></label>
										<input type="password" class="form-control" id="password" name="password" placeholder="" autocomplete="off" maxlength="100" required />
									</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-3 col-md-offset-3">
								<button id="btn-next" type="submit" class="btn btn-success btn-block"><?php echo $this->translate('Valid'); ?></button>
							</div>
							<div class="col-md-3">
								<button id="btn-exit" type="button" class="btn btn-danger btn-block" onclick="location.href='<?php echo $this->url('operator')?>'"><?php echo $this->translate('Cancel'); ?></button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>