<ol class="breadcrumb">
	<li><a href="<?php echo $this->url('operator')?>"><span class="glyphicon glyphicon-home"></span> <?php echo $this->translate("Operator dashboard");?></a></li>
	<li class="active"><?php echo $this->translate("Confirmation of patient's datas"); ?></li>
</ol>
<div class="row">
	<div class="panel-body">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<span class="glyphicon glyphicon-plus-sign"></span> <?php echo $this->translate("Confirmation of patient's datas")?>
			</div>
			<div class="panel-body">
				<form class="form-horizontal" role="form" novalidate="novalidate"  action="<?php echo $this->url('setup', array('action'=>'storecurrentpatient'))?>" method="POST">
					<input type="hidden" id="patient-id" name="patient_id" value="0" />
					
					<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
					  <div class="panel panel-default">
					    <div class="panel-heading" role="tab" id="headingOne">
					      <h4 class="panel-title">
					          <?php echo $this->translate('Selected patient : '); ?><span id="spanFirstname"></span> <span id="spanLastname"></span>
					      </h4>
					    </div>
					    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
					      <div class="panel-body">
					      	<div class="col-md-6">
								<div class="form-group">
									<label for="lastname" class="col-sm-4 control-label"><?php echo $this->translate('Lastname')?></label>
									<div class="col-sm-8">
										<input type="text" class="form-control input-sm" id="lastname" 
										name="lastname" tabindex="1" placeholder="<?php echo $this->translate('ex: Martin'); ?>" autocomplete="off" maxlength="100" required />
									</div>
								</div>
								<div class="form-group">
									<label for="birthdate" class="col-sm-4 control-label"><?php echo $this->translate('Birthdate')?></label>
									<div class="col-sm-8">
										<div class="input-group date" id="datetimepicker-birthday">
											<input type="text" class="form-control" data-format="YYYY-MM-DD" id="birthdate" 
											name="birthdate" tabindex="3" placeholder="<?php echo $this->translate('ex: 1984-03-02'); ?>" autocomplete="off" maxlength="10" required />
											<span class="input-group-addon">
												<span class="glyphicon glyphicon-calendar"></span>
											</span>
										</div>
									</div>
									<script type="text/javascript">
									$(function() {
										$('#datetimepicker-birthday').datetimepicker({
											language: 'fr',
											pickTime: false
										});
									});
									</script>
								</div>
							</div>
							<div class="col-md-6">
								<div class="form-group">
									<label for="firstname" class="col-sm-4 control-label"><?php echo $this->translate('Firstname')?></label>
									<div class="col-sm-8">
										<input type="text" class="form-control input-sm" id="firstname" 
										name="firstname" tabindex="2" placeholder="<?php echo $this->translate('ex: Julie'); ?>" autocomplete="off" maxlength="100" required />
									</div>
								</div>
								<div class="form-group">
									<label for="expeditornum" class="col-sm-4 control-label"><?php echo $this->translate('Expeditor number')?></label>
									<div class="col-sm-8">
										<input type="text" class="form-control input-sm" id="expeditornum" tabindex="5" 
										placeholder="<?php echo $this->translate('ex: 754234'); ?>" maxlength="100" autocomplete="off" />
									</div>
								</div>
							</div>
					    	<div class="col-md-12">
								<div class="form-group">
									<label for="comments" class="col-md-2 control-label"><?php echo $this->translate('Comments');?></label>
									<div class="col-md-10">
										<textarea style="resize:none" class="form-control input-sm" 
										id="comments" name="comments" tabindex="6" rows="3" placeholder="<?php echo $this->translate("Commentaire sur l'examen du patient");?>"></textarea>
									</div>
								</div>
					    	</div>
							<div class="col-md-4 col-md-offset-4">
								<a class="btn btn-success btn-block" onclick="setPatientAndShowExam();"><?php echo $this->translate('Confirm');?></a>
							</div>
					      </div>
					    </div>
					  </div>
					  <div class="panel panel-default">
					    <div class="panel-heading" role="tab" id="headingTwo">
					      <h4 class="panel-title">
					        <?php echo $this->translate('Exams variables'); ?>
					      </h4>
					    </div>
					    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
					      <div class="panel-body">
					      	<div class="row">
						      	<div class="col-sm-4">
									<div class="form-group">
										<label for="examinationid" class="col-sm-4 control-label"><?php echo $this->translate('Examination')?></label>
										<div class="col-sm-8">
											<select class="form-control" id="examination" name="examinationid" tabindex="7" required>
												<option value=""><?php echo $this->translate('Choose an exam'); ?></option>
												<optgroup label="<?php echo $this->translate('Compatible exams'); ?>">
											<?php foreach($examinations['compatible'] as $examination) {?>
												<option value="<?php echo $examination->id;?>"><?php echo $examination->name;?></option>
											<?php } ?>
											<?php if (count($examinations['others']) > 0) { ?>
												<optgroup label="<?php echo $this->translate('Other exams'); ?>">
											<?php foreach($examinations['others'] as $examination) {?>
												<option disabled value="<?php echo $examination->id;?>"><?php echo $examination->name;?></option>
											<?php } ?>
											<?php } ?>
											</select>
										</div>
									</div>
						      	</div>
						      	<div class="col-sm-4">
									<div class="form-group has-info">
										<label for="weight" class="col-sm-4 control-label" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('This field impact the activity'); ?>"><i class="glyphicon glyphicon-info-sign"></i> <?php echo $this->translate('Weight');?></label>
										<div class="col-sm-8">
											<div class="input-group">
												<input type="number" min="1" max="500" class="form-control input-sm" id="weight" 
												name="weight" tabindex="4" autocomplete="off" placeholder="<?php echo $this->translate('ex: 72,25'); ?>" required />
												<span class="input-group-addon">Kg</span>
											</div>
										</div>
									</div>
						      	</div>
						      	<div class="col-sm-4">
									<div class="form-group has-success">
										<label for="activity" class="col-sm-6 control-label"><?php echo $this->translate('Activity for examination');?></label>
										<div class="col-sm-6">
											<div class="input-group">
												<input type="number" class="form-control input-sm" id="activity" name="activity" tabindex="8" autocomplete="off" required />
												<span class="input-group-addon"><?php echo $unit?></span>
											</div>
										</div>
									</div>
						      	</div>
						    </div>
						    <div class="row">
						    	<div class="col-md-6 col-md-offset-6">
									<div class="form-group">
										<label for="activityavailable" class="col-sm-8 control-label"><?php echo $this->translate('Activity available at')?> <span id="activity-time">HH.MM</span></label>
										<div class="col-sm-4">
											<div class="input-group">
												<input type="number" class="form-control input-sm" id="activityavailable" name="activityavailable" value="???" autocomplete="off" readonly />
												<span class="input-group-addon"><?php echo $unit?></span>
											</div>
										</div>
									</div>
						    	</div>
						    </div>
					      </div>
					    </div>
					  </div>
					</div>
					<div class="row">
						<div class="col-md-2 col-md-offset-1">
							<input type="submit" id="submitExam" disabled="disabled" class="btn btn-success btn-block" value="<?php echo $this->translate('Next');?>" />
						</div>
						<div class="col-md-2">
							<button type="button" class="btn btn-primary btn-block" onclick="setMinActivity()"><?php echo $this->translate('Min Activity')?></button>
							<div class="input-group">
								<input type="number" class="form-control input-sm" id="minactivity" name="minactivity" autocomplete="off" disabled />
								<span class="input-group-addon"><?php echo $unit?></span>
							</div>
						</div>
						<div class="col-md-2">
							<button type="button" class="btn btn-primary btn-block" onclick="setMaxActivity()"><?php echo $this->translate('Max Activity')?></button>
							<div class="input-group">
								<input type="number" class="form-control input-sm" id="maxactivity" name="maxactivity" autocomplete="off" disabled />
								<span class="input-group-addon"><?php echo $unit?></span>
							</div>
						</div>
						<div class="col-md-2">
							<button type="button" class="btn btn-primary btn-block" onclick="setNormActivity()"><?php echo $this->translate('Rate')?></button>
							<div class="input-group">
								<input type="number" on class="form-control input-sm" id="averageactivity" name="averageactivity" autocomplete="off" disabled />
								<span class="input-group-addon"><?php echo $unit?>/Kg</span>
							</div>
						</div>
						<div class="col-md-2">
							<button type="button" class="btn btn-danger btn-block" onclick="cancelPatient();"><?php echo $this->translate('Abort');?></button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="alertlowactivity" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title"><span class="glyphicon glyphicon-warning-sign"></span> <?php echo $this->translate('Insufficient activity');?></h4>
			</div>
			<div class="modal-body">
				<?php echo $this->translate('Insufficient activity. Do you want to correct it ?');?>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-success" onclick="lowActivityOperatorResponse('correct');"><?php echo $this->translate('YES');?></button>
				<button type="button" class="btn btn-danger" onclick="lowActivityOperatorResponse('ignore');"><?php echo $this->translate('NO');?></button>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="alerthighactivity" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title"><span class="glyphicon glyphicon-warning-sign"></span> <?php echo $this->translate('Maximum activity reached');?></h4>
			</div>
			<div class="modal-body">
				<?php echo $this->translate('You have reached the maximum acivity. Do you want to correct it ?');?>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-success" onclick="highActivityOperatorResponse('correct');"><?php echo $this->translate('YES');?></button>
				<button type="button" class="btn btn-danger" onclick="highActivityOperatorResponse('abort');"><?php echo $this->translate('NO');?></button>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="alertchoosepatient" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title"><span class="glyphicon glyphicon-warning-sign"></span> <?php echo $this->translate('Insufficient activity');?></h4>
			</div>
			<div class="modal-body">
				<p><?php echo $this->translate("Insufficient activity. You have choose to don't change the activity."); ?></p>
				<div class="alert alert-info">
					<i class="glyphicon glyphicon-question-sign"></i>
					<?php echo $this->translate('Do you want to create / choose another patient ?'); ?>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-success" onclick="lowActivityOperatorResponse('choose');"><?php echo $this->translate('YES');?></button>
				<button type="button" class="btn btn-danger" onclick="lowActivityOperatorResponse('abort');"><?php echo $this->translate('NO');?></button>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">

	$(function () {
	  $('[data-toggle="tooltip"]').tooltip()
	});

	function	setPatientAndShowExam()
	{
		$.ajax({
			url: "<?php echo $this->url('setup', array('action'=>'aupdatepatient'));?>",
			type: "POST",
			data: { 
				'lastname'		: $('#lastname').val(),
				'firstname'		: $('#firstname').val(),
				'birthdate'		: $('#birthdate').val(),
				'weight' 		: $('#weight').val(),
				'expeditornum'	: $('#weight').val(),
			},
			dataType: "json"
		}).done(function(result) {
			loadInjection(<?php echo $patientid;?>);
			$('#collapseOne').collapse('hide');
			$('#collapseTwo').collapse('show');
			$('#submitExam').prop('disabled', false);
		});
	}
				
	function	cancelPatient()
	{
		$.ajax({
			url: "<?php echo $this->url('setup', array('action' => 'ainputsoftexit'));?>",
			type: "GET",
			dataType: "json",
		}).done(function(result) {
			location.href = '<?php echo $this->url('setup', array('action'=>'selectpatient')); ?>';
		});
	}

	//Appel au robot							
	function	setMinActivity()
	{
		$.ajax({
			url: "<?php echo $this->url('setup', array('action'=>'asetactivity'));?>",
			type: "POST",
			dataType: "json",
			data: {"min" : 1}
		}).done(function(result) {
			$('#activity').val(result.activity);
		});
	}

	//Appel au robot
	function	setMaxActivity()
	{
		$.ajax({
			url: "<?php echo $this->url('setup', array('action'=>'asetactivity'));?>",
			type: "POST",
			dataType: "json",
			data: {"max" : 1}
		}).done(function(result) {
			$('#activity').val(result.activity);
		});
	}

	//Appel au robot
	function	setNormActivity()
	{
		$.ajax({
			url: "<?php echo $this->url('setup', array('action'=>'asetactivity'));?>",
			type: "POST",
			dataType: "json",
			data: {"norm" : 1}
		}).done(function(result) {
			$('#activity').val(result.activity);
		});
	}

	// Pas d'appel fait au robot
	function	loadExamination(examinationid)
	{
		$.ajax({
			url: "<?php echo $this->url('setup', array('action'=>'aloadexamination'));?>",
			type: "POST",
			data: { 'examinationid': examinationid },
			dataType: "json"
		}).done(function(result) {
			if (result.error === true) {
				//TODO FAIRE APPARAITRE MESSAGE D"ERREUR ET ANNULER LE PATIENT EN COURS
			} else {
				$('#averageactivity').val(result.examination.rate);
				$('#minactivity').val(result.examination.min);
				$('#maxactivity').val(result.examination.max);
			}
		});

	}

	// Pas d'appel fait au robot
	function	loadInjection(patientid)
	{
		$.ajax({
			url: "<?php echo $this->url('bufferspace', array('action'=>'aloadinjection'));?>",
			type: "POST",
			data: { 'patientid': patientid },
			dataType: "json"
		}).done(function(result) {
			$('#activity').val(result.activity);
			$('#comments').val(result.comments);
			$('#expeditornum').val(result.unique_id);
			if (result.examinationid > 0)  {
				$('#examination').val(result.examinationid);
				loadExamination(result.examinationid);
			}
		});
	}

	// Pas d'appel fait au robot
	function	loadPatient(patientid)
	{
		$('tr.info').removeClass('info');
		$('#patient-'+patientid).addClass('info');
		$.ajax({
			url: "<?php echo $this->url('bufferspace', array('action'=>'aloadpatient'));?>",
			type: "POST",
			data: { 'patientid': patientid },
			dataType: "json"
		}).done(function(result) {
			$('#patient-id').val(result.id);
			$('#lastname').val(result.lastname);
			$('#firstname').val(result.firstname);
			$('#spanLastname').text(result.lastname);
			$('#spanFirstname').text(result.firstname);
			$('#datetimepicker-birthday').data('DateTimePicker').setDate(result.birthdate);
			$('#weight').val(result.weight);
		});
		$('#btn-next').removeAttr('disabled');
	}

	//Appel au robot
	function	loadActivityData()
	{
		$.ajax({
			type: "GET",
			url: "<?php echo $this->url('setup', array('action'=>'agetavailableactivity'))?>",
			dataType: "json"
		}).done(function(result) {
			var data = result;
			$("#activity-time").html(data.time);
			$("#activityavailable").val(data.activity);
			if (Number(data.activity) < Number($("#activity").val()))
			{
				$("#alertlowactivity").modal('show');
			}
		});
	}

	function	lowActivityOperatorResponse(response)
	{
		$('#alertlowactivity').modal('hide');
		$('#alertchoosepatient').modal('hide');
		
		if (response == 'correct') {
			$('#activity').val('');
			$('#activity').focus();
		} else if (response == 'ignore') {
			$("#alertchoosepatient").modal('show');
		}
// 		else if (response == 'choose') {
//			location.href = '<?php echo $this->url('setup', array('action'=>'selectpatient'));?>';
// 		} else if (response == 'abort') {
//			location.href = '<?php echo $this->url('operator');?>';
// 		}
		//TODO Appel pour mettre un log en base de donnée
		
	}

	function	highActivityOperatorResponse(response)
	{
		//TODO
	}

	// A utiliser
	function	checkbeforesubmit() {
		setActivity();
		updatePatient();
		loadExamination($('#examination').val());
	}

	//Appel au robot
	function	setActivity() {
		$.ajax({
			url: "<?php echo $this->url('setup', array('action'=>'asetactivity'));?>",
			type: "POST",
			data: { "activity" : $('#activity').val() },
			dataType: "json"
		}).done(function(result) {
			$('#activity').val(result.activity);
			loadActivityData();
		});	
	}

	function	updateWeight() {
		$.ajax({
			url: "<?php echo $this->url('setup', array('action'=>'aupdatepatient'));?>",
			type: "POST",
			data: { "weight" : $('#weight').val() },
			dataType: "json"
		}).done(function(result) {
			$('#activity').val(result.activity);
			loadActivityData();
		});	
	}

	$(function(){
		loadPatient(<?php echo $patientid;?>);
		loadActivityData();
		
		$('#examination').change(function() {
			loadExamination($('#examination').val());
		});
		
		$('#activity').change(function () {
			setActivity();
		});

		$('#weight').change(function () {
			updateWeight();
		});
	});
</script>
