<ol class="breadcrumb">
	<li><a href="<?php echo $this->url('operator')?>"><span class="glyphicon glyphicon-home"></span> <?php echo $this->translate("Operator dashboard");?></a></li>
	<li class="active"><?php echo $this->translate("Confirmation of patient's datas"); ?></li>
</ol>
<div class="row">
	<div class="panel-body">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<span class="glyphicon glyphicon-plus-sign"></span> <?php echo $this->translate("Confirmation of patient's datas")?>
			</div>
			<div class="panel-body">
				<form class="form-horizontal" name="formconfirm" id="formconfirm" role="form" novalidate="novalidate"  action="<?php echo $this->url('setup', array('action'=>'storecurrentpatient'))?>" method="POST">
					<input type="hidden" id="patient-id" name="patient_id" value="0" />
					
					<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
					  <div class="panel panel-default">
					    <div class="panel-heading" role="tab" id="headingOne">
					      <h4 class="panel-title">
					          <?php echo $this->translate('Selected patient : '); ?> <span id="spanFirstname"></span> <span id="spanLastname"></span>
					      </h4>
					    </div>
					    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
					      <div class="panel-body">
					      	<div class="col-md-6">
								<div class="form-group">
									<label for="lastname" class="col-sm-4 control-label"><?php echo $this->translate('Lastname')?></label>
									<div class="col-sm-8">
										<input type="text" class="form-control input-sm" id="lastname" 
										name="lastname" tabindex="1" placeholder="<?php echo $this->translate('ex: Martin'); ?>" autocomplete="off" maxlength="100" required />
									</div>
								</div>
								<div class="form-group">
									<label for="birthdate" class="col-sm-4 control-label"><?php echo $this->translate('Birthdate')?></label>
									<div class="col-sm-8">
										<div class="input-group date" id="datetimepicker-birthday">
											<input type="text" class="form-control number" data-format="YYYY-MM-DD" id="birthdate" maxlength="10"
											name="birthdate" tabindex="3" placeholder="<?php echo $this->translate('ex: 1984-03-02'); ?>" autocomplete="off" maxlength="10" required />
											<span class="input-group-addon">
												<span class="glyphicon glyphicon-calendar"></span>
											</span>
										</div>
									</div>
									<script type="text/javascript">
									$(function() {
										$('#datetimepicker-birthday').datetimepicker({
											language: 'fr',
											pickTime: false
										});
									});
									</script>
								</div>
							</div>
							<div class="col-md-6">
								<div class="form-group">
									<label for="firstname" class="col-sm-4 control-label"><?php echo $this->translate('Firstname')?></label>
									<div class="col-sm-8">
										<input type="text" class="form-control input-sm" id="firstname" 
										name="firstname" tabindex="2" placeholder="<?php echo $this->translate('ex: Julie'); ?>" autocomplete="off" maxlength="100" required />
									</div>
								</div>
								<div class="form-group">
									<label for="expeditornum" class="col-sm-4 control-label"><?php echo $this->translate('Expeditor number')?></label>
									<div class="col-sm-8">
										<input type="text" class="form-control input-sm number" id="expeditornum" tabindex="5" 
										placeholder="<?php echo $this->translate('ex: 754234'); ?>" maxlength="100" autocomplete="off" />
									</div>
								</div>
							</div>
					    	<div class="col-md-12">
								<div class="form-group">
									<label for="comments" class="col-md-2 control-label"><?php echo $this->translate('Comments');?></label>
									<div class="col-md-10">
										<textarea style="resize:none" class="form-control input-sm" 
										id="comments" name="comments" tabindex="6" rows="3" placeholder="<?php echo $this->translate("Commentaire sur l'examen du patient");?>"></textarea>
									</div>
								</div>
					    	</div>
							<div class="col-md-4 col-md-offset-4">
								<a class="btn btn-success btn-block" onclick="setPatientAndShowExam();"><?php echo $this->translate('Confirm');?></a>
							</div>
					      </div>
					    </div>
					  </div>
					  <div class="panel panel-default">
					    <div class="panel-heading" role="tab" id="headingTwo">
					      <h4 class="panel-title">
					        <?php echo $this->translate('Exams variables'); ?>
					      </h4>
					    </div>
					    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
					      <div class="panel-body">
					      	<div class="row">
						      	<div class="col-sm-4">
									<div class="form-group">
										<label for="examinationid" class="col-sm-4 control-label"><?php echo $this->translate('Examination')?></label>
										<div class="col-sm-8">
											<select class="form-control" id="examination" name="examinationid" tabindex="7" required>
												<option value="">?</option>
												<optgroup label="<?php echo $this->translate('Compatible exams'); ?>">
											<?php foreach($examinations['compatible'] as $examination) {?>
												<option value="<?php echo $examination->id;?>"><?php echo $examination->name;?></option>
											<?php } ?>
											<?php if (count($examinations['others']) > 0) { ?>
												<optgroup label="<?php echo $this->translate('Other exams'); ?>">
											<?php foreach($examinations['others'] as $examination) {?>
												<option disabled value="<?php echo $examination->id;?>"><?php echo $examination->name;?></option>
											<?php } ?>
											<?php } ?>
											</select>
										</div>
									</div>
						      	</div>
						      	<div class="col-sm-4">
									<div class="form-group has-info">
										<label for="weight" class="col-sm-4 control-label" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('This field impact the activity'); ?>"><i class="glyphicon glyphicon-info-sign"></i> <?php echo $this->translate('Weight');?></label>
										<div class="col-sm-8">
											<div class="input-group">
												<input type="number" min="1" max="500" class="form-control input-sm" id="weight" step="0.01"
												name="weight" tabindex="4" autocomplete="off" placeholder="<?php echo $this->translate('ex: 72,25'); ?>" required />
												<span class="input-group-addon">Kg</span>
											</div>
										</div>
									</div>
						      	</div>
						      	<div class="col-sm-4">
									<div class="form-group has-success">
										<label for="activity" class="col-sm-6 control-label"><?php echo $this->translate('Activity for examination');?></label>
										<div class="col-sm-6">
											<div class="input-group">
												<input type="number" class="form-control input-sm" id="activity" name="activity" tabindex="8" autocomplete="off" required />
												<span class="input-group-addon"><?php echo $unit?></span>
											</div>
										</div>
									</div>
						      	</div>
						    </div>
						    <div class="row">
						    	<div class="col-md-6 col-md-offset-6">
									<div class="form-group">
										<label for="activityavailable" class="col-sm-8 control-label"><?php echo $this->translate('Activity available at')?> <span id="activity-time">HH.MM</span></label>
										<div class="col-sm-4">
											<div class="input-group">
												<input type="number" class="form-control input-sm" id="activityavailable" name="activityavailable" value="???" autocomplete="off" readonly />
												<span class="input-group-addon"><?php echo $unit?></span>
											</div>
										</div>
									</div>
						    	</div>
						    </div>
					      </div>
					    </div>
					  </div>
					</div>
					<div class="row">
						<div class="col-md-2 col-md-offset-1">
							<button id="submitExam" disabled="disabled" onclick="submitForm();" class="btn btn-success btn-block">
								<?php echo $this->translate('Next');?>
							</button>
						</div>
						<div class="col-md-2">
							<button type="button" class="btn btn-primary btn-block" onclick="setMinActivity()" id="btnMinActivity" disabled><?php echo $this->translate('Min Activity')?></button>
							<div class="input-group">
								<input type="number" class="form-control input-sm" id="minactivity" name="minactivity" autocomplete="off" disabled />
								<span class="input-group-addon"><?php echo $unit?></span>
							</div>
						</div>
						<div class="col-md-2">
							<button type="button" class="btn btn-primary btn-block" onclick="setMaxActivity()" id="btnMaxActivity" disabled><?php echo $this->translate('Max Activity')?></button>
							<div class="input-group">
								<input type="number" class="form-control input-sm" id="maxactivity" name="maxactivity" autocomplete="off" disabled />
								<span class="input-group-addon"><?php echo $unit?></span>
							</div>
						</div>
						<div class="col-md-2">
							<button type="button" class="btn btn-primary btn-block" onclick="setNormActivity()" id="btnNormActivity" disabled><?php echo $this->translate('Rate')?></button>
							<div class="input-group">
								<input type="number" on class="form-control input-sm" id="averageactivity" name="averageactivity" autocomplete="off" disabled />
								<span class="input-group-addon"><?php echo $unit?>/Kg</span>
							</div>
						</div>
						<div class="col-md-2">
							<button type="button" class="btn btn-danger btn-block" onclick="cancelPatient();"><?php echo $this->translate('Abort');?></button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="alertlowactivity" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title"><span class="glyphicon glyphicon-warning-sign"></span> <?php echo $this->translate('Low activity available');?></h4>
			</div>
			<div class="modal-body">
				<p><?php echo $this->translate('The available activity in the drug is at a low value.');?></p>
				<p><?php echo $this->translate('Please set the activity at a lower value than the available activity or choose another patient.');?></p>
			</div>
			<div class="modal-footer">
				<div class="col-md-5 col-md-offset-1">
					<button type="button" class="btn btn-primary btn-block" onclick="correctActivity('alertlowactivity');"><?php echo $this->translate('Correct the activity');?></button>
				</div>
				<div class="col-md-5">
					<button type="button" class="btn btn-default btn-block" onclick="chooseAnotherPatient('alertlowactivity');"><?php echo $this->translate('Choose another patient');?></button>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="alertmaxactivity" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title"><span class="glyphicon glyphicon-warning-sign"></span> <?php echo $this->translate('Too much activity');?></h4>
			</div>
			<div class="modal-body">
				<p><?php echo $this->translate('Exceeded maximum activity');?></p>
				<p><?php echo $this->translate('The activity you setted is above the maximum limit of the current exam.');?></p>
				<p><?php echo $this->translate('Do you want to correct the activity ?');?></p>
			</div>
			<div class="modal-footer">
				<div class="col-md-3">
					<button type="button" class="btn btn-success btn-block" onclick="correctActivity('alertmaxactivity');"><?php echo $this->translate('YES');?></button>
				</div>
				<div class="col-md-3">
					<button type="button" class="btn btn-danger btn-block" onclick="dontChangeMaxActivity();"><?php echo $this->translate('NO');?></button>
				</div>
				<div class="col-md-5">
					<button type="button" class="btn btn-default btn-block" onclick="chooseAnotherPatient('alertmaxactivity');"><?php echo $this->translate('Choose another patient');?></button>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="alertminactivity" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title"><span class="glyphicon glyphicon-warning-sign"></span> <?php echo $this->translate('Insufficient activity');?></h4>
			</div>
			<div class="modal-body">
				<p><?php echo $this->translate('Insufficient activity for this exam.');?></p>
				<p><?php echo $this->translate('The activity is null or above the min limit of this exam.');?></p>
				<p><?php echo $this->translate('Do you want to correct the activity ?');?></p>
			</div>
			<div class="modal-footer">
				<div class="col-md-3">
					<button type="button" class="btn btn-success btn-block" onclick="correctActivity('alertminactivity');"><?php echo $this->translate('YES');?></button>
				</div>
				<div class="col-md-3">
					<button type="button" class="btn btn-danger btn-block" onclick="dontChangeMinActivity();"><?php echo $this->translate('NO');?></button>
				</div>
				<div class="col-md-5">
					<button type="button" class="btn btn-default btn-block" onclick="chooseAnotherPatient('alertminactivity');"><?php echo $this->translate('Choose another patient');?></button>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="alertmaxcenteractivity" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title"><span class="glyphicon glyphicon-warning-sign"></span> <?php echo $this->translate('Center maximum activity reached');?></h4>
			</div>
			<div class="modal-body">
				<p><?php echo $this->translate('You have reached the maximum activity authorized for your center.');?></p>
				<p><?php echo $this->translate('You can correct it or use this value above the limit.');?></p>
				<p><?php echo $this->translate('The autorization of an autority is required for exceed the maximum value.');?></p>
			</div>
			<div class="modal-footer">
				<div class="col-md-5 col-md-offset-1">
					<button type="button" class="btn btn-success btn-block" onclick="correctActivity('alertmaxcenteractivity');"><?php echo $this->translate('Correct the value');?></button>
				</div>
				<div class="col-md-5">
					<button type="button" class="btn btn-danger btn-block" onclick="authorityConfirm();"><?php echo $this->translate('Use this value');?> <i class="fa fa-key" title=""></i></button>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="alertconfirmauthority" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h3 class="modal-title"><span class="glyphicon glyphicon-warning-sign"></span> <?php echo $this->translate('Confirmation of maxim center activity exceed'); ?></h3>
			</div>
			<div class="modal-body">
				<div class="alert alert-danger hide" role="alert" id="errorConfirm">
					<span id="errorConfirmMessage"></span>
				</div>
				<h4><?php echo $this->translate('Injection prohibited unless authorized by Radio-Pharmacist'); ?>
				<p><strong><?php echo $this->translate('To Authorize: Please sign-in with authority account, or Cancel to end the injections.'); ?></strong></p>
				<div class="row">
					<div class="col-md-8 col-md-offset-2">
							<div class="form-group">
								<label for="login"><?php echo $this->translate('User'); ?></label>
								<input type="text" class="form-control" id="login" name="login" placeholder="" autocomplete="off" maxlength="100" required />
							</div>
							<div class="form-group">
								<label for="password"><?php echo $this->translate('Password'); ?></label>
								<input type="password" class="form-control" id="password" name="password" placeholder="" autocomplete="off" maxlength="100" required />
							</div>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<div class="col-md-4 col-md-offset-2">
					<button id="btn-next" type="button" class="btn btn-success btn-block " onclick="checkAccessAuthority();"><?php echo $this->translate('Validate'); ?></button>
				</div>
				<div class="col-md-4">
					<button id="btn-exit" type="button" class="btn btn-danger btn-block" onclick="correctActivity('alertconfirmauthority');"><?php echo $this->translate('Cancel'); ?></button>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">

	var patientSetted = false;
	var examinaSetted = false;
	var instanceValidActivity = null;
	var activityIsValid = 0;
	var overPassMinActivity = false;
	var overPassMaxActivity = false;
	var overPassCenterActivity = false;
									
	$(function () {
	  $('[data-toggle="tooltip"]').tooltip()
	});

	function	resetOverpass() {
		$('#submitExam').prop('disabled', true);
		overPassMinActivity = false;
		overPassMaxActivity = false;
		overPassCenterActivity = false;
	}
	
	function	checkValidActivityInterval(submitForm)
	{
		instanceValidActivity = window.setInterval(function(){ getActivity(submitForm);}, 5000);
	}

	function	stopValidActivityInterval()
	{
		window.clearInterval(instanceValidActivity);
	}
	
	function	chooseAnotherPatient(idToClose) {
		$.ajax({
			url: "<?php echo $this->url('setup', array('action' => 'acancelpatient'));?>",
			type: "GET",
			cache: false,
			dataType: "json",
		}).done(function(result) {
			$("#" + idToClose).modal('hide');
			location.href = '<?php echo $this->url('setup', array('action'=>'selectpatient')); ?>';
		});
	}
	
	function 	submitForm() {
		$('#submitExam').prop('disabled', true);
 		setActivity(true);
	}
	
	function	dontChangeMaxActivity() {
		$('#alertmaxactivity').modal('hide');
		//TODO Appel a un log en ajax et lancement loadactivitydata onresult
		activityIsValid = 1;
		overPassMaxActivity = true;
		loadActivityData();
	}
	
	function	dontChangeMinActivity() {
		$('#alertminactivity').modal('hide');
		//TODO Appel a un log en ajax et lancement loadactivitydata onresult
		activityIsValid = 1;
		overPassMinActivity = true;
		loadActivityData();
	}
	
	function	checkAccessAuthority() {
		$.ajax({
			url: "<?php echo $this->url('setup', array('action'=>'confirmauthority'));?>",
			type: "POST",
			data: {
				'login'		: $('#login').val(),
				'password'	: $('#password').val(),
				'activity' 	: $('#activity').val(),
			},
			dataType: "json"
		}).done(function(result) {
			$('#errorConfirm').removeClass('hide');
			if (result.error == true) {
				$('#errorConfirm').show();
				$('#errorConfirmMessage').text(result.message);
				$('#login').val('');
				$('#password').val('');
			} else {
				activityIsValid = 1;
				overPassCenterActivity = true;
				loadActivityData();
				$('#errorConfirm').hide();	
				$("#alertconfirmauthority").modal('hide');
			}
		});
	}

	function	correctActivity(idToClose) {
		$('#activity').val('');
		$('#activity').focus();
		$("#" + idToClose).modal('hide');
	}

	function	authorityConfirm() {
		$("#alertmaxcenteractivity").modal('hide');
		$("#alertconfirmauthority").modal({
			backdrop: "static",
			keyboard: false,
			show: true,
		});
	}
	
	function	setPatientAndShowExam()
	{
		$('#spanLastname').text($('#lastname').val());
		$('#spanFirstname').text($('#firstname').val());
		
		$.ajax({
			url: "<?php echo $this->url('setup', array('action'=>'aupdatepatient'));?>",
			type: "POST",
			data: {
				'patientid'		: $('#patient-id').val(),
				'lastname'		: $('#lastname').val(),
				'firstname'		: $('#firstname').val(),
				'birthdate'		: $('#birthdate').val(),
				'expeditornum'	: $('#expeditornum').val(),
				'weight' 		: $('#weight').val(),
			},
			dataType: "json"
		}).done(function(result) {
			loadInjection(<?php echo $patientid;?>);
			$('#collapseOne').collapse('hide');
			$('#collapseTwo').collapse('show');
			patientSetted = true;
		});
	}
				
	function	cancelPatient()
	{
		$.ajax({
			url: "<?php echo $this->url('setup', array('action' => 'acancelpatient'));?>",
			type: "GET",
			cache: false,
			dataType: "json",
		}).done(function(result) {
			location.href = '<?php echo $this->url('setup', array('action'=>'selectpatient')); ?>';
		});
	}

	//Appel au robot							
	function	setMinActivity()
	{
		resetOverpass();
		$.ajax({
			url: "<?php echo $this->url('setup', array('action'=>'asetactivity'));?>",
			type: "POST",
			dataType: "json",
			data: {"min" : 1}
		}).done(function(result) {
			getActivity(false);
		}).fail(function(jqXHR, textStatus, errorThrown) {
			console.log(jqXHR);
			console.log(textStatus);
			console.log(errorThrown);
		}).always(function(data, textStatus, errorThrown) {
			console.info(data);
			console.info(textStatus);
			console.info(errorThrown);
		});
	}

	//Appel au robot
	function	setMaxActivity()
	{
		resetOverpass();
		$.ajax({
			url: "<?php echo $this->url('setup', array('action'=>'asetactivity'));?>",
			type: "POST",
			dataType: "json",
			data: {"max" : 1}
		}).done(function(result) {
			getActivity(false);
		}).fail(function(jqXHR, textStatus, errorThrown) {
			console.log(jqXHR);
			console.log(textStatus);
			console.log(errorThrown);
		}).always(function(data, textStatus, errorThrown) {
			console.info(data);
			console.info(textStatus);
			console.info(errorThrown);
		});
	}

	//Appel au robot
	function	setNormActivity()
	{
		resetOverpass();
		$.ajax({
			url: "<?php echo $this->url('setup', array('action'=>'asetactivity'));?>",
			type: "POST",
			dataType: "json",
			data: {"norm" : 1}
		}).done(function(result) {
			getActivity(false);
		}).fail(function(jqXHR, textStatus, errorThrown) {
			console.log(jqXHR);
			console.log(textStatus);
			console.log(errorThrown);
		}).always(function(data, textStatus, errorThrown) {
			console.info(data);
			console.info(textStatus);
			console.info(errorThrown);
		});
	}

	// Pas d'appel fait au robot
	function	loadExamination(examinationid)
	{
		$.ajax({
			url: "<?php echo $this->url('setup', array('action'=>'aloadexamination'));?>",
			type: "POST",
			data: { 'examinationid': examinationid },
			dataType: "json"
		}).done(function(result) {
			if (result.error === true) {
				//TODO FAIRE APPARAITRE MESSAGE D"ERREUR ET ANNULER LE PATIENT EN COURS
				$('#btnNormActivity').attr('disabled');
				$('#btnMinActivity').attr('disabled');
				$('#btnMaxActivity').attr('disabled');
			} else {
				examinaSetted = true;
				
				$('#btnNormActivity').removeAttr('disabled');
				$('#btnMinActivity').removeAttr('disabled');
				$('#btnMaxActivity').removeAttr('disabled');
				
				$('#averageactivity').val(result.examination.rate);
				$('#minactivity').val(result.examination.min);
				$('#maxactivity').val(result.examination.max);
				setActivity(false);
			}
		});

	}

	// Pas d'appel fait au robot
	function	loadInjection(patientid)
	{
		$.ajax({
			url: "<?php echo $this->url('bufferspace', array('action'=>'aloadinjection'));?>",
			type: "POST",
			data: { 'patientid': patientid },
			dataType: "json"
		}).done(function(result) {
			$('#activity').val(result.activity);

			if (result.activity > 0) {
				setActivity(false);
			}
			
			$('#comments').val(result.comments);
			$('#expeditornum').val(result.unique_id);
			if (result.examinationid > 0)  {
				$('#examination').val(result.examinationid);
				loadExamination(result.examinationid);
			}
		});
	}

	// Pas d'appel fait au robot
	function	loadPatient(patientid)
	{
		$('tr.info').removeClass('info');
		$('#patient-'+patientid).addClass('info');
		$.ajax({
			url: "<?php echo $this->url('bufferspace', array('action'=>'aloadpatient'));?>",
			type: "POST",
			data: { 'patientid': patientid },
			dataType: "json"
		}).done(function(result) {
			$('#patient-id').val(result.id);
			$('#lastname').val(result.lastname);
			$('#firstname').val(result.firstname);
			$('#spanLastname').text(result.lastname);
			$('#spanFirstname').text(result.firstname);
			$('#datetimepicker-birthday').data('DateTimePicker').setDate(result.birthdate);
			$('#weight').val(result.weight);
			$('#comments').val(result.comments);
			$('#expeditornum').val(result.expeditornum);
		});
		$('#btn-next').removeAttr('disabled');
	}

	//Appel au robot
	function	loadActivityData()
	{
		$.ajax({
			type: "GET",
			cache: false,
			url: "<?php echo $this->url('setup', array('action'=>'agetavailableactivity'))?>",
			dataType: "json"
		}).done(function(result) {
			var data = result;
			$("#activity-time").html(data.time);
			$("#activityavailable").val(data.activity);
			if (patientSetted == true && examinaSetted == true && $('#activity').val() > 0 && activityIsValid == 1) {
				$('#submitExam').prop('disabled', false);
			}
		});
	}

	function getActivity(submitForm) {
		stopValidActivityInterval();
		$.ajax({
			url: "<?php echo $this->url('setup', array('action'=>'agetactivity'));?>",
			type: "POST",
			dataType: "json"
		}).done(function(result) {
			activityIsValid = result.activityisvalid;
			if (activityIsValid < 0) {
				if (activityIsValid == -1) {
					$("#alertlowactivity").modal({
						backdrop: "static",
						keyboard: false,
						show: true,
					});
				} else if (activityIsValid == -2 && overPassCenterActivity == false) {
					$("#alertmaxcenteractivity").modal({
						backdrop: "static",
						keyboard: false,
						show: true,
					});
				} else if (activityIsValid == -3 && overPassMinActivity == false) {
					$("#alertminactivity").modal({
						backdrop: "static",
						keyboard: false,
						show: true,
					});
				} else if (activityIsValid == -4 && overPassMaxActivity == false) {
					$("#alertmaxactivity").modal({
						backdrop: "static",
						keyboard: false,
						show: true,
					});
				} else {
					activityIsValid = 1;
				}
			}

			if (activityIsValid == 1) {
				$('#activity').val(result.activity);
				if (submitForm == true) {
					$('#formconfirm').submit();
				} else {
					loadActivityData();
				}
			} else if (activityIsValid == 0) {
				checkValidActivityInterval(submitForm);
			}
		});	
	}
	
	//Appel au robot
	function	setActivity(submitForm) {
		$.ajax({
			url: "<?php echo $this->url('setup', array('action'=>'asetactivity'));?>",
			type: "POST",
			data: { "activity" : $('#activity').val() },
			dataType: "json"
		}).done(function(result) {
			if (result.error == false) {
				getActivity(submitForm);
			}
		});	
	}

	function	updateWeight() {
		$.ajax({
			url: "<?php echo $this->url('setup', array('action'=>'aupdatepatient'));?>",
			type: "POST",
			data: { "weight" : $('#weight').val() },
			dataType: "json"
		}).done(function(result) {
			getActivity(false);
		});	
	}

	$(function() {
		loadPatient(<?php echo $patientid;?>);
		loadActivityData();
		
		$('#examination').change(function() {
			$('#submitExam').prop('disabled', true);
			if ($('#examination').val() > 0) {
				loadExamination($('#examination').val());
			} else {
				$('#btnNormActivity').attr('disabled');
				$('#btnMinActivity').attr('disabled');
				$('#btnMaxActivity').attr('disabled');
			}
		});
		
		$('#activity').change(function () {
			console.log('activity change =>' + $('#activity').val());
			$('#submitExam').prop('disabled', true);
			resetOverpass();
			setActivity(false);
		});

		$('#weight').change(function () {
			$('#submitExam').prop('disabled', true);
			updateWeight();
		});
	});
</script>
