<ol class="breadcrumb">
	<li><a href="<?php echo $this->url('operator')?>"><span class=" glyphicon glyphicon-home"></span> <?php echo $this->translate('Operator dashboard')?></a></li>
	<li class="active"><?php echo $this->translate('Creation of patient')?></li>
</ol>

<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="panel-body">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<span class="glyphicon glyphicon-plus-sign"></span> <?php echo $this->translate('Creation of patient')?>
				</div>
				<div class="panel-body">
					<form class="form-horizontal" role="form" method="post" action="<?php echo $this->url('setup', array('action'=>'createpatient')) ?>">
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<label for="lastname" class="col-sm-4 control-label"><?php echo $this->translate('Lastname')?></label>
									<div class="col-sm-8">
										<input type="text" tabindex="1" class="form-control input-sm" id="lastname" name="lastname" 
										 autocomplete="off" maxlength="100" required />
									</div>
								</div>
								<div class="form-group">
									<label for="birthdate" class="col-sm-4 control-label"><?php echo $this->translate('Birthdate')?></label>
									<div class="col-sm-8">
										<div class="input-group date" id="datetimepicker-birthday">
											<input type="text" tabindex="3" class="form-control input-sm input-date" data-format="YYYY-MM-DD" id="birthdate" name="birthdate" 
											autocomplete="off" maxlength="10" placeholder="YYYY-MM-DD" required />
											<span class="input-group-addon">
												<span class="glyphicon glyphicon-calendar"></span>
											</span>
										</div>
									</div>
									<script type="text/javascript">
									$(function() {
										$('#datetimepicker-birthday').datetimepicker({
											locale: 'fr',
											format: 'YYYY-MM-DD',
											allowInputToggle: true,
											viewMode: 'decades',
										});
									});
									</script>
								</div>

								<div class="form-group">
									<label for="input4" class="col-sm-4 control-label"><?php echo $this->translate('Expeditor number')?></label>
									<div class="col-sm-8">
										<input type="text" tabindex="5" class="form-control input-sm number" id="expeditornum" name="expeditornum" 
										 autocomplete="off" maxlength="100" />
									</div>
								</div>
								<div class="form-group">
									<label for="input5" class="col-sm-4 control-label"><?php echo $this->translate('Examination')?></label>
									<div class="col-sm-8">
										<select class="form-control" id="examination" name="examination" tabindex="7" required>
											<option value=""><?php echo $this->translate('Choose an exam'); ?></option>
											<optgroup label="<?php echo $this->translate('Compatible exams'); ?>">
										<?php foreach($examinations['compatible'] as $examination) {?>
												<option value="<?php echo $examination->id;?>" data-dci="<?php echo $examination->dci; ?>">
													<?php echo $examination->name;?>
												</option>
										<?php } ?>
											</optgroup>
											<optgroup label="<?php echo $this->translate('Other exams'); ?>">
										<?php foreach($examinations['others'] as $examination) {?>
												<option disabled value="<?php echo $examination->id;?>" data-dci="<?php echo $examination->dci; ?>">
													<?php echo $examination->name;?>
												</option>
										<?php } ?>
											</optgroup>
										</select>
									</div>
								</div>
								<div class="form-group">
									<label for="dci" class="col-sm-4 control-label"><?php echo $this->translate('DCI')?></label>
									<div class="col-sm-8">
										<select class="form-control" tabindex="9" id="dci" name="dci" disabled>
											<option value=""></option>
										<?php foreach($dcis as $dci) {?>
											<option value="<?php echo $dci->dci;?>"><?php echo $dci->dci;?></option>
										<?php } ?>
										</select>
									</div>
								</div>
							</div>
							<div class="col-md-6">
								<div class="form-group">
									<label for="input8" class="col-sm-4 control-label"><?php echo $this->translate('Firstname')?></label>
									<div class="col-sm-8">
										<input type="text" tabindex="2" class="form-control input-sm" id="firstname" name="firstname" 
										 autocomplete="off" maxlength="100" required />
									</div>
								</div>
								<div class="form-group">
									<label for="input7" class="col-sm-4 control-label"><?php echo $this->translate('Weight');?></label>
									<div class="col-sm-8">
										<div class="input-group">
											<input type="number" min="1" max="500" step="0.01" tabindex="4" class="form-control input-sm" id="weight" name="weight" 
											 autocomplete="off" />
											<span class="input-group-addon">Kg</span>
										</div>
									</div>
								</div>
								<div class="form-group">
									<label for="selected-patient" class="col-sm-4 control-label"><?php echo $this->translate('Gender')?></label>
									<div class="col-sm-8">
										<select class="form-control input-sm" tabindex="6" id="gender" name="gender" required>
											<option value=""><?php echo $this->translate('Select gender...');?></option>
											<option value="F"><?php echo $this->translate('F');?></option>
											<option value="M"><?php echo $this->translate('M');?></option>
											<option value="U"><?php echo $this->translate('U');?></option>
										</select>
									</div>
								</div>
								<div class="form-group">
									<label for="input3" class="col-sm-4 control-label"><?php echo $this->translate('Comments');?></label>
									<div class="col-sm-8">
										<textarea style="resize:none" tabindex="8" class="form-control input-sm" id="comment" name="comment" rows="3"></textarea>
									</div>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-2 col-md-offset-4">
								<input type="submit" class="btn btn-success btn-block" value="<?php echo $this->translate('Next');?>" />
							</div>
							<div class="col-md-2">
								<button type="button" class="btn btn-danger btn-block" onclick="location.href='<?php echo $this->url('setup', array('action'=>'selectpatient'))?>'">
									<?php echo $this->translate('Abort');?>
								</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	$(function(){
		$(document).on("change","#examination", function() {
			var dci = $("#examination option:selected").data('dci');
 			$('#dci').val(dci);
		});
	});
</script>