<ol class="breadcrumb">
	<li><a href="<?php echo $this->url('operator')?>"><span class=" glyphicon glyphicon-home"></span> <?php echo $this->translate('Operator\'s dashboard')?></a></li>
	<li class="active"><?php echo $this->translate('Filling drug\'s informations')?></li>
</ol>
<div class="row">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<span class="glyphicon glyphicon-file"></span> <?php echo $this->translate('Filling drug\'s informations')?>
		</div>
		<div class="panel-body">
			<form class="form-horizontal" role="form" action="<?php echo $this->url('setup', array('action'=>'drug'))?>" method="POST" onSubmit="return checkForm();">
				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<label for="inputEmail3" class="col-sm-6 control-label"><?php echo $this->translate('Drug name'); ?></label>
							<div class="col-sm-6">
								<select class="form-control input-sm" id="drugid" name="drugid" tabindex="1" required>
									<option value=""><?php echo $this->translate('Select a drug'); ?></option>
								<?php foreach($this->drugs as $drug) { ?>
									<option value="<?php echo $drug->id?>"><?php echo '[' . $drug->dci . ']' . ' ' . $drug->name;?></option>
								<?php } ?>
								</select>
							</div>
						</div>
						<div class="form-group">
							<label for="input3" class="col-sm-6 control-label"><?php echo $this->translate('Calibration time')?></label>
							<div class="col-sm-6">
								<div class="input-group date" id="datetimepicker-calibration">
									<input type="text" class="form-control input-sm input-date" data-format="YYYY-MM-DD HH:mm" placeholder="YYYY-MM-DD HH:mm" id="calibrationtime" name="calibrationtime" autocomplete="off" tabindex="5" maxlength="16" required />
									<span class="input-group-addon">
										<span class="glyphicon glyphicon-calendar"></span>
									</span>
								</div>
							</div>
							<script type="text/javascript">
								$(function() {
									$('#datetimepicker-calibration').datetimepicker({
										language: 'en'
									});
								});
							</script>
						</div>
						<div class="form-group">
							<label for="input3" class="col-sm-6 control-label"><?php echo $this->translate('Vial volume')?></label>
							<div class="col-sm-6">
								<div class="input-group">
									<input type="number" class="form-control input-sm" id="vialvol" name="vialvol" step="any" min="0" placeholder="ex: 200,5" autocomplete="off" tabindex="3" required  />
									<span class="input-group-addon">ml</span>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label for="input3" class="col-sm-6 control-label"><?php echo $this->translate('Activity concentration')?></label>
							<div class="col-sm-6">
								<div class="input-group">
									<input type="number" class="form-control input-sm" id="activityconc" name="activityconc" step="any" min="0"  placeholder="ex: 12,5" autocomplete="off"  tabindex="7" disabled required />
									<span class="input-group-addon"><?php echo $unit?>/ml</span>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<label for="input3" class="col-sm-6 control-label"><?php echo $this->translate('Batch number')?></label>
							<div class="col-sm-6">
								<input type="text" class="form-control input-sm" id="batchnum" name="batchnum" placeholder="ex: FG120925A-04" autocomplete="off" tabindex="2" maxlength="100" required />
							</div>
						</div>
						<div class="form-group">
							<label for="input3" class="col-sm-6 control-label"><?php echo $this->translate('Expiration time')?></label>
							<div class="col-sm-6">
								<div class="input-group date" id="datetimepicker-peremption">
									<input type="text" class="form-control input-sm input-date" data-format="YYYY-MM-DD HH:mm" placeholder="YYYY-MM-DD HH:mm" id="expirationtime" name="expirationtime" autocomplete="off" tabindex="4" maxlength="16" required />
									<span class="input-group-addon">
										<span class="glyphicon glyphicon-calendar"></span>
									</span>
								</div>
							</div>
							<script type="text/javascript">
								$(function() {
									$('#datetimepicker-peremption').datetimepicker({
										language: 'en'
									});
								});
							</script>
						</div>
						<div class="form-group">
							<label for="input3" class="col-sm-6 control-label"><?php echo $this->translate('Activity at calibration time')?></label>
							<div class="col-sm-6">
								<div class="input-group">
									<input type="number" class="form-control input-sm" id="activitycalib" name="activitycalib" placeholder="" tabindex="6" autocomplete="off" disabled required />
									<span class="input-group-addon"><?php echo $unit?></span>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label for="activity" class="col-sm-6 control-label"><?php echo $this->translate('Activity available at')?> <span id="activity-time">HH.MM</span></label>
							<div class="col-sm-6">
								<div class="input-group">
									<input type="number" class="form-control input-sm" id="activity" name="activity" value="???" autocomplete="off" readonly/>
									<span class="input-group-addon"><?php echo $unit?></span>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="alert alert-info">
					<span class="glyphicon glyphicon-exclamation-sign"></span>
					<?php echo $this->translate('Fill the vial volume field to enable fields about activity')?>
				</div>
				<div class="row">
					<div class="col-md-2 col-md-offset-4">
						<input type="submit" class="btn btn-success btn-block" value="<?php echo $this->translate('Next')?>"/>
					</div>
					<div class="col-md-2">
						<button type="button" class="btn btn-danger btn-block" onclick="cancel();"><?php echo $this->translate('Abort')?></button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
<script type="text/javascript">
	/**
	 * @todo fill the tests
	 */
	function	checkForm()
	{
		if(true)
		{
			return true;
		}
		else
		{
			return false;
		}
	}

	function	cancel()
	{
		$.ajax({
			url: "<?php echo $this->url('setup', array('action' => 'ainputsoftexit'));?>",
			type: "GET",
			dataType: "json",
		}).done(function(result) {
			location.href = '<?php echo $this->url('operator'); ?>';
		});
	}
	

	function	loadActivityData()
	{
		$.ajax({
			type: "GET",
			url: "<?php echo $this->url('setup', array('action'=>'agetavailableactivity'))?>",
			dataType: "json"
		}).done(function(result) {
			var data = result;
			$("#activity-time").html(data.time);
			$("#activity").val(data.activity).trigger('change');
		});
		setTimeout(function(){loadActivityData();}, 10000);
	}

	$(function() {
		loadActivityData();

		//Envoie le batchnum
		$('#batchnum').change(function() {
			$.ajax({
	        	type: "POST",
	        	url: "<?php echo $this->url('setup', array('action'=>'aupdatedrug'))?>",
	        	dataType: "json",
	        	data: {"batchnum" : $("#batchnum").val()}
	      	});
		});

		//Envoie le médicament selectionné
		$('#drugid').change(function() {
			$.ajax({
	        	type: "POST",
	        	url: "<?php echo $this->url('setup', array('action'=>'aupdatedrug'))?>",
	        	dataType: "json",
	        	data: {"drugid" : $("#drugid").val()}
	      	});
		});

		//Envoie la date de calibration
		$("#calibrationtime").change(function() {
	    	$.ajax({
	        	type: "POST",
	        	url: "<?php echo $this->url('setup', array('action'=>'aupdatedrug'))?>",
	        	dataType: "json",
	        	data: {'calibrationtime': $("#calibrationtime").val() }
	      	});
		});

		//Envoie la date de calibration
		$('#datetimepicker-calibration').change(function() {
			$.ajax({
	        	type: "POST",
	        	url: "<?php echo $this->url('setup', array('action'=>'aupdatedrug'))?>",
	        	dataType: "json",
	        	data: {'calibrationtime': $("#calibrationtime").val() }
	      	});
		});

		//Envoie la date d'expiration
		$("#expirationtime").change(function() {
	    	$.ajax({
	        	type: "POST",
	        	url: "<?php echo $this->url('setup', array('action'=>'aupdatedrug'))?>",
	        	dataType: "json",
	        	data: {'expirationtime': $("#expirationtime").val() }
	      	});
		});

		$('#datetimepicker-peremption').change(function() {
			$.ajax({
	        	type: "POST",
	        	url: "<?php echo $this->url('setup', array('action'=>'aupdatedrug'))?>",
	        	dataType: "json",
	        	data: {'expirationtime': $("#expirationtime").val() }
	      	});
		});

		$('#vialvol').change(function() {
			$('#activityconc').removeAttr('disabled');
			$('#activitycalib').removeAttr('disabled');
			$.ajax({
	        	type: "POST",
	        	url: "<?php echo $this->url('setup', array('action'=>'aupdatedrug'))?>",
	        	dataType: "json",
	        	data: {'vialvol': $("#vialvol").val() }
	      	});
		});

		$("#activityconc").change(function() {
			console.log('activityconc');
			$.ajax({
				type: "POST",
				url: "<?php echo $this->url('setup', array('action'=>'aupdatedrug'))?>",
				dataType: "json",
				data: { 'activityconc': $("#activityconc").val() }
			}).done(function() {
		
				$.ajax({
					type: "POST",
					url: "<?php echo $this->url('setup', array('action'=>'arecalcactivity'));?>",
					dataType:"json",
					data : {"field" : "calib"}
				}).done(function(result) {
					$('#activitycalib').val(result["activitycalib"]);
				});
			});
		});

		$("#activitycalib").change(function(){
			$.ajax({
				type: "POST",
				url: "<?php echo $this->url('setup', array('action'=>'aupdatedrug'));?>",
				dataType:"json",
				data: { "activitycalib": $('#activitycalib').val() },
			}).done(function() {
				$.ajax({
					type: "POST",
					url: "<?php echo $this->url('setup', array('action'=>'arecalcactivity'));?>",
					dataType:"json",
					data : {"field" : "conc"}
				}).done(function(result) {
					$('#activityconc').val(result.activityconc);
				});
			});
		});


		$("#activity").change(function() {
			var activity = $("#activity").val();
			if (activity == -1) {
				if ($("#expirationtime").val() != '') {
					alert('LA DATE D EXPIRATION EST FAUSSE');
				}
			}
			else if (activity == -2) {
				if ($("#activityconc").val() != '') {
					alert('L ACTIVITE VOLUMIQUE EST FAUSSE');
				}
			}
			else if (activity == -3) {
				if ($("#activitycalib").val() != '') {
					alert('L ACTIVITE A CALIBRATION EST FAUSSE');
				}
			}
			else if (activity == -4) {
				if ($("#vialvol").val() != '') {
					alert('LE VOLUME DE LA FIOLE EST INCORRECT');
				}
			}
		});
	});
</script>
