<ol class="breadcrumb">
	<li><a href="<?php echo $this->url('operator')?>"><span class=" glyphicon glyphicon-home"></span> <?php echo $this->translate('Operator\'s dashboard')?></a></li>
	<li class="active"><?php echo $this->translate('Filling drug\'s informations')?></li>
</ol>
<div class="row">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<span class="glyphicon glyphicon-file"></span> <?php echo $this->translate('Filling drug\'s informations')?>
		</div>
		<div class="panel-body">
			<form class="form-horizontal" role="form" action="<?php echo $this->url('setup', array('action'=>'drug'))?>" method="POST" onSubmit="return checkForm();">
				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<label for="inputEmail3" class="col-sm-6 control-label"><?php echo $this->translate('Drug name'); ?></label>
							<div class="col-sm-6">
								<select class="form-control input-sm" id="drugid" name="drugid" tabindex="1" required>
									<option value=""><?php echo $this->translate('Select a drug'); ?></option>
								<?php foreach($this->drugs as $drug) { ?>
									<option value="<?php echo $drug->id?>"><?php echo '[' . $drug->dci . ']' . ' ' . $drug->name;?></option>
								<?php } ?>
								</select>
							</div>
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<label for="input3" class="col-sm-6 control-label"><?php echo $this->translate('Batch number')?></label>
							<div class="col-sm-6">
								<input type="text" class="form-control input-sm" id="batchnum" name="batchnum" placeholder="ex: FG120925A-04" autocomplete="off" tabindex="2" maxlength="100" required />
							</div>
						</div>
					</div>
				</div>	
				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<label for="input3" class="col-sm-6 control-label"><?php echo $this->translate('Calibration date')?></label>
							<div class="col-sm-6">
								<div class="input-group date" id="datepicker-calibration">
									<input type="text" class="form-control input-sm input-date" data-format="YYYY-MM-DD" placeholder="YYYY-MM-DD" id="calibrationdate" name="calibrationdate" autocomplete="off" tabindex="4" maxlength="10" required />
									<span class="input-group-addon">
										<span class="glyphicon glyphicon-calendar" style="padding-left: 30px; padding-right: 30px;"></span>
									</span>
								</div>
							</div>
							<script type="text/javascript">
								$(function() {
									$('#datepicker-calibration').datetimepicker({
										locale: '<?php echo $locale; ?>',
										minDate: moment(),
										allowInputToggle: true,
										showClose: true,
										format: 'YYYY-MM-DD',
									});
								});
							</script>
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<label for="input3" class="col-sm-6 control-label"><?php echo $this->translate('Calibration time')?></label>
							<div class="col-sm-6">
								<div class="input-group date" id="datetimepicker-calibration">
									<input type="text" class="form-control input-sm input-date" data-format="hh:mm" placeholder="hh:mm" id="calibrationtime" name="calibrationtime" autocomplete="off" tabindex="5" maxlength="5" required />
									<span class="input-group-addon">
										<span class="glyphicon glyphicon-time" style="padding-left: 30px; padding-right: 30px;"></span>
									</span>
								</div>
							</div>
							<script type="text/javascript">
								$(function() {
									$('#datetimepicker-calibration').datetimepicker({
										locale: '<?php echo $locale; ?>',
										format: 'HH:mm',
										showClose: true,
										allowInputToggle: true,
									});
								});
							</script>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<label for="input3" class="col-sm-6 control-label"><?php echo $this->translate('Expiration date')?></label>
							<div class="col-sm-6">
								<div class="input-group date" id="datepicker-peremption">
									<input type="text" class="form-control input-sm input-date" data-format="YYYY-MM-DD" placeholder="YYYY-MM-DD" id="expirationdate" name="expirationdate" autocomplete="off" tabindex="4" maxlength="10" required />
									<span class="input-group-addon">
										<span class="glyphicon glyphicon-calendar" style="padding-left: 30px; padding-right: 30px;"></span>
									</span>
								</div>
							</div>
							<script type="text/javascript">
								$(function() {
									$('#datepicker-peremption').datetimepicker({
										locale: '<?php echo $locale; ?>',
										minDate: moment(),
										allowInputToggle: true,
										showClose: true,
										format: 'YYYY-MM-DD',
									});
								});
							</script>
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<label for="input3" class="col-sm-6 control-label"><?php echo $this->translate('Expiration time')?></label>
							<div class="col-sm-6">
								<div class="input-group date" id="datetimepicker-expiration">
									<input type="text" class="form-control input-sm input-date" data-format="hh:mm" placeholder="hh:mm" id="expirationtime" name="expirationtime" autocomplete="off" tabindex="5" maxlength="5" required />
									<span class="input-group-addon">
										<span class="glyphicon glyphicon-time" style="padding-left: 30px; padding-right: 30px;"></span>
									</span>
								</div>
							</div>
							<script type="text/javascript">
								$(function() {
									$('#datetimepicker-expiration').datetimepicker({
										locale: '<?php echo $locale; ?>',
										format: 'HH:mm',
										showClose: true,
										allowInputToggle: true,
									});
								});
							</script>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-6">
						<div class="form-group has-info">
							<label for="input3" class="col-sm-6 control-label"><?php echo $this->translate('Vial volume')?></label>
							<div class="col-sm-6">
								<div class="input-group">
									<input type="number" class="form-control input-sm" id="vialvol" name="vialvol" step="0.01" min="<?php echo $vialvol_min; ?>" max="<?php echo $vialvol_max; ?>" placeholder="ex: 10" autocomplete="off" tabindex="3" required  />
									<span class="input-group-addon">ml</span>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group" id="divActivityCalib">
							<label for="input3" class="col-sm-6 control-label"><?php echo $this->translate('Activity at calibration time')?></label>
							<div class="col-sm-6">
								<div class="input-group">
									<input type="number" class="form-control input-sm" id="activitycalib" name="activitycalib" placeholder="ex: 123.45" step="0.01" tabindex="6" autocomplete="off" disabled required />
									<span class="input-group-addon"><?php echo $unit?></span>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-6">
						<div class="form-group" id="divActivityConc">
							<label for="input3" class="col-sm-6 control-label"><?php echo $this->translate('Activity concentration')?></label>
							<div class="col-sm-6">
								<div class="input-group">
									<input type="number" class="form-control input-sm" id="activityconc" name="activityconc" step="0.01" min="0"  placeholder="ex: 200,52" autocomplete="off"  tabindex="7" disabled required />
									<span class="input-group-addon"><?php echo $unit?>/ml</span>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<label for="activity" class="col-sm-6 control-label"><?php echo $this->translate('Activity available at')?> <span id="activity-time">HH.MM</span></label>
							<div class="col-sm-6">
								<div class="input-group">
									<input type="number" class="form-control input-sm" id="activity" name="activity" value="" autocomplete="off" readonly/>
									<span class="input-group-addon"><?php echo $unit?></span>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="alert alert-info col-md-3">
					<span class="glyphicon glyphicon-exclamation-sign"></span>
					<?php echo $this->translate('Fill the vial volume field to enable fields about activity')?>
				</div>
				<div class="alert alert-warning col-md-3 col-md-offset-1">
					<span class="glyphicon glyphicon-exclamation-sign"></span>
					<?php echo $this->translate('The last filled value is in yellow')?>
				</div>
				<div class="alert alert-success col-md-3 col-md-offset-1">
					<span class="glyphicon glyphicon-exclamation-sign"></span>
					<?php echo $this->translate('The green field represents the calculated value')?>
				</div>
				<div class="row">
					<div class="col-md-2 col-md-offset-4">
						<input type="submit" class="btn btn-success btn-block" value="<?php echo $this->translate('Next')?>"/>
					</div>
					<div class="col-md-2">
						<button type="button" class="btn btn-danger btn-block" onclick="cancel();"><?php echo $this->translate('Abort')?></button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
<script type="text/javascript">
	var lastChange = null;
	var focusField = null;

	function checkInputOnChange(e, keyboard, el) {
// 		console.log(e);
// 		console.warn(keyboard);
		console.info(keyboard.preview.value);
	}	
							
	/**
	 * @todo fill the tests
	 */
	function	checkForm()
	{
		if(true)
		{
			return true;
		}
		else
		{
			return false;
		}
	}

	function	cancel()
	{
		$.ajax({
			url: "<?php echo $this->url('setup', array('action' => 'ainputsoftexit'));?>",
			type: "GET",
			cache: false,
			dataType: "json",
		}).done(function(result) {
			location.href = '<?php echo $this->url('operator'); ?>';
		});
	}

	function	checkActivityDataByInterval() {
		setTimeout(function() {
			loadActivityData(true);
		}, 60000);
	}

	function	loadActivityData(reload)
	{
		$.ajax({
			type: "GET",
			cache: false,
			url: "<?php echo $this->url('setup', array('action'=>'agetavailableactivity'))?>",
			dataType: "json"
		}).done(function(result) {
			var data = result;
			$("#activity-time").html(data.time);
			$("#activity").val(data.activity).trigger('change');

			if (reload === true) {
				checkActivityDataByInterval();
			}
		});
	}

	function	setFocusOnField() {
		if (focusField != '') {
			$('#' + focusField).val('');
			$('#' + focusField).focus();
		}
		$("#alertdata").modal('hide');
	}

	$(function() {
		checkActivityDataByInterval();

		//Envoie le batchnum
		$('#batchnum').change(function() {
			$.ajax({
	        	type: "POST",
	        	url: "<?php echo $this->url('setup', array('action'=>'aupdatedrug'))?>",
	        	dataType: "json",
	        	data: {"batchnum" : $("#batchnum").val()}
	      	});
		});

		//Envoie le médicament selectionné
		$('#drugid').change(function() {
			$.ajax({
	        	type: "POST",
	        	url: "<?php echo $this->url('setup', array('action'=>'aupdatedrug'))?>",
	        	dataType: "json",
	        	data: {"drugid" : $("#drugid").val()}
	      	});
		});

		//Envoie la date de calibration
		$("#datetimepicker-calibration").on("dp.hide", function(e) {
			$.ajax({
	        	type: "POST",
	        	url: "<?php echo $this->url('setup', array('action'=>'aupdatedrug'))?>",
	        	dataType: "json",
	        	data: {'calibrationtime': $("#calibrationtime").val() }
	      	});
		});
		
		//Envoie la date d'expiration
		$("#datetimepicker-peremption").on("dp.hide", function(e) {
			$.ajax({
	        	type: "POST",
	        	url: "<?php echo $this->url('setup', array('action'=>'aupdatedrug'))?>",
	        	dataType: "json",
	        	data: {'expirationtime': $("#expirationtime").val() }
			}).done(function(result) {
	      		loadActivityData(false);
		    });
		});

		$('#vialvol').change(function() {
			$('#activityconc').removeAttr('disabled');
			$('#activitycalib').removeAttr('disabled');
			$.ajax({
	        	type: "POST",
	        	url: "<?php echo $this->url('setup', array('action'=>'aupdatedrug'))?>",
	        	dataType: "json",
	        	data: {'vialvol': $("#vialvol").val() }
	      	}).done(function(result) {
				var data = null;
		      	if (lastChange == 'activityconc') {
			      	data = {"field" : "calib"};
		      	} else if (lastChange == 'activitycalib') {
		      		data = {"field" : "conc"};
		      	}
		      	
 	      		$.ajax({
 					type: "POST",
					url: "<?php echo $this->url('setup', array('action'=>'arecalcactivity'));?>",
 					dataType:"json",
 					data : data
 				}).done(function(result) {
 					if (lastChange == 'activityconc') {
 				      	data = {"field" : "calib"};
 				      	$('#activitycalib').val(result.activitycalib);
 			      	} else if (lastChange == 'activitycalib') {
	 					$('#activityconc').val(result.activityconc);
 			      	}
 					loadActivityData(false);
 				});
			});
		});

		$("#activityconc").change(function() {
			lastChange = 'activityconc';

			$("#divActivityCalib").removeClass('has-warning');
			$("#divActivityCalib").removeClass('has-success');
			$("#divActivityConc").removeClass('has-warning');
			$("#divActivityConc").removeClass('has-success');

			$("#divActivityConc").addClass('has-warning');
			
			$.ajax({
				type: "POST",
				url: "<?php echo $this->url('setup', array('action'=>'aupdatedrug'))?>",
				dataType: "json",
				data: { 'activityconc': $("#activityconc").val() }
			}).done(function() {
				$.ajax({
					type: "POST",
					url: "<?php echo $this->url('setup', array('action'=>'arecalcactivity'));?>",
					dataType:"json",
					data : {"field" : "calib"}
				}).done(function(result) {
					$("#divActivityCalib").addClass('has-success');
					$('#activitycalib').val(result["activitycalib"]);
					loadActivityData(false);
				});
			});
		});

		$("#activitycalib").change(function() {
			lastChange = 'activitycalib';

			$("#divActivityCalib").removeClass('has-warning');
			$("#divActivityCalib").removeClass('has-success');
			$("#divActivityConc").removeClass('has-warning');
			$("#divActivityConc").removeClass('has-success');
			
			$("#divActivityCalib").addClass('has-warning');
			
			$.ajax({
				type: "POST",
				url: "<?php echo $this->url('setup', array('action'=>'aupdatedrug'));?>",
				dataType:"json",
				data: { "activitycalib": $('#activitycalib').val() },
			}).done(function() {
				$.ajax({
					type: "POST",
					url: "<?php echo $this->url('setup', array('action'=>'arecalcactivity'));?>",
					dataType:"json",
					data : {"field" : "conc"}
				}).done(function(result) {
					$("#divActivityConc").addClass('has-success');
					$('#activityconc').val(result.activityconc);
					loadActivityData(false);
				});
			});
		});


		$("#activity").change(function() {
			var activity = $("#activity").val();
			if (activity == -1) {
				if ($("#expirationtime").val() != '') {
					focusField = 'expirationtime';
					$('#titleModal').text("<?php echo $this->translate("Incorrect expiration date"); ?>");
					$('#messageModal').text("<?php echo $this->translate("The expiration date of the drug is incorrect."); ?>");
					$('#alertModal').text("<?php echo $this->translate("Set a correct date : greater than the calibration date"); ?>");
					

					$('#datetimepicker-peremption').val('');
					$("#alertdata").modal('show');
				}
			}
			else if (activity == -2) {
				if ($("#activityconc").val() != '') {
					focusField = 'activityconc';
					$('#titleModal').text("<?php echo $this->translate("Wrong volumic activity"); ?>");
					$('#messageModal').text("<?php echo $this->translate("The volumic activity of the drug is incorrect."); ?>");
					$('#alertModal').text("<?php echo $this->translate("Set a correct value : positive"); ?>");
					
					
					$("#alertdata").modal('show');
				}
			}
			else if (activity == -3) {
				if ($("#activitycalib").val() != '') {
					focusField = 'activitycalib';
					$('#titleModal').text("<?php echo $this->translate("Wrong calibration activity"); ?>");
					$('#messageModal').text("<?php echo $this->translate("The calibration activity is incorrect."); ?>");
					$('#alertModal').text("<?php echo $this->translate("Set a correct value : positive"); ?>");
					
					
					$("#alertdata").modal('show');
				}
			}
			else if (activity == -4) {
				if ($("#vialvol").val() != '') {
					focusField = 'vialvol';
					$('#titleModal').text("<?php echo $this->translate("Incorrect vial volume"); ?>");
					$('#messageModal').text("<?php echo $this->translate("The volume of the vial is incorrect."); ?>");
					$('#alertModal').text("<?php echo $this->translate("Set a correct value : between $vialvol_min and $vialvol_max ml"); ?>");
					
					
					$("#alertdata").modal('show');
					//TODO Rajouter l'appel au setFocusOnField lorsque la popup se ferme
				}
			}
		});
	});
</script>
<div class="modal fade" id="alertdata" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title"><span class="glyphicon glyphicon-warning-sign"></span> <span id="titleModal">Title Modal</span></h4>
			</div>
			<div class="modal-body">
				<p id="messageModal">Message Modal</p>
				<div class="alert alert-info">
					<i class="glyphicon glyphicon-info-sign"></i>
					<span id="alertModal">alertModal</span>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" onclick="setFocusOnField();"><?php echo $this->translate('OK');?></button>
			</div>
		</div>
	</div>
</div>