<ol class="breadcrumb">
	<li><a href="<?php echo $this->url('operator')?>"><span class=" glyphicon glyphicon-home"></span> <?php echo $this->translate('Operator dashboard')?></a></li>
	<li class="active"><?php echo $this->translate('Registrer the source kit')?></li>
</ol>
<div class="row">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<span class="glyphicon glyphicon-barcode"></span> <?php echo $this->translate('Registrer the source kit')?>
		</div>
		<div class="panel-body">
			<form id="scankitsource" action="<?php echo $this->url('setup', array('action'=>'scankitsource'));?>" method="POST">
				<div class="row">
					<div class="col-md-12">
						<p><?php echo $this->translate('Please scan the barcode of the source kit or write it manually');?></p>
					</div>
				</div>
				<div class="row">
					<div class="col-md-10 col-md-offset-1 alert alert-danger hide" id="errormsg">
						<span class="glyphicon glyphicon-exclamation-sign"></span> <strong><?php echo $this->translate('Error')?> : </strong>
						<span id="errormsg-content"></span>
					</div>
				</div>
				<div class="row">
					<div class="col-md-8 col-md-offset-2">
						<div id="inputgroup1" class="form-group has-error">
							<label for="sourcekit-sn">Kit n°</label>
							<div class="input-group">
								<span class="input-group-addon"><span id="input-statut" class="glyphicon glyphicon-ban-circle"></span></span>
								<input type="text" class="form-control barcode" id="sourcekit-sn" name="sourcekit-sn" placeholder="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" maxlength="35" autocomplete="off"/>
								<span class="input-group-btn">
									<button class="btn btn-default" type="button" onclick="resetInputVal()"><span class="glyphicon glyphicon-remove"></span></button>
								</span>
							</div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-2 col-md-offset-4">
						<button id="btn-next" type="button" class="btn btn-success btn-block" onclick="checkInputVal(true);" disabled>Suivant</button>
					</div>
					<div class="col-md-2">
						<button id="btn-exit" type="button" class="btn btn-danger btn-block" onclick="location.href='<?php echo $this->url('operator')?>'">Annuler</button>
					</div>
				</div>
			</form>
			<script type="text/javascript">
				$(function() {
					$('#sourcekit-sn').focus();
					<?php if ($this->layout()->virtualkeyboardEnable === false) { ?>
					$('#sourcekit-sn').on('change', function(e) { checkInputVal(false); });
					<?php } ?>
				});


				function checkInputVal(submitForm)
				{
					$('#errormsg').removeClass('hide');
					$('#errormsg').addClass('hide');
					$('#inputgroup1').removeClass("has-success has-warning has-error").addClass('has-warning');
					$('#input-statut').removeClass("glyphicon-ban-circle glyphicon-time glyphicon-time glyphicon-ok-circle").addClass('glyphicon-time');
					var code = $('#sourcekit-sn').val();
					if(code.length == 35)
					{
						var sn = $('#sourcekit-sn').val();
						var postdata = {
							"sourcekit-sn": sn,
						};
						$.ajax({
							type: "POST",
							url: "<?php echo $this->url('setup', array('action'=>'achecksourcekit'));?>",
								dataType: "json",
								data: postdata,
						}).done(function(result) {
							if(result.success == 1)
							{
								$('#inputgroup1').removeClass("has-success has-warning has-error").addClass('has-success');
								$('#input-statut').removeClass("glyphicon-ban-circle glyphicon-time glyphicon-ok-circle").addClass('glyphicon-ok-circle');
								$('#btn-next').removeAttr('disabled');
								if (submitForm === true) {
									$('#scankitsource').submit();
								}
								return false;
							}
							else if(result.success == 0)
							{
								$('#inputgroup1').removeClass("has-success has-warning has-error").addClass('has-error');
								$('#input-statut').removeClass("glyphicon-ban-circle glyphicon-time glyphicon-ok-circle").addClass('glyphicon-ban-circle');
								$('#errormsg-content').html(result.msg);
								$('#errormsg').removeClass('hide');
								return false;
							}
							else
							{
 								$(location).attr('href', result.redirect);
							}
						});
					}
					else
					{
						$('#input-statut').removeClass("glyphicon-ban-circle glyphicon-time glyphicon-ok-circle").addClass('glyphicon-ban-circle');
						$('#inputgroup1').removeClass("has-success has-warning has-error").addClass('has-error');
						$('#btn-next').attr('disabled', 'disabled');
						$('#errormsg-content').html("<?php echo $this->translate("Invalid barcode")?>");
						$('#errormsg').removeClass('hide');
						return false;
					}
				}
				
				function resetInputVal()
				{
					$('#sourcekit-sn').val('');
					$('#sourcekit-sn').popover('hide');
					$('#sourcekit-sn').focus();
					checkInputVal(false);
				}
			</script>
		</div>
	</div>
</div>
