<ol class="breadcrumb">
	<li><a href="<?php echo $this->url('operator')?>"><span class=" glyphicon glyphicon-home"></span> <?php echo $this->translate('Operator dashboard')?></a></li>
	<li class="active"><?php echo $this->translate('Patient selection')?></li>
</ol>
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<span class="glyphicon glyphicon-list"></span> <?php echo $this->translate('Patient selection')?>
			</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-md-10">
						<form id="submitedpatient-form" action="<?php echo $this->url('setup', array('action'=>'confirmpatient'))?>" method="post">
							<input type="hidden" id="patient-id" name="patient-id" value=""  />
						</form>
						<div>
							<ul class="nav nav-tabs" role="tablist">
								<li role="presentation" class="active">
									<a href="#compatibles" aria-controls="compatibles" role="tab" data-toggle="tab"><?php echo $this->translate('Compatible patients list'); ?></a>
								</li>
								<li role="presentation">
									<a href="#others" aria-controls="others" role="tab" data-toggle="tab"><?php echo $this->translate('Other patients list'); ?></a>
								</li>
							</ul>
						
							<div class="tab-content">
								<div role="tabpanel" class="tab-pane active">
									<table class="table table-condensed <?php if (count($patients_compatible) > 0) { echo 'table-hover'; } ?>" style="margin-bottom: 0;">
										<thead>
											<tr>
												<th><?php echo $this->translate('Lastname'); ?></th>
												<th><?php echo $this->translate('Firstname'); ?></th>
											</tr>
										</thead>
									</table>
									<div style="height: 190px; overflow: hidden;"  id="compatibles">
										<table class="table table-condensed <?php if (count($patients_compatible) > 0) { echo 'table-hover'; } ?>">
											<tbody>
											<?php if (count($patients_compatible) > 0) { ?>
											<?php foreach($patients_compatible as $patient) { ?>
												<tr id="patient-<?php echo $patient->patientId;?>" style="cursor:pointer" onclick="loadPatient(<?php echo $patient->patientId?>);">
													<td><?php echo $patient->patientLastname;?></td>
													<td><?php echo $patient->patientFirstname;?></td>
													<td></td>
												</tr>
											<?php } ?>
												<tr><td colspan="3" style="text-align: center;"><i><?php echo $this->translate('End of patients list.'); ?></i></td></tr>
												<tr><td colspan="3"><hr /></td></tr>
											<?php } else if ((count($patients_compatible) + count($patients_nocompatible)) == 0) { ?>
												<tr>
													<td colspan="3">
														<div class="alert alert-warning" role="alert">
														<?php echo $this->translate('No patient loaded. Try to load a file or to create a new one.')?>
														<a class="btn btn-default" href="<?php echo $this->url("setup", array("action" => "loadpatient")); ?>" role="button"><i class="glyphicon glyphicon-import"></i> <?php echo $this->translate('Import patients')?></a>
														</div>
													</td>
												</tr>
											<?php } else if (count($patients_compatible) == 0) { ?>
												<tr>
													<td colspan="3">
														<div class="alert alert-warning" role="alert">
														<?php echo $this->translate('No compatible patient found. Try to unload the drug or create a new patient.'); ?>
														</div>
													</td>
												</tr>
											<?php } ?>
											</tbody>
										</table>
									</div>
								</div>
						    	<div role="tabpanel" class="tab-pane" id="others">
									<?php if (count($patients_nocompatible) > 0) { ?>
									<table class="table table-condensed">
										<tbody>
										<?php foreach($patients_nocompatible as $patient) { ?>
											<tr id="patient-<?php echo $patient->patientId;?>">
												<td><?php echo $patient->patientLastname;?></td>
												<td><?php echo $patient->patientFirstname;?></td>
												<td></td>
											</tr>
										<?php } ?>
										</tbody>
									</table>
									<?php } ?>
								</div>
						  	</div>
						</div>
					</div>
					<div class="col-md-2">
						<div style="position: relative; height: 190px; margin-left: auto; margin-right: auto; width: 50px; margin-top: 70px;">
							<div style="position: absolute; top: 0;">
								<button type="button" class="btn btn-default btn-lg btn-block" style="width: 50px; height: 50px;" onclick="scrollToTop();">
									<i class="glyphicon glyphicon-chevron-up"></i>
								</button>
							</div>
							<div style="position: absolute; bottom: 0;">
								<button type="button" class="btn btn-default btn-lg btn-block" style="width: 50px; height: 50px;" onclick="scrollToDown();">
									<i class="glyphicon glyphicon-chevron-down"></i>
								</button>
							</div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-3 <?php if (count($patients_compatible) > 0) { echo 'col-md-offset-3'; } ?>">
						<button id="btn-next" type="button" class="btn btn-success btn-block" disabled><?php echo $this->translate('Next')?></button>
					</div>
					<div class="col-md-3">
						<button id="btn-exit" type="button" class="btn btn-primary btn-block" onclick="location.href='<?php echo $this->url('setup', array('action'=>'createpatient'))?>'"><?php echo $this->translate('New patient'); ?></button>
					</div>
					<?php if (count($patients_compatible) == 0) { ?>
					<div class="col-md-3">
						<button id="btn-exit" type="button" class="btn btn-primary btn-block" onclick="location.href='<?php echo $this->url('inject', array('action'=>'endinject')); ?>'"><?php echo $this->translate('End of injections'); ?></button>
					</div>
					<?php } ?>
					<div class="col-md-3">
						<button id="btn-exit" type="button" class="btn btn-danger btn-block" onclick="location.href='<?php echo $this->url('operator'); ?>'"><?php echo $this->translate('Cancel'); ?></button>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	var patientIds = [];
<?php $n = 0; ?>
<?php if (count($patients_compatible) > 0) { ?>
<?php 	foreach($patients_compatible as $patient) { ?>
<?php 		echo '	patientIds[' . $n .'] = ' . $patient->patientId . ";\n"; ?>
<?php 		$n++; ?>
<?php 	} ?>
<?php } ?>
	var scrollPosition = 0;
	var scrollTop = null;
	var scrollMax = <?php echo $n - 1; ?>;

	function	scrollToTop() {
		scrollPosition--;
		if (scrollPosition < 0) {
			scrollPosition = 0;
		}

		var target = $('#patient-' + patientIds[scrollPosition]);

		$('#compatibles').animate({
            scrollTop: target.outerHeight() * scrollPosition
        }, 400);
	}

	function	scrollToDown() {
		if (scrollTop !== null && scrollTop == $('#compatibles').scrollTop()) {
			return false;
		}
		
		scrollPosition++;
		if (scrollPosition > scrollMax) {
			scrollPosition = scrollMax;
		}

 		var target = $('#patient-' + patientIds[scrollPosition]);

		$('#compatibles').animate({
            scrollTop: target.outerHeight() * scrollPosition
        }, 400);
        
		scrollTop = $('#compatibles').scrollTop();
	}

	function	loadPatient(patientid)
	{
		$('tr.info').removeClass('info');
		$('#patient-'+patientid).addClass('info');
		$('#patient-id').val(patientid);
		$.ajax({
			url: "<?php echo $this->url('bufferspace', array('action'=>'aloadpatient'));?>",
			type: "POST",
			data: { 'patientid': patientid },
			dataType: "json"
		}).done(function(result) {

			$('#name').val(result.lastname + ', ' + result.firstname);
			$('#gender').val(result.gender);
			$('#birthdate').val(result.birthdate);
			$('#weight').val(result.weight);
			$('#btn-next').removeAttr('disabled');
		});
	}
	$(function(){
		$('#btn-next').click(function(){
			$('#submitedpatient-form').submit();
		});
	});
</script>