<ol class="breadcrumb">
	<li><a href="<?php echo $this->url('manager')?>"><span class=" glyphicon glyphicon-home"></span> <?php echo $this->translate('Supervior dashboard');?></a></li>
	<li><a href="<?php echo $this->url('radionuclide')?>"><?php echo $this->translate('Radionuclide management');?></a></li>
	<li class="active"><?php echo $this->translate('Radionuclide profile');?></li>
</ol>
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<span class="glyphicon glyphicon-certificate"></span> <?php echo $this->translate('Radionuclide profile');?>
			</div>
			<div class="panel-body">
				<form class="form-horizontal" role="form" method="post" action="<?php echo $this->url('radionuclide', array('action'=>'edit'))?>">
					<div class="form-group">
						<label for="lastname" class="control-label col-md-2"><?php echo $this->translate("Name")?></label>
						<div class="col-md-6">
							<input type="text" class="form-control col-md-6" id="name" name="name" value="<?php echo $this->radionuclide->name;?>" required />
						</div>
					</div>
					<div class="form-group">
						<label for="firstname" class="control-label col-md-2"><?php echo $this->translate("Period")?></label>
						<div class="col-md-6">
							<div class="input-group">
								<input type="text" class="form-control" id="period" name="period" value="<?php echo $this->radionuclide->period;?>" required />
								<span class="input-group-addon">min</span>
							</div>
						</div>
					</div>
					<div class="form-group">
						<label for="login" class="control-label col-md-2"><?php echo $this->translate("Coefficient")?></label>
						<div class="col-md-6">
							<div class="input-group">
								<input type="text" class="form-control" id="coefficient" name="coefficient" value="<?php echo $this->radionuclide->coefficient;?>" required />
								<span class="input-group-addon">%</span>
							</div>
						</div>
					</div>
					<input type="hidden" id="id" name="id" value="<?php echo $this->radionuclide->id;?>" />
					<button type="submit" class="btn btn-primary"><?php echo $this->translate("Submit")?></button>
					<button type="button" class="btn btn-danger" onClick="window.location='<?php echo $this->url('radionuclide')?>'"><?php echo $this->translate("Abort")?></button>
				</form>
			</div>
		</div>
	</div>
</div>