<?php //TODO Virer les actions CRUD Radionculeides ?>
<ol class="breadcrumb">
	<li><a href="<?php echo $this->url('manager')?>"><span class=" glyphicon glyphicon-home"></span> <?php echo $this->translate('Supervior dashboard');?></a></li>
	<li class="active"><?php echo $this->translate('Radionuclide management')?></li>
</ol>
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<span class="glyphicon glyphicon-certificate"></span> <?php echo $this->translate('Radionuclide list');?>
			</div>
			<div class="panel-body">
			<?php if (count($radionuclides) === 0) { ?>
				<div class="alert alert-danger" role="alert">
					<strong><i class="glyphicon glyphicon-exclamation-sign"></i> <?php echo $this->translate('Warning');?> <i class="glyphicon glyphicon-exclamation-sign"></i></strong> 
					<p><?php echo sprintf('%s <a href="' . $this->url("restart") . '" class="alert-link">%s</a> %s', $this->translate('No radionuclides found in database. Please '), $this->translate('restart the application'), $this->translate(' or (if it fails) reboot completely the system.')); ?></p>
				</div>
				<?php } else { ?>
				<table class="table table-striped table-hover">
					<thead>
						<tr>
							<th><?php echo $this->translate('Name');?></th>
							<th><?php echo $this->translate('Period');?></th>
							<th><?php echo $this->translate('Coefficient');?></th>
						</tr>
					</thead>
					<tbody>
						<?php foreach($radionuclides as $radionuclide) { ?>
						<tr>
							<td><?php echo $this->escapeHtml($radionuclide->name);?></td>
							<td><?php echo $this->escapeHtml($radionuclide->period);?> min</td>
							<td><?php echo $this->escapeHtml($radionuclide->coefficient);?> %</td>
						</tr>
						<?php } ?>
					</tbody>
				</table>
				<?php } ?>
			</div>
		</div>
	</div>
</div>