<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Auth\Module'                        => __DIR__ . '/Module.php',
    'Auth\Controller\LoginController' => __DIR__ . '/src/Auth/Controller/LoginController.php',
    'AuthTest\Framework\TestCase'        => __DIR__ . '/tests/Auth/Framework/TestCase.php',
    'AuthTest\SampleTest'                => __DIR__ . '/tests/Auth/SampleTest.php',
);
