<ol class="breadcrumb">
	<li class="active"><span class=" glyphicon glyphicon-home"></span> <?php echo $this->translate('Supervior dashboard');?></li>
</ol>
<div class="well">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<div class="list-group">
				<a href="<?php echo $this->url('user')?>" class="list-group-item">
					<span class="glyphicon glyphicon-user"></span>
					<?php echo $this->translate('Users management');?>
				</a>
				<a href="<?php echo $this->url('radionuclide')?>" class="list-group-item">
					<span class="glyphicon glyphicon-certificate"></span>
					<?php echo $this->translate('Radionuclides management');?>
				</a>
				<a href="<?php echo $this->url('drug')?>" class="list-group-item">
					<span class="glyphicon glyphicon-tint"></span>
					<?php echo $this->translate('Drugs management');?>
				</a>
				<a href="<?php echo $this->url('examination')?>" class="list-group-item">
					<span class="glyphicon glyphicon-edit"></span>
					<?php echo $this->translate('Examinations management');?>
				</a>
				<a href="<?php echo $this->url('activimeter')?>" class="list-group-item">
					<span class="glyphicon glyphicon-dashboard"></span>
					<?php echo $this->translate('Activimeter');?>
				</a>
				<a href="<?php echo $this->url('system')?>" class="list-group-item">
					<span class="glyphicon glyphicon-search"></span>
					<?php echo $this->translate('System overview');?>
				</a>
<!-- suppression de la gestion manuelle de l'injecteur -->
<!--				<a href="<?php echo $this->url('injector')?>" class="list-group-item">
					<span class="glyphicon glyphicon-list-alt"></span>
					<?php echo $this->translate('Injector management');?>
				</a>-->
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="modalAutoLogout" tabindex="-1" role="dialog" aria-labelledby="autologoutModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title" id="autologoutModalLabel"><i class="glyphicon glyphicon-time"></i> <?php echo $this->translate('Locking protection system'); ?></h4>
			</div>
			<div class="modal-body">
				<div class="alert alert-warning" role="alert">
					<p><?php echo sprintf($this->translate('No activity has been detect on this screen since %s seconds.'), $supervisorTimeout); ?></p>
					<p><?php echo $this->translate('You have been deconnected.'); ?></p>
					<br />
					<p><?php echo $this->translate('Please proceed to Sign-In button to be reconnected.'); ?></p>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary" onclick="location.href='<?php echo $this->url('log'); ?>'"><i class="glyphicon glyphicon-home"></i> <?php echo $this->translate('Sign In'); ?></button>
			</div>
		</div>
	</div>
</div>

<?php
$this->inlineScript()->appendScript('
	$(function() {
		setTimeout(function(){
			$.ajax({
				url: "'. $this->url('log', array('action'=>'autologout')) . '",
			}).done(function(result){
				$("#modalAutoLogout").modal({
					backdrop: "static",
					keyboard: false,
					show: true,
				});
			});
		}, ' . $supervisorTimeout . '000);
	});
');