<?php //TODO Trad high prio ?>
<ol class="breadcrumb">
	<li><a href="<?php echo $this->url('manager')?>"><span class=" glyphicon glyphicon-home"></span> <?php echo $this->translate('Supervior dashboard');?></a></li>
	<li class="active"><?php echo $this->translate('Injector management');?></li>
</ol>
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<span class="glyphicon glyphicon-list-alt"></span> <?php echo $this->translate('Injector management');?>
			</div>
			<div class="panel-body">
				<div id="carousel-setup-process" class="carousel slide" data-ride="carousel" data-interval="" data-wrap="false">
					<ol class="carousel-indicators">
						<li data-target="#carousel-setup-process" data-slide-to="0" class="active"></li>
						<li data-target="#carousel-setup-process" data-slide-to="1"></li>
						<li data-target="#carousel-setup-process" data-slide-to="2"></li>
						<li data-target="#carousel-setup-process" data-slide-to="3"></li>
						<li data-target="#carousel-setup-process" data-slide-to="4"></li>
						<li data-target="#carousel-setup-process" data-slide-to="5"></li>
						<li data-target="#carousel-setup-process" data-slide-to="6"></li>
					</ol>
					<div class="carousel-inner">
						<div class="item active">
							<img src="/img/slide_carousel.jpg" alt=""/>
							<div class="carousel-caption">
								<h3>Déverrouillage de la Porte</h3>
								<p>Blabla</p>
							</div>
						</div>
						<div class="item">
							<img src="/img/slide_carousel.jpg" alt=""/>
							<div class="carousel-caption">
								<h3>Déverrouillage du Tiroir</h3>
								<p>Blabla</p>
							</div>
						</div>
						<div class="item">
							<img src="/img/slide_carousel.jpg" alt=""/>
							<div class="carousel-caption">
								<h3>Montée du Support Aiguille</h3>
								<p>Blabla</p>
							</div>
						</div>
						<div class="item">
							<img src="/img/slide_carousel.jpg" alt=""/>
							<div class="carousel-caption">
								<h3>Ouverture du Tiroir</h3>
								<p>Blabla</p>
							</div>
						</div>
						<div class="item">
							<img src="/img/slide_carousel.jpg" alt=""/>
							<div class="carousel-caption">
								<h3>Retirer la source en remettant le couvercle fournisseur</h3>
								<p>Blabla</p>
							</div>
						</div>
						<div class="item">
							<img src="/img/slide_carousel.jpg" alt=""/>
							<div class="carousel-caption">
								<h3>Fermeture du Tiroir</h3>
								<p>Blabla</p>
							</div>
						</div>
						<div class="item">
							<img src="/img/slide_carousel.jpg" alt=""/>
							<div class="carousel-caption">
								<h3>Fermeture de la Porte</h3>
								<p>Blabla</p>
							</div>
						</div>
					</div>
					<a class="right carousel-control" href="#carousel-setup-process" data-slide="next">
						<span class="glyphicon glyphicon-chevron-right"></span>
					</a>
				</div>
				<div class="row" style="margin-top:10px;display:none;" id="btn-next">
					<div class="col-md-4 col-md-offset-4">
						<button class="btn btn-primary btn-block btn-lg" onClick="gotonext()"><?php echo $this->translate('Continue');?></button>
					</div>
				</div>
				<script type="text/javascript">
					$('#carousel-setup-process').on('slid.bs.carousel', function() {
						if($('.carousel-inner .item:last').hasClass('active')) {
							$('#btn-next').show();
						}
					});

					function	gotonext()
					{
						window.location.href = "<?php echo $this->url('setup', array('action'=>'loadkitsource','confirm'=>1))?>";
					}
				</script>
			</div>
		</div>
	</div>
</div>