<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Manager\Module'                        => __DIR__ . '/Module.php',
    'Manager\Controller\ManagerController' => __DIR__ . '/src/Manager/Controller/ManagerController.php',
    'ManagerTest\Framework\TestCase'        => __DIR__ . '/tests/Manager/Framework/TestCase.php',
    'ManagerTest\SampleTest'                => __DIR__ . '/tests/Manager/SampleTest.php',
);
