<ol class="breadcrumb">
	<li><a href="<?php echo $this->url('operator')?>"><span class=" glyphicon glyphicon-home"></span> <?php echo $this->translate('Operator dashboard');?></a></li>
	<li class="active"><?php echo $this->translate('Activimeter')?></li>
</ol>
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<span class="glyphicon glyphicon-dashboard"></span> <?php echo $this->translate('Activimeter');?>
			</div>
			<div class="panel-body">
				<div class="alert alert-info" role="alert">
					<h3><?php echo $this->translate("Activimeter launch"); ?></h3>
					<p>
						<?php echo $this->translate("A new window should be opened in few seconds."); ?>
						<?php echo $this->translate("Check on every desktop if ou don't see it."); ?>
					</p>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
$.ajax({url: "http://sami.local:4242/vnc.php" });
</script>
