<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Logger\Module'                        => __DIR__ . '/Module.php',
    'Logger\Controller\IndexController' => __DIR__ . '/src/Logger/Controller/IndexController.php',
    'LoggerTest\Framework\TestCase'        => __DIR__ . '/tests/Logger/Framework/TestCase.php',
    'LoggerTest\SampleTest'                => __DIR__ . '/tests/Logger/SampleTest.php',
);
