<ol class="breadcrumb">
	<li><a href="<?php echo $this->url('manager')?>"><span class=" glyphicon glyphicon-home"></span> <?php echo $this->translate('Supervior dashboard');?></a></li>
	<li><a href="<?php echo $this->url('drug')?>"><?php echo $this->translate('Drug management');?></a></li>
	<li class="active"><?php echo $this->translate('Drug profile');?></li>
</ol>
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<span class="glyphicon glyphicon-tint"></span> <?php echo $this->translate('Drug profile');?>
			</div>
			<div class="panel-body">
				<form class="form-horizontal" id="form-drug" role="form" method="post" action="<?php echo $this->url('drug', array('action'=>'add'))?>" onsubmit="return checkForm();">
					<div id="errorMessage" class="alert alert-danger hide" role="alert">
						<i class=""><?php echo $this->translate('This drug is already existing in database. Please choose another name.'); ?></i>
					</div>
					<div class="form-group">
						<label for="name" class="control-label col-md-2"><?php echo $this->translate("Name")?></label>
						<div class="col-md-6">
							<input type="text" class="form-control col-md-6" id="name" name="name" value="" autocomplete="off" maxlength="100" onchange="checkUniqueName();" required/>
						</div>
					</div>
					<div class="form-group">
						<label for="radionuclideid" class="control-label col-md-2"><?php echo $this->translate("Radionuclide")?></label>
						<div class="col-md-6">
							<select class="form-control" id="radionuclideid" name="radionuclideid" required>
								<option value=""><?php echo $this->translate('Choose a radionuclide'); ?></option>
							<?php foreach ($this->radionuclides as $radionuclide) { ?>
								<option value="<?php echo $radionuclide->id;?>"><?php echo $radionuclide->name;?></option>
							<?php } ?>
							</select>
						</div>
					</div>
					<div class="form-group">
						<label for="dci" class="control-label col-md-2"><?php echo $this->translate("D.C.I.")?></label>
						<div class="col-md-6">
							<input type="text" class="form-control" id="dci" name="dci" value="" maxlength="100" required autocomplete="off" />
						</div>
					</div>
					<div class="form-group">
						<label for="dilutable" class="control-label col-md-2"><?php echo $this->translate("Dilutable")?></label>
						<div class="col-md-6">
							<div class="btn-group" data-toggle="buttons">
								<label class="btn btn-default active">
									<input type="radio" name="dilutable" id="no" autocomplete="off" value="0" checked="checked" /> <?php echo $this->translate('No'); ?>
								</label>
								<label class="btn btn-default">
									<input type="radio" name="dilutable" id="yes" autocomplete="off" value="1" /> <?php echo $this->translate('Yes'); ?>
								</label>
							</div>
						</div>
					</div>
					<input type="submit" class="btn btn-primary" value="<?php echo $this->translate("Submit")?>" />
				</form>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	var canSubmit = false;

	function	checkForm()
	{
		return canSubmit;
	}

	function checkUniqueName()
	{
		canSubmit = false;
		$.ajax({
			type: "POST",
			url: "<?php echo $this->url('drug', array('action' => 'acheckunique'));?>",
			dataType:"json",
			data : {"name" : $('#name').val(), "currentDrugId" : 0}
		}).done(function(result) {
			if (result.error === false) {
				$("#errorMessage").removeClass("hide");
				$("#errorMessage").addClass("hide");
				canSubmit = true;
			}
			else {
				$("#errorMessage").removeClass("hide");
			}
		});
	}
</script>