<ol class="breadcrumb">
	<li><a href="<?php echo $this->url('manager')?>"><span class=" glyphicon glyphicon-home"></span> <?php echo $this->translate('Supervior dashboard');?></a></li>
	<li class="active"><?php echo $this->translate('Drug management')?></li>
</ol>
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<span class="glyphicon glyphicon-tint"></span> <?php echo $this->translate('Drug list');?>
			</div>
			<div class="panel-body">
			<?php if (count($drugs) == 0) {  ?>
			<div class="alert alert-warning" role="alert">
				<strong><i class="glyphicon glyphicon-exclamation-sign"></i> <?php echo $this->translate('Warning');?> <i class="glyphicon glyphicon-exclamation-sign"></i></strong> 
				<p><?php echo sprintf('%s <a href="' . $this->url("drug", array("action" => "add")) . '" class="alert-link">%s</a> %s', $this->translate('No drugs found in database. Please '), $this->translate('create'), $this->translate(' at least one drug.')); ?></p>
			</div>
			<p class="text-center"><a class="btn btn-primary" href="<?php echo $this->url('drug', array('action'=>'add'));?>"><span class="glyphicon glyphicon-plus-sign"></span> <?php echo $this->translate('Add a drug')?></a></p>
			<?php } else { ?>
				<table class="table table-striped table-hover">
					<thead>
						<tr>
							<th><?php echo $this->translate('Name');?></th>
							<th><?php echo $this->translate('Radionuclide');?></th>
							<th><?php echo $this->translate('D.C.I.');?></th>
							<th><?php echo $this->translate('Action');?></th>
						</tr>
					</thead>
					<tbody>
						<?php foreach($drugs as $drug) { ?>
						<tr>
							<td><?php echo $this->escapeHtml($drug->drug_name);?></td>
							<td><?php echo $this->escapeHtml($drug->radionuclide_name);?></td>
							<td><?php echo $this->escapeHtml($drug->dci);?></td>
							<td class="col-md-3">
								<a href="<?php echo $this->url('drug', array('action'=>'edit', 'id'=>$drug->id))?>" class="btn btn-primary"><span class="glyphicon glyphicon-pencil"></span> <?php echo $this->translate('Edit');?></a>
							<?php if ($drug->nbExams == 0) { ?>
								<a href="<?php echo $this->url('drug', array('action'=>'delete', 'id'=>$drug->id))?>" class="btn btn-danger" 
									role="delete" data-delete-title="<?php echo $this->translate('Delete drug confirmation title');?>" data-delete-content="<?php echo $this->translate('Delete drug confirmation content');?>">
									<span class="glyphicon glyphicon-trash"></span> <?php echo $this->translate('Delete');?>
								</a>
							<?php } else { ?>
								<a href="javascript: void(0);" class="btn btn-danger disabled" style="pointer-events: inherit !important" title="<?php echo sprintf($this->translate('%s examination(s) use this drug.'), $drug->nbExams);?>">
									<span class="glyphicon glyphicon-trash"></span> <?php echo $this->translate('Delete');?>
								</a>
							<?php } ?>
							</td>
						</tr>
						<?php } ?>
					</tbody>
					<tfoot>
						<tr>
							<th colspan="5" class="text-center"><a class="btn btn-primary" href="<?php echo $this->url('drug', array('action'=>'add'));?>"><span class="glyphicon glyphicon-plus-sign"></span> <?php echo $this->translate('Add a drug')?></a></th>
						</tr>
					</tfoot>
				</table>
			<?php } ?>
			</div>
		</div>
	</div>
</div>