<ol class="breadcrumb">
	<li><a href="<?php echo $this->url('manager')?>"><span class=" glyphicon glyphicon-home"></span> <?php echo $this->translate('Supervior dashboard');?></a></li>
	<li><a href="<?php echo $this->url('examination')?>"><?php echo $this->translate('Examination management');?></a></li>
	<li class="active"><?php echo $this->translate('Examination profile');?></li>
</ol>
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<span class="glyphicon glyphicon-edit"></span> <?php echo $this->translate('Examination profile');?>
			</div>
			<div class="panel-body">
				<form class="form-horizontal" role="form" method="post" action="<?php echo $this->url('examination', array('action'=>'add'))?>" onsubmit="return checkForm()">
					<div class="form-group">
						<label for="name" class="control-label col-md-2"><?php echo $this->translate("Name")?></label>
						<div class="col-md-6">
							<input type="text" class="form-control col-md-6" id="name" name="name" value="" autocomplete="off" maxlength="100" required />
						</div>
					</div>
					<div class="form-group">
						<label for="dci" class="control-label col-md-2"><?php echo $this->translate("DCI")?></label>
						<div class="col-md-6">
							<select class="form-control" id="dci" name="dci" required>
								<option value=""><?php echo $this->translate("Select a DCI")?></option>
							<?php foreach ($this->dcis as $dci) { ?>
								<option value="<?php echo $dci->dci;?>"><?php echo $dci->dci;?></option>
							<?php } ?>
							</select>
						</div>
					</div>
					<div class="form-group">
						<label for="rate" class="control-label col-md-2"><?php echo $this->translate("Rate")?></label>
						<div class="col-md-6">
							<div class="input-group">
								<input type="number" min="1" step="1" class="form-control" id="rate" name="rate" value="" autocomplete="off" required />
								<span class="input-group-addon"><?php echo $unit?>/Kg</span>
							</div>
						</div>
					</div>
					<div class="form-group">
						<label for="min" class="control-label col-md-2"><?php echo $this->translate("Min.")?></label>
						<div class="col-md-6">
							<div class="input-group">
								<input type="number" min="1" step="1" class="form-control" id="min" name="min" value="" autocomplete="off" required />
								<span class="input-group-addon"><?php echo $unit?></span>
							</div>
						</div>
					</div>
					<div class="form-group">
						<label for="max" class="control-label col-md-2"><?php echo $this->translate("Max.")?></label>
						<div class="col-md-6">
							<div class="input-group">
								<input type="number" min="1" step="1" class="form-control" id="max" name="max" value="" autocomplete="off" required />
								<span class="input-group-addon"><?php echo $unit?></span>
							</div>
						</div>
					</div>
					<button type="submit" class="btn btn-primary"><?php echo $this->translate("Submit")?></button>
					<button type="button" class="btn btn-danger" onClick="window.location='<?php echo $this->url('examination')?>'"><?php echo $this->translate("Abort")?></button>
				</form>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	function	checkForm()
	{
		if(true)
		{
			return true;
		}
		else
		{
			return false;
		}
	}
</script>