<ol class="breadcrumb">
	<li><a href="<?php echo $this->url('manager')?>"><span class=" glyphicon glyphicon-home"></span> <?php echo $this->translate('Supervior dashboard');?></a></li>
	<li class="active"><?php echo $this->translate('Examination management')?></li>
</ol>
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<span class="glyphicon glyphicon-edit"></span> <?php echo $this->translate('Examination list');?>
			</div>
			<div class="panel-body">
			<?php if (count($examinations) === 0) { ?>
				<div class="alert alert-warning" role="alert">
					<strong><i class="glyphicon glyphicon-exclamation-sign"></i> <?php echo $this->translate('Warning');?> <i class="glyphicon glyphicon-exclamation-sign"></i></strong> 
					<p><?php echo sprintf('%s <a href="' . $this->url("examination", array("action" => "add")) . '" class="alert-link">%s</a> %s', $this->translate('No exam found in database. Please '), $this->translate('create'), $this->translate(' at least one exam.')); ?></p>
				</div>
				<p class="text-center"><a class="btn btn-primary" href="<?php echo $this->url('examination', array('action'=>'add'));?>"><span class="glyphicon glyphicon-plus-sign"></span> <?php echo $this->translate('Add an examination')?></a></p>
			<?php } else { ?>
				<table class="table table-striped table-hover">
					<thead>
						<tr>
							<th><?php echo $this->translate('Name');?></th>
							<th><?php echo $this->translate('DCI');?></th>
							<th><?php echo $this->translate('Rate');?></th>
							<th><?php echo $this->translate('Min');?></th>
							<th><?php echo $this->translate('Max');?></th>
							<th><?php echo $this->translate('Action');?></th>
						</tr>
					</thead>
					<tbody>
						<?php foreach($examinations as $examination) { ?>
						<tr>
							<td><?php echo $this->escapeHtml($examination->examination_name);?></td>
							<td><?php echo $this->escapeHtml($examination->dci);?></td>
							<td><?php echo $this->escapeHtml($examination->rate);?> <?php echo $unit?>/Kg</td>
							<td><?php echo $this->escapeHtml($examination->min);?> <?php echo $unit?></td>
							<td><?php echo $this->escapeHtml($examination->max);?> <?php echo $unit?></td>
							<td class="col-md-4">
								<a href="<?php echo $this->url('examination', array('action'=>'edit', 'id'=>$examination->id))?>" class="btn btn-primary"><span class="glyphicon glyphicon-pencil"></span> <?php echo $this->translate('Edit');?></a>
								<a href="<?php echo $this->url('examination', array('action'=>'delete', 'id'=>$examination->id))?>" class="btn btn-danger"
									role="delete" data-delete-title="<?php echo $this->translate('Delete examination confirmation title');?>" data-delete-content="<?php echo $this->translate('Delete examination confirmation content');?>">
									<span class="glyphicon glyphicon-trash"></span> 
									<?php echo $this->translate('Delete');?>
								</a>
								<?php } ?>
							</td>
						</tr>
						<?php } ?>
					</tbody>
					<tfoot>
						<tr>
							<th colspan="6" class="text-center"><a class="btn btn-primary" href="<?php echo $this->url('examination', array('action'=>'add'));?>"><span class="glyphicon glyphicon-plus-sign"></span> <?php echo $this->translate('Add an examination')?></a></th>
						</tr>
					</tfoot>
				</table>
			<?php } ?>
			</div>
		</div>
	</div>
</div>
