<ol class="breadcrumb">
	<li><a href="<?php echo $this->url('manager')?>"><span class=" glyphicon glyphicon-home"></span> <?php echo $this->translate('Supervior dashboard');?></a></li>
	<li><a href="<?php echo $this->url('user')?>"><?php echo $this->translate('User management');?></a></li>
	<li class="active"><?php echo $this->translate('User account');?></li>
</ol>
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<span class="glyphicon glyphicon-user"></span> <?php echo $this->translate('User account');?>
			</div>
			<div class="panel-body">
				<form class="form-horizontal" role="form" method="post" action="<?php echo $this->url('user', array('action'=>'edit'))?>" onsubmit="return checkForm()">
					<div class="form-group">
						<label for="lastname" class="control-label col-md-2"><?php echo $this->translate("Lastname")?></label>
						<div class="col-md-6">
							<input type="text" class="form-control" id="lastname" name="lastname" value="<?php echo $this->user->lastname;?>" autocomplete="off" required />
						</div>
					</div>
					<div class="form-group">
						<label for="lastname" class="control-label col-md-2"><?php echo $this->translate("Firstname")?></label>
						<div class="col-md-6">
							<input type="text" class="form-control" id="firstname" name="firstname" value="<?php echo $this->user->firstname;?>" autocomplete="off" required />
						</div>
					</div>
					<div class="form-group">
						<label for="lastname" class="control-label col-md-2"><?php echo $this->translate("Login")?></label>
						<div class="col-md-6">
							<input type="text" class="form-control" id="login" name="login" value="<?php echo $this->user->login;?>" autocomplete="off" required />
						</div>
					</div>
					<div class="form-group">
						<label for="lastname" class="control-label col-md-2"><?php echo $this->translate("New Password (let it empty if not modified)")?></label>
						<div class="col-md-6">
							<input type="password" class="form-control" id="password" name="password" value="" autocomplete="off"/>
						</div>
					</div>
					<div class="form-group">
						<label for="lastname" class="control-label col-md-2"><?php echo $this->translate("Confirm password (let it empty if not modified)")?></label>
						<div class="col-md-6">
							<input type="password" class="form-control" id="password-confirm" name="password-confirm" value="" autocomplete="off"/>
						</div>
					</div>
					<div class="form-group">
						<label for="admin" class="control-label col-md-2"><?php echo $this->translate('User is manager'); ?></label>
						<div class="btn-group" data-toggle="buttons">
							<label class="btn btn-default <?php if(!$this->user->admin){echo "active";}?>">
								<input type="radio" name="admin" id="no" autocomplete="off" value="0" <?php if (!$this->user->admin) { echo "checked"; }?> /> <?php echo $this->translate('No'); ?>
							</label>
							<label class="btn btn-default <?php if($this->user->admin){echo "active";}?>">
								<input type="radio" name="admin" id="yes" autocomplete="off" value="1" <?php if ($this->user->admin) { echo "checked"; }?> /> <?php echo $this->translate('Yes'); ?>
							</label>
						</div>
					</div>	
					<input type="hidden" id="id" name="id" value="<?php echo $this->user->id;?>" />
					<button type="submit" class="btn btn-primary"><?php echo $this->translate("Submit")?></button>
					<button type="button" class="btn btn-danger" onClick="window.location='<?php echo $this->url('user')?>'"><?php echo $this->translate("Abort")?></button>
				</form>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	function	checkForm()
	{
		if($("#password").val() == $("#password-confirm").val())
		{
			return true;
		}
		else
		{
			$("#password").parents('.form-group').addClass('has-error');
			$("#password-confirm").parents('.form-group').addClass('has-error');
			return false;
		}
	}
</script>