<ol class="breadcrumb">
	<li><a href="<?php echo $this->url('manager')?>"><span class=" glyphicon glyphicon-home"></span> <?php echo $this->translate('Supervior dashboard');?></a></li>
	<li class="active"><?php echo $this->translate('User management');?></li>
</ol>
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<span class="fa fa-user-md"></span> <?php echo $this->translate('User list');?>
			</div>
			<div class="panel-body">
				<table class="table table-striped table-hover">
					<thead>
						<tr>
							<th><?php echo $this->translate('Lastname');?></th>
							<th><?php echo $this->translate('Firstname');?></th>
							<th><?php echo $this->translate('Login');?></th>
							<th><?php echo $this->translate('Supervisor');?></th>
							<th><?php echo $this->translate('Action');?></th>
						</tr>
					</thead>
					<tbody>
						<?php foreach($users as $user) { ?>
						<tr>

							<td><?php echo $this->escapeHtml($user->lastname);?></td>
							<td><?php echo $this->escapeHtml($user->firstname);?></td>
							<td><?php echo $this->escapeHtml($user->login);?></td>
							<td>
								<?php if($user->admin){?>
								<p><?php echo $this->translate('Yes');?></p>
								<?php } else { ?>
								<p><?php echo $this->translate('No');?></p>
								<?php }?>
							</td>
							<td class="col-md-4">
								<a href="<?php echo $this->url('user', array('action'=>'edit', 'id'=>$user->id))?>" class="btn btn-primary">
									<span class="glyphicon glyphicon-pencil"></span> <?php echo $this->translate('Edit');?>
								</a>
								<a href="<?php echo $this->url('user', array('action'=>'delete', 'id'=>$user->id))?>"  class="btn btn-danger" 
									role="delete" data-delete-title="<?php echo $this->translate('Delete user confirmation title');?>" data-delete-content="<?php echo $this->translate('Delete user confirmation content');?>">
									<span class="glyphicon glyphicon-trash"></span> <?php echo $this->translate('Delete');?>
								</a>
							</td>
						</tr>
						<?php } ?>
					</tbody>
					<tfoot>
						<tr>
							<th colspan="5" class="text-center"><a class="btn btn-primary" href="<?php echo $this->url('user', array('action'=>'add'));?>"><span class="glyphicon glyphicon-plus-sign"></span> <?php echo $this->translate('Add user');?></a></th>
						</tr>
					</tfoot>
				</table>
			</div>
		</div>
	</div>
</div>