CREATE DATABASE IF NOT EXISTS `sami` ;

GRANT ALL ON sami.* TO 'sami'@'localhost' IDENTIFIED BY 'sami' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;
GRANT SELECT, INSERT, UPDATE, DELETE ON sami.* TO 'sami'@'localhost';
