<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Bufferspace\Module'                        => __DIR__ . '/Module.php',
    'Bufferspace\Controller\MonitorController' => __DIR__ . '/src/Bufferspace/Controller/MonitorController.php',
    'BufferspaceTest\Framework\TestCase'        => __DIR__ . '/tests/Bufferspace/Framework/TestCase.php',
    'BufferspaceTest\SampleTest'                => __DIR__ . '/tests/Bufferspace/SampleTest.php',
);
