<ol class="breadcrumb">
	<li><a href="<?php echo $this->url('manager')?>"><span class=" glyphicon glyphicon-home"></span> <?php echo $this->translate('Supervior dashboard');?></a></li>
	<li class="active"><?php echo $this->translate('Activimeter')?></li>
</ol>
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<span class="glyphicon glyphicon-dashboard"></span> <?php echo $this->translate('Activimeter');?>
			</div>
			<div class="panel-body">
				<applet archive="/jar/tightvnc-jviewer.jar"
						code="com.glavsoft.viewer.Viewer"
						width="1" height="1">
					<param name="Host" value="10.0.0.100" /> <!-- Host to connect. Default:  the host from which the applet was loaded. -->
					<param name="Port" value="5900" /> <!-- Port number to connect. Default: 5900 -->
					<param name="Password" value="c"> <!-- Password to the server (not recommended to use this parameter here) -->
				</applet>
			</div>
		</div>
	</div>
</div>
