<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Tools\Module'                        => __DIR__ . '/Module.php',
    'Tools\Controller\ToolsController' => __DIR__ . '/src/Tools/Controller/ToolsController.php',
    'ToolsTest\Framework\TestCase'        => __DIR__ . '/tests/Tools/Framework/TestCase.php',
    'ToolsTest\SampleTest'                => __DIR__ . '/tests/Tools/SampleTest.php',
);
