<?php //TODO Trad high prio ?>
<ol class="breadcrumb">
	<li><a href="<?php echo $this->url('operator')?>"><span class="glyphicon glyphicon-home"></span> <?php echo $this->translate('Operator dashboard')?></a></li>
	<li><?php echo $this->translate('Injection')?></li>
	<li class="active"><?php echo $this->translate('Dilution')?></li>
</ol>
<div class="row">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<?php echo $this->translate('Dilution')?>
		</div>
		<div class="panel-body">
			<div class="panel-group" id="accordion">
				<div class="panel panel-info">
					<div class="panel-heading">
						<div class="panel-title">
							<a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"><?php echo $this->translate("Patient's data")?></a>
						</div>
					</div>
					<div id="collapseOne" class="panel-collapse collapse in">
						<div class="panel-body">
							<div class="row">
								<div class="col-md-3"><?php echo $this->translate('Lastname')?></div>
								<div class="col-md-3"><input type="text" value="<?php echo $patient['lastname']?>" class="form-control" autocomplete="off" maxlength="100" disabled/></div>
								<div class="col-md-3"><?php echo $this->translate('Firstname')?></div>
								<div class="col-md-3"><input type="text" value="<?php echo $patient['firstname']?>" class="form-control" autocomplete="off" maxlength="100" disabled/></div>
							</div>
							<div class="row">
								<div class="col-md-3">Activité prélevée</div>
								<div class="col-md-3"><div class="input-group"><input type="number" value="<?php echo $injection['activity']?>" class="form-control" autocomplete="off" disabled/><span class="input-group-addon"><?php echo $unit?></span></div></div>
								<div class="col-md-6"></div>
							</div>
							<div class="row">
								<div class="col-md-2 col-md-offset-10">
									<button type="button" class="btn btn-primary" id="dilution-confirm" onClick="launchDilution()">Validation</button>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="panel panel-danger" id="statut-block">
					<div class="panel-heading">
						Progression dilution
					</div>
					<div class="panel-body">
						<p><strong>Statut :</strong> <span id="dilution-statut">En attente de validation informations patient...</span></p>
						<div class="row">
							<div class="col-md-12">
								<div class="progress progress-striped active">
									<div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%" id="dilution-progress">
										<span class="sr-only">45% Complete</span>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-2 col-md-offset-4">
					<button id="btn-next" type="button" class="btn btn-success btn-block" onClick="location.href='<?php echo $this->url('inject', array('action'=>'injection'))?>'" disabled>Suivant</button>
				</div>
				<div class="col-md-2">
					<button id="btn-exit" type="button" class="btn btn-danger btn-block" onClick="location.href='<?php echo $this->url('operator')?>'">Annuler</button>
				</div>
			</div>
			<script type="text/javascript">
					var value = 0;
					function moveProgressBar()
					{
            $.ajax({
              type: "POST",
              url: "<?php echo $this->url('inject', array('action'=>'agetdilutionprogress'))?>",
              dataType: "json",
              data: {}
            }).done(function (result) {

						if(result.progress < 100)
						{
							$("#dilution-progress").css('width', result.progress+'%');
							window.setTimeout(function(){moveProgressBar();}, 500);
						}
						else
						{
							$("#dilution-progress").css('width', result.progress+'%');
							$('#statut-block').removeClass('panel-info panel-success panel-warning').addClass('panel-success');
							$('#dilution-statut').html('Dilution terminée ! Médicament prêt');
							$("#btn-next").removeAttr('disabled');
						}
						});
					}

					function launchDilution()
					{
						$("#dilution-confirm").attr('disabled', 1);
						$('#statut-block').removeClass('panel-danger panel-success panel-warning').addClass('panel-warning');
						$('#collapseOne').collapse('toggle');
						$('#dilution-statut').html('Dilution en cours...');
            $.ajax({
              type: "POST",
              url: "<?php echo $this->url('inject', array('action'=>'alaunchdilution'))?>",
              dataType: "json",
              data: {}
            });


						moveProgressBar();
					}
				</script>
		</div>
	</div>
</div>
