<ol class="breadcrumb">
	<li><a href="<?php echo $this->url('operator')?>"><span class=" glyphicon glyphicon-home"></span> <?php echo $this->translate('Operator dashboard')?></a></li>
	<li><?php echo $this->translate('Injection')?></li>
	<li class="active"><?php echo $this->translate('End of injection')?></li>
</ol>
<div class="row">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<?php echo $this->translate('End of injection')?>
		</div>
		<div class="panel-body">
			<p><?php echo $this->translate('End of injections mean rinsing the needle and reinject the content into the source vial.')?></p>
			<p><?php echo $this->translate('Remaining activity at ')?><span id="activity-time"></span>: <span id="activity"></span><?php echo $unit?></p>
			<p><?php echo $this->translate('Confirm the end of injection?')?></p>
			<div class="row">
				<div class="col-md-3"></div>
				<div class="col-md-3 text-center"><button class="btn btn-primary" id="btnconfirm"><?php echo $this->translate('YES')?></button></div>
				<div class="col-md-3 text-center"><button class="btn btn-danger"  id="btncancel"><?php echo $this->translate('NO')?></button></div>
				<div class="col-md-3"></div>
					
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="confirmmodal" tabindex="-1" role="dialog" aria-labelledby="confirmmodaltitle" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="confirmmodaltitle"><?php echo $this->translate('Confirm the end of injection')?></h4>
			</div>
			<div class="modal-body">
				<p><?php echo $this->translate('Are you sure to confirm the end of injection')?></p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('No')?></button>
				<button type="button" class="btn btn-primary" id="launchaction"><?php echo $this->translate('Yes')?></button>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	$(function(){
		loadActivityData();
		$('#btncancel').click(function(){
			window.location.href = "<?php echo $this->url('operator'); ?>";
		});
		$('#btnconfirm').click(function(){
			$('#confirmmodal').modal('show');
		});
		$('#launchaction').click(function(){
			// doing stuff here, dunno what
			$.ajax({
				url: "<?php echo $this->url('inject', array('action'=>'amarkendinject')); ?>"
			}).done(function(){
				window.location.href = "<?php echo $this->url('operator'); ?>";
			});
			$('#confirmmodal').modal('hide');
		});
	});

	//TOOD Inutile pour l'instant. Voir si ils faut supprimer ce code.
	function	loadActivityData()
	{
		$.ajax({
			type: "GET",
			url: "<?php echo $this->url('setup', array('action'=>'agetavailableactivity')); ?>",
			dataType: "json"
		}).done(function(result) {
			var data = result;
			$("#activity-time").html(data.time);
			$("#activity").html(data.activity);
		});
		//setTimeout(function(){loadActivityData();}, 5000);
	}
</script>