<?php $timeInjection = DateTime::createFromFormat('d-m-Y H:i:s', date('d-m-Y') . ' ' . $injection['injection_time']); ?>
<ol class="breadcrumb">
	<li><a href="<?php echo $this->url('operator'); ?>"><span class=" glyphicon glyphicon-home"></span> <?php echo $this->translate('Operator dashboard'); ?></a></li>
	<li><?php echo $this->translate('Injection'); ?></li>
	<li class="active"><?php echo $this->translate('Patient disconnection'); ?></li>
</ol>
<div class="row">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<?php echo $this->translate('Patient disconnection'); ?>
		</div>
		<div class="panel-body">
			<div class="row">
				<label for="lastname" class="col-sm-3 control-label"><?php echo $this->translate('Location of injection'); ?></label>
				<div class="col-sm-6">
					<input type="text" tabindex="1" class="form-control input-sm" id="location_input" name="location_input" placeholder="" maxlength="200" autocomplete="off" />
				</div>
				<div class="col-sm-3">
					<button id="location_validation" class="btn btn-primary btn-block"><?php echo $this->translate('Validation'); ?></button>
				</div>
			</div>
			<div id="resume" style="display:none; margin-top: 10px;">
				<div class="row">
					<div class="col-sm-8">
						<div class="panel panel-default">
							<div class="panel-heading">
								<?php echo $this->translate('Informations resume'); ?>
							</div>
							<div class="panel-body">
								<div class="row table-responsive">
									<table class="table table-bordered table-condensed">
										<tr>
											<th colspan="2">
												<span class="label label-primary" title="<?php echo $this->translate('Ordonnancier'); ?>"><i class="fa fa-clipboard"></i>&nbsp;<?php echo $injection['unique_id']; ?></span> 
												<?php echo $patient['lastname']; ?> <?php echo $patient['firstname']; ?> [<?php echo $patient['birthdate']; ?>] 
												(<?php echo $patient['weight']; ?>kg) 
											</th>
										</tr>
										<tr>
											<td><?php echo $drug['name']; ?> <?php echo $this->translate('Serial : '); ?> <?php echo $curdrug['batchnum']; ?></td>
											<td><i class="fa fa-eyedropper"></i><?php echo $injection['activity']; ?> <?php echo $unit ; ?></td>
										</tr>
										<tr>
											<td>Injection <i class="fa fa-clock-o"></i><?php echo $injection['injection_time']; ?><</td>
											<td><i class="glyphicon glyphicon-screenshot"> <?php echo $injection['location']; ?></i></td>
										</tr>
										<tr>
											<th colspan="2">
												<i class="fa fa-user-md"></i> 
												<?php echo strtoupper($operator['lastname']); ?> <?php echo ucfirst(strtolower($operator['firstname'])); ?>
											</th>
										</tr>
										<tr>
											<td></td>
											<td>/td>
										</tr>
										<tr>
											<td><?php echo $examination['name']; ?></td>
											<td></td>
										</tr>
										<tr>
											<td>
												Kit source : <span class="label label-success">OUI</span> <a href="javascript:void(0);" data-toggle="tooltip" data-placement="right" title="<?php echo $sourcekit['serialnumber']; ?>"><i class="glyphicon glyphicon-barcode" ></i></a>
												<br />
												Kit patient : <span class="label label-success">OUI</span> <a href="javascript:void(0);" data-toggle="tooltip" data-placement="right" title="<?php echo $patientkit['serialnumber']; ?>"<i class="glyphicon glyphicon-barcode"></i></a>
											</td>
											<td>Commentaire : <?php echo $injection['comments']; ?></td>
										</tr>
									</table>
								</div>
							</div>
						</div>
					</div>
					<div class="col-sm-4">	
						<div class="panel panel-default">
							<div class="panel-heading">
								<?php echo $this->translate('Printing sticker'); ?>
								<button class="btn btn-primary pull-right" onclick="printSticker();" title="<?php echo $this->translate('Send to printer'); ?>"><i class="glyphicon glyphicon-print"></i></button>
								<div style="clear: both;"></div>
							</div>
							<div class="panel-body">
								<div class="print-container" id="sticker">
									<div class="content">
										<div class="row">
								    		<div class="col-xs-2 no-padding"><span style="font-size: 2.6em; font-weight: normal; line-height: 0.8em;">&#9762;</span></div>
								    		<div class="col-xs-6 no-padding" style="margin-top: 1mm;"><?php echo date('d/m/Y'); ?></div>
								    		<div class="col-xs-4 no-padding" style="margin-top: 1mm;"><?php echo $timeInjection->format('H:i'); ?></div>
								  		</div>
										<div class="row">
											<div class="col-xs-10 col-xs-offset-2 no-padding"><?php echo $drug['name']; ?></div>
										</div>
										<div class="row">
											<div class="col-xs-7 col-xs-offset-5 no-padding"><?php echo $injection['activity'] . ' ' . $unit; ?></div>
										</div>
										<div class="row spacer"></div>
										<div class="row">
											<div class="col-xs-5 no-padding"><?php echo $radionuclide['code']; ?></div>
											<div class="col-xs-7 no-padding"><?php echo $this->translate('Serial : '); ?><span><?php echo $curdrug['batchnum']; ?></span></div>
										</div>
										<div class="row spacer"></div>
										<div class="row">
											<div class="col-xs-5 no-padding">N&ordm; <span><?php echo $injection['unique_id']; ?></span></div>
											<div class="col-xs-7 no-padding"><?php echo strtoupper($operator['lastname']); ?> <?php echo ucfirst(strtolower($operator['firstname'])); ?></div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<p><?php echo $this->translate('Please disconnect the patient kit, trash it and validate.'); ?></p>
						<button class="btn btn-primary" id="showactivityleft"><?php echo $this->translate('Validation'); ?></button>
					</div>
				</div>
			</div>
			<div id="nextstep" style="display: none;">
				<div class="row">
					<div class="col-md-12">
						<p><?php echo $this->translate('Remaining activity at '); ?><span id="activity-time"></span>: <span id="activity"></span><?php echo $unit; ?></p>
						<p style="float:left;"><?php echo $this->translate('Remaining activity at '); ?>
							<div id="activity-attime" class="input-group date" style="width: 30%;float: left;">
								<input name="activityattime" id="activityattime" type="text" class="form-control input-sm" data-format="YYYY-MM-DD HH:mm" size="16" maxlength="10" autocomplete="off"/>
								<span class="input-group-addon">
									<span class="glyphicon glyphicon-calendar"></span>
								</span>
							</div>
						</p>
								: <span id="activityat"></span><?php echo $unit; ?>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-3">
						<a href="<?php echo $this->url('bufferspace', array('action'=>'patientlist')); ?>" class="btn btn-primary btn-block"><?php echo $this->translate('Injected patients list'); ?></a>
					</div>
					<div class="col-sm-3">
						<a href="<?php echo $this->url('auth', array('action'=>'confirmauth')); ?>" class="btn btn-primary btn-block"><?php echo $this->translate('Launch another injection'); ?></a>
					</div>
					<div class="col-sm-3">
						<a href="<?php echo $this->url('inject', array('action'=>'endinject')); ?>" class="btn btn-primary btn-block"><?php echo $this->translate('End of injections'); ?></a>
					</div>
					<div class="col-sm-3">
						<a href="<?php echo $this->url('operator', array('action'=>'index')); ?>" class="btn btn-primary btn-block"><?php echo $this->translate('Operator menu'); ?></a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	$(function(){
		$('#resume').hide();
		$('#nextstep').hide();
		$('#location_validation').click(function(){
			$.ajax({
				type: "POST",
				url: "<?php echo $this->url('inject', array('action'=>'storelocation')); ?>",
				data: { location: $('#location_input').val()}
			});
			$('#location').html($('#location_input').val());
			$('#resume').show();
		});
		$('#activity-attime').datetimepicker({
			language: 'en',
			setDate: new Date()
		})
			.on("changeDate", function(e)
					{
						alert("hohoho");
					})
			.on("change", function (e)
					{
						$.ajax({
							type: "POST",
							url: "<?php echo $this->url('setup', array('action'=>'agetavailableactivityat')); ?>",
							dataType: "json",
							data: {wantedat : "DT#" + $("#activityattime").val().replace(" ", "-") + ":00"}
						}).done(function(result) {
							var data = result;
							$("#activityat").html(data.activity);
						});
					});
		toto = new Date();
		$('#activityattime').val(toto.getFullYear() + "-" + (toto.getMonth() + 1) + "-" + toto.getDate() + " " + toto.getHours() + ":" + toto.getMinutes());
		$('#showactivityleft').click(function(){
			loadActivityData();
			$.ajax({
				type: "POST",
				url: "<?php echo $this->url('inject', array('action'=>'adisconnectpatient')); ?>"
			});

			$('#nextstep').show();
		});
	});

	$(function() {
		$('[data-toggle="tooltip"]').tooltip();
	});
	
	function	loadActivityData()
	{
		$.ajax({
			type: "GET",
			url: "<?php echo $this->url('setup', array('action'=>'agetavailableactivity'))?>",
			dataType: "json"
		}).done(function(result) {
			var data = result;
			$("#activity-time").html(data.time);
			$("#activity").html(data.activity);
		});
		//setTimeout(function(){loadActivityData();}, 5000);
	}


	function	printSticker() {
		printElement(document.getElementById("sticker"));
		window.print();
	}
</script>
