<?php $timeInjection = DateTime::createFromFormat('d-m-Y H:i:s', date('d-m-Y') . ' ' . $injection['injection_time']); ?>
<ol class="breadcrumb">
	<li><a href="<?php echo $this->url('operator'); ?>"><span class=" glyphicon glyphicon-home"></span> <?php echo $this->translate('Operator dashboard'); ?></a></li>
	<li><?php echo $this->translate('Injection'); ?></li>
	<li class="active"><?php echo $this->translate('Patient disconnection'); ?></li>
</ol>
<div class="row">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<?php echo $this->translate('Patient disconnection'); ?>
		</div>
		<div class="panel-body">
			<div class="row" id="location_block">
				<label for="lastname" class="col-sm-3 control-label"><?php echo $this->translate('Location of injection'); ?></label>
				<div class="col-sm-6">
					<input type="text" tabindex="1" class="form-control input-sm" id="location_input" name="location_input" placeholder="" maxlength="200" autocomplete="off" />
				</div>
				<div class="col-sm-3">
					<button id="location_validation" class="btn btn-primary btn-block"><?php echo $this->translate('Validation'); ?></button>
				</div>
			</div>
			<div id="resume" style="display:none; margin-top: 10px;">
				<div class="row">
					<div class="col-sm-8">
						<div class="panel panel-default">
							<div class="panel-heading">
								<?php echo $this->translate('Informations resume'); ?>
								<button class="btn btn-default pull-right" onclick="togglePanel(this)" data-toggle="collapse" data-target="#panel-body-infos" aria-expanded="true" aria-controls="panel-body-infos">
									<span id="panel-left-caret" class="caret rotate-180"></span>
								</button>
								<div class="clearfix"></div>
							</div>
							<div class="panel-body collapse in" id="panel-body-infos" style="padding: 0 15px;">
								<div class="row table-responsive">
									<table class="table table-bordered table-condensed" style="margin-bottom: 0;">
										<tr>
											<th colspan="2">
												<div class="col-sm-6">
													<span class="label label-primary" style="font-size: 1.2em;" title="<?php echo $this->translate('Prescription book'); ?>">
														<i class="fa fa-clipboard"></i>&nbsp;<?php echo $injection['unique_id']; ?>
													</span>&nbsp;
													<?php echo $patient['lastname']; ?> <?php echo $patient['firstname']; ?> 
												</div>
												<div class="col-sm-3">
													<i class="fa fa-birthday-cake"></i> <?php echo $patient['birthdate']; ?> 
												</div>
												<div class="col-sm-3">
													<i class="fa fa-tachometer"></i> <?php echo $patient['weight']; ?>kg
												</div>
											</th>
										</tr>
										<tr>
											<td>
												<div class="col-sm-6">
													<?php echo $drug['name']; ?> 
												</div>
												<div class="col-sm-6">
													<?php echo $this->translate('Serial : '); ?> <?php echo $curdrug['batchnum']; ?>
												</div>
											</td>
											<td>
												<i class="fa fa-eyedropper"></i>&nbsp;<?php echo $injection['activity']; ?> <?php echo $unit ; ?>
											</td>
										</tr>
										<tr>
											<td><?php echo $this->translate('Injection'); ?> : &nbsp;<i class="fa fa-clock-o"></i>&nbsp;<?php echo $injection['injection_time']; ?></td>
											<td><i class="glyphicon glyphicon-screenshot"></i> <span id="location"><?php echo $injection['location']; ?><span></td>
										</tr>
										<tr>
											<th colspan="2">
												<span class="label label-primary label-as-badge"><i class="fa fa-user-md" style="font-size: 2em;"></i></span>
												<?php echo strtoupper($operator['lastname']); ?> <?php echo ucfirst(strtolower($operator['firstname'])); ?>
											</th>
										</tr>
										<tr>
											<td><?php echo $this->translate('Exam'); ?> : <?php echo $examination['name']; ?></td>
											<td>
												<i class="fa fa-commenting" title="<?php echo $this->translate('Comments'); ?>"></i> 
												<?php if (strlen(trim($injection['comments']))) { echo $injection['comments']; } else { echo '<em>' . $this->translate('no comments') . '</em>'; } ?>
											</td>
										</tr>
										<tr>
											<td>
												<?php echo $this->translate('Source kit'); ?> : 
												<?php if ($sourcekit['serialnumber'] != '') { ?>
												<span class="label label-success"><?php echo $this->translate('YES'); ?></span> 
												<a href="javascript:void(0);" data-toggle="tooltip" data-placement="right" title="<?php echo $sourcekit['serialnumber']; ?>">
													<i class="glyphicon glyphicon-barcode" ></i>
												</a>
												<?php } else { ?>
												<span class="label label-danger"><?php echo $this->translate('NO'); ?></span> 
												<?php } ?>
											</td>
											<td>
												<?php echo $this->translate('Patient kit'); ?> : 
												<?php if ($patientkit['serialnumber'] != '') { ?>
												<span class="label label-success"><?php echo $this->translate('YES'); ?></span> 
												<a href="javascript:void(0);" data-toggle="tooltip" data-placement="right" title="<?php echo $patientkit['serialnumber']; ?>">
													<i class="glyphicon glyphicon-barcode"></i>
												</a>
												<?php } else { ?>
												<span class="label label-danger"><?php echo $this->translate('NO'); ?></span> 
												<?php } ?>
											</td>
										</tr>
									</table>
								</div>
							</div>
						</div>
					</div>
					<div class="col-sm-4">	
						<div class="panel panel-default">
							<div class="panel-heading">
								<?php echo $this->translate('Printing sticker'); ?>
								<button class="btn btn-primary" onclick="printSticker();" title="<?php echo $this->translate('Send to printer'); ?>"><i class="glyphicon glyphicon-print"></i></button>
								<button class="btn btn-default pull-right" onclick="togglePanel(this);" data-toggle="collapse" data-target="#panel-body-sticker" aria-expanded="true" aria-controls="panel-body-sticker">
									<span id="panel-right-caret" class="caret rotate-180"></span>
								</button>
							</div>
							<div class="panel-body collaspe in" id="panel-body-sticker">
								<div class="print-container" id="sticker">
									<div class="content">
										<div class="row">
								    		<div class="col-xs-2 no-padding"><span style="font-size: 2.6em; font-weight: normal; line-height: 0.8em;">&#9762;</span></div>
								    		<div class="col-xs-6 no-padding" style="margin-top: 1mm;"><?php echo date('d/m/Y'); ?></div>
								    		<div class="col-xs-4 no-padding" style="margin-top: 1mm;"><?php echo $timeInjection->format('H:i'); ?></div>
								  		</div>
										<div class="row">
											<div class="col-xs-10 col-xs-offset-2 no-padding"><?php echo $drug['name']; ?></div>
										</div>
										<div class="row">
											<div class="col-xs-7 col-xs-offset-5 no-padding"><?php echo $injection['activity'] . ' ' . $unit; ?></div>
										</div>
										<div class="row spacer"></div>
										<div class="row">
											<div class="col-xs-5 no-padding"><?php echo $radionuclide['code']; ?></div>
											<div class="col-xs-7 no-padding"><?php echo $this->translate('Serial : '); ?><span><?php echo $curdrug['batchnum']; ?></span></div>
										</div>
										<div class="row spacer"></div>
										<div class="row">
											<div class="col-xs-5 no-padding">N&ordm; <span><?php echo $injection['unique_id']; ?></span></div>
											<div class="col-xs-7 no-padding"><?php echo strtoupper($operator['lastname']); ?> <?php echo ucfirst(strtolower($operator['firstname'])); ?></div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<div class="alert alert-info" role="alert">
							<i class="glyphicon glyphicon-info-sign"></i> <?php echo $this->translate('Please disconnect the patient kit, trash it and validate.'); ?>
							<div class="btn-group">
								<button class="btn btn-primary" id="showactivityleft"><?php echo $this->translate('Validation')?></button>
								<button class="btn btn-danger"  id="showactivityleft-statut" disabled><span id="showactivityleft-statut-picto" class="glyphicon glyphicon-remove-sign"></span></button>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div id="nextstep" style="display: none;">
				<div class="row">
					<form class="form-horizontal">
						<div class="form-group has-info has-feedback">
							<label class="col-sm-2 col-sm-offset-2 control-label"><?php echo $this->translate('Remaining activity at '); ?></label>
							<div class="col-sm-3">
								<div class="input-group">
									<input type="text" class="form-control" id="activity-time" disabled />
									<span class="input-group-addon">
										<i class="glyphicon glyphicon-time"></i>
									</span>
								</div>
							</div>
							<div class="col-sm-3">
								<div class="input-group">
									<input type="number" class="form-control" id="activity" disabled />
									<span class="input-group-addon"><?php echo $unit; ?></span>
								</div>
							</div>
						</div>
					</form>
				</div>
				<div class="row">
					<form class="form-horizontal">
						<div class="form-group">
							<label for="activityattime" class="col-sm-2 col-sm-offset-2 control-label"><?php echo $this->translate('Remaining activity at '); ?></label>
							<div class="col-sm-3">
								<div id="activity-attime" class="input-group date">
									<input name="activityattime" id="activityattime" type="text" class="form-control" data-format="<?php echo $this->translate('YYYY-MM-DD HH:mm'); ?>" maxlength="16" autocomplete="off"/>
									<span class="input-group-addon">
										<i class="glyphicon glyphicon-calendar"></i>
									</span>
								</div>
							</div>
							<div class="col-sm-3">
								<div class="input-group has-success">
									<input type="text" class="form-control" id="activityat" disabled />
									<span class="input-group-addon"><?php echo $unit; ?></span>
								</div>
							</div>
						</div>
					</form>
				</div>
				<div class="row" style="margin-top: 10px;">
					<div class="col-sm-3">
						<a href="<?php echo $this->url('bufferspace', array('action'=>'patientlist')); ?>" class="btn btn-primary btn-block"><?php echo $this->translate('Injected patients list'); ?></a>
					</div>
					<div class="col-sm-3">
						<a href="<?php echo $this->url('auth', array('action'=>'confirmauth')); ?>" class="btn btn-primary btn-block"><?php echo $this->translate('Launch another injection'); ?></a>
					</div>
					<div class="col-sm-3">
						<a href="<?php echo $this->url('inject', array('action'=>'endinject')); ?>" class="btn btn-primary btn-block"><?php echo $this->translate('End of injections'); ?></a>
					</div>
					<div class="col-sm-3">
						<a href="<?php echo $this->url('operator', array('action'=>'index')); ?>" class="btn btn-primary btn-block"><?php echo $this->translate('Operator menu'); ?></a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	$(function(){
		$('#resume').hide();
		$('#nextstep').hide();

		<?php if (isset($launched) && $launched === true) { ?>
		$('#nextstep').show();
		$('#resume').show();
		$('#location_block').hide();
		$('#panel-body-infos').collapse('hide');
		$('#panel-body-sticker').collapse('hide');
		$('#panel-left-caret').removeClass('rotate-180');
		$('#panel-right-caret').removeClass('rotate-180');

		$('#showactivityleft-statut-picto').removeClass('glyphicon-calendar').addClass('glyphicon-time');
		$('#showactivityleft-statut').removeClass('btn-danger').addClass('btn-warning');
		$('#showactivityleft-statut-picto').removeClass('glyphicon-time').addClass('glyphicon-ok-sign');
		$('#showactivityleft-statut').removeClass('btn-warning').addClass('btn-success');
		$('#showactivityleft').attr('disabled', 1);

		loadActivityData();
		getAvailableActivityAt();
		
		<?php } ?>

		$('#location_validation').click(function(){
			$.ajax({
				type: "POST",
				url: "<?php echo $this->url('inject', array('action'=>'storelocation')); ?>",
				data: { location: $('#location_input').val()}
			});
			$('#location').html($('#location_input').val());
			$('#resume').show();
			$('#location_block').hide();
		});

		$('#activity-attime').datetimepicker({
			language: 'en',
			setDate: new Date()
		}).on("change", function (e) {
			getAvailableActivityAt();
		});

		var now = new Date();
		var month = now.getMonth() + 1;
		var day = now.getDate();
		var hour = now.getHours();
		var minutes = now.getMinutes();

		if (month < 10) {
			month = '0' + month;
		}
		if (day < 10) {
			day = '0' + day;
		}
		if (hour < 10) {
			hour = '0' + hour;
		}
		if (minutes < 10) {
			minutes = '0' + minutes;
		}

		$('#activityattime').val(now.getFullYear() + "-" + month + "-" + day + " " + hour + ":" + minutes);

		$('#showactivityleft').click(function(){
			$('#panel-body-infos').collapse('hide');
			$('#panel-body-sticker').collapse('hide');
			$('#panel-left-caret').removeClass('rotate-180');
			$('#panel-right-caret').removeClass('rotate-180');

			$('#showactivityleft-statut-picto').removeClass('glyphicon-calendar').addClass('glyphicon-time');
			$('#showactivityleft-statut').removeClass('btn-danger').addClass('btn-warning');
			$('#showactivityleft').attr('disabled', 1);

			loadActivityData();
			getAvailableActivityAt();
			
			$.ajax({
				type: "POST",
				url: "<?php echo $this->url('inject', array('action'=>'adisconnectpatient')); ?>"
			}).done(function(result) {
				setTimeout(function() {
					$('#showactivityleft-statut-picto').removeClass('glyphicon-time').addClass('glyphicon-ok-sign');
					$('#showactivityleft-statut').removeClass('btn-warning').addClass('btn-success');
				}, 1000);
			});

			$('#nextstep').show();
		});
	});

	$(function() {
		$('[data-toggle="tooltip"]').tooltip();
	});

	function	getAvailableActivityAt() {
		$.ajax({
			type: "POST",
			url: "<?php echo $this->url('setup', array('action'=>'agetavailableactivityat')); ?>",
			dataType: "json",
			data: {wantedat : "DT#" + $("#activityattime").val().replace(" ", "-") + ":00"}
		}).done(function(result) {
			var data = result;
			$("#activityat").val(data.activity);
		});
	}

	function	togglePanel(that) {
		$(that).children('.caret').toggleClass('rotate-180');
	}
	
	function	loadActivityData()
	{
		$.ajax({
			type: "GET",
			url: "<?php echo $this->url('setup', array('action'=>'agetavailableactivity'))?>",
			dataType: "json"
		}).done(function(result) {
			var data = result;
			$("#activity-time").val(data.time);
			$("#activity").val(data.activity);
		});
		setTimeout(function() { loadActivityData();}, 5000);
	}


	function	printSticker() {
		printElement(document.getElementById("sticker"));
		window.print();
	}
</script>
