<ol class="breadcrumb">
	<li><a href="<?php echo $this->url('operator')?>"><span class="glyphicon glyphicon-home"></span> <?php echo $this->translate('Operator dashboard')?></a></li>
	<li><?php echo $this->translate('Injection')?></li>
	<li class="active"><?php echo $this->translate('Rinsing')?></li>
</ol>
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<?php echo $this->translate('Rinsing')?>
			</div>
			<div class="panel-body">
				<div class="panel panel-info">
					<div class="panel-heading">
						<?php echo $this->translate("Patient's data")?>
					</div>
					<div class="panel-body">
						<div class="row">
							<div class="col-md-3"><?php echo $this->translate('Lastname')?></div>
							<div class="col-md-3"><input value="<?php echo $patient['lastname']?>" class="form-control" disabled/></div>
							<div class="col-md-3"><?php echo $this->translate('Firstname')?></div>
							<div class="col-md-3"><input value="<?php echo $patient['firstname']?>" class="form-control" disabled/></div>
						</div>
						<div class="row">
							<div class="col-md-3"><?php echo $this->translate('Activity injected')?></div>
							<div class="col-md-3"><div class="input-group"><input value="<?php echo $injection['activity']?>" class="form-control" disabled/><span class="input-group-addon"><?php echo $unit?></span></div></div>
							<div class="col-md-2 col-md-offset-3"><button type="button" class="btn btn-primary" id="rinsing-confirm" onClick="launchRinsing()">Lancer le rinçage</button></div>
						</div>
					</div>
				</div>
				<div class="panel panel-danger" id="statut-block">
					<div class="panel-heading">
						<?php echo $this->translate('Rinsing progress')?>
					</div>
					<div class="panel-body">
						<p><strong><?php echo $this->translate("Status")?> :</strong> <span id="rinsing-statut">En attente de validation utilisateur...</span></p>
						<div class="row">
							<div class="col-md-12">
								<div class="progress">
									<div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%" id="rinsing-progress-1">
										<span class="sr-only"></span>
									</div>
									<div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%" id="rinsing-progress-2">
										<span class="sr-only"></span>
									</div>
									<div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%" id="rinsing-progress-3">
										<span class="sr-only"></span>
									</div>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-1 col-md-offset-2">
								<button class="btn btn-primary" onClick="pauseRinsing()" id="btn-pause"><span class="glyphicon glyphicon-pause"></span></button>
							</div>
							<div class="col-md-1">
								<button class="btn btn-primary" onClick="playRinsing()" id="btn-play" disabled><span class="glyphicon glyphicon-play"></span></button>
							</div>
							<div class="col-md-8 text-right">
								Règlage du débit:
								<button onClick="rinsingSlowDown()"><span class="glyphicon glyphicon-minus"></span></button>
								<input type="text" id="debit-controller" value="" data-slider-min="0" data-slider-max="4" data-slider-step="1" data-slider-value="2" data-slider-orientation="horizontal" data-slider-selection="after"data-slider-tooltip="hide">
								<button onClick="rinsingSpeedUp()"><span class="glyphicon glyphicon-plus"></span></button>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="row" style="margin-top:10px;margin-bottom:10px;">
				<div class="col-md-2 col-md-offset-4">
					<button id="btn-next" type="button" class="btn btn-success btn-block" onClick="location.href='<?php echo $this->url('inject', array('action'=>'patientdisconnection'))?>'" disabled>Suivant</button>
				</div>
				<div class="col-md-2">
					<button id="btn-exit" type="button" class="btn btn-danger btn-block" onClick="location.href='<?php echo $this->url('operator')?>'">Annuler</button>
				</div>
			</div>
			<script type="text/javascript">
				var value1 = 0;
				var value2 = 0;
				var value3 = 100;
				var way = 0;
				var rinsed = 1;
				var statut = 1;

				var timerAnim; // instance of timer used by moveProgressBar
				var frequency = 500; // value of interval (in ms)

				function moveProgressBar()
				{
					timerAnim = window.setInterval(function(){animProgressBar();}, frequency);
				}

				function	stopProgressBar()
				{
					window.clearInterval(timerAnim);
				}

				function	animProgressBar()
				{
              $.ajax({
              type: "POST",
              url: "<?php echo $this->url('inject', array('action'=>'agetpurgeprogress'))?>",
              dataType: "json",
              data: {}
            }).done(function (result) {

					var speed = $("#debit-controller").slider('getValue');
					if(Number(result.progress) <= 50)
					{
						value2 = result.progress * 2;
						value3 = 100 - result.progress * 2;
					}
					else
					{
						value1 = (result.progress - 50) * 2;
						value2 = 100 - (result.progress - 50) * 2;
					}
					$("#rinsing-progress-1").css('width', value1+'%');
					$("#rinsing-progress-2").css('width', value2+'%');
					$("#rinsing-progress-3").css('width', value3+'%');

					if(value1 >= 100)
					{
						stopProgressBar();
						$("#rinsing-progress-1").css('width', '100%');
						$("#rinsing-progress-2").css('width', '0%');
						$("#rinsing-progress-3").css('width', '0%');
						$('#statut-block').removeClass('panel-info panel-success panel-warning').addClass('panel-success');
						$("#rinsing-confirm").removeAttr('disabled');
						$('#rinsing-statut').html('Rinçage terminé ! Appuyez sur le bouton "Lancer le rinçage" pour relancer un rinçage');
						rinsed = 1;
						checkEnableNext();
					}
					});
				}

				function launchRinsing()
				{
					$("#rinsing-confirm").attr('disabled', 1);
					$('#statut-block').removeClass('panel-danger panel-success panel-warning').addClass('panel-warning');
					$('#collapseOne').collapse('toggle');
					$('#rinsing-statut').html('Rinçage en cours...');
					moveProgressBar();
				}

				function	pauseRinsing()
				{
					$('#btn-pause').attr('disabled', 1);
					$('#btn-play').removeAttr('disabled');
					stopProgressBar();
				}

				function	playRinsing()
				{
					$('#btn-play').attr('disabled', 1);
					$('#btn-pause').removeAttr('disabled');
          $.ajax({
              type: "POST",
              url: "<?php echo $this->url('inject', array('action'=>'alaunchinjection'))?>",
              dataType: "json",
              data: {}
            });

					moveProgressBar();
				}

        function sendSpeedInjection()
        {
          $.ajax({
            type: "POST",
            url: "<?php echo $this->url('inject', array('action'=>'aspeedinjection'))?>",
            dataType: "json",
            data: {speed :  $("#debit-controller").slider('getValue') * 25}
          });
        }

				function	rinsingSlowDown()
				{
					pauseRinsing();
					if($("#debit-controller").slider('getValue') > 0)
					{
						$("#debit-controller").slider('setValue', $("#debit-controller").slider('getValue') - 1);
					}
					sendSpeedInjection();
				}

				function	rinsingSpeedUp()
				{
					pauseRinsing();
					if($("#debit-controller").slider('getValue') < 4)
					{
						$("#debit-controller").slider('setValue', $("#debit-controller").slider('getValue') + 1);
					}
					sendSpeedInjection();
				}

				function	checkEnableNext()
				{
					if(rinsed == 1)
					{
						$("#btn-next").removeAttr('disabled');
					}
				}

				function	blockNextStep()
				{
					$("#btn-next").attr('disabled', 1);
				}

				$(function(){
					$('#debit-controller').slider()
					.on('slideStart', function(){
						pauseRinsing();
					})
					.on('slideStop', function() {
						//playRinsing();
					});
				  $.ajax({
            type: "POST",
            url: "<?php echo $this->url('inject', array('action'=>'agetspeedinjection'))?>",
            dataType: "json",
            data: {}
          }).done(function (result) {
						$("#debit-controller").slider('setValue', result.speed);
					});
				});
			</script>
		</div>
	</div>
</div>
