<?php //TODO Trad high prio ?>
<?php
$this->headStyle()->appendStyle('
.slider-selection {
	background: #337ab7;
}');
?>
<ol class="breadcrumb">
	<li><a href="<?php echo $this->url('operator')?>"><span class="glyphicon glyphicon-home"></span> <?php echo $this->translate('Operator dashboard')?></a></li>
	<li><?php echo $this->translate('Injection')?></li>
	<li class="active"><?php echo $this->translate('Rinsing')?></li>
</ol>
<div class="row">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<?php echo $this->translate('Rinsing')?>
		</div>
		<div class="panel-body">
			<div class="panel panel-info">
				<div class="panel-heading">
					<?php echo $this->translate("Patient's data")?>
				</div>
				<div id="collapseOne" class="panel-collapse collapse in">
					<div class="panel-body">
						<div class="row">
							<div class="col-md-3"><?php echo $this->translate('Lastname')?></div>
							<div class="col-md-3"><input value="<?php echo $patient['lastname']?>" class="form-control" autocomplete="off" disabled/></div>
							<div class="col-md-3"><?php echo $this->translate('Firstname')?></div>
							<div class="col-md-3"><input value="<?php echo $patient['firstname']?>" class="form-control" autocomplete="off" disabled/></div>
						</div>
						<div class="row">
							<div class="col-md-3"><?php echo $this->translate('Activity injected')?></div>
							<div class="col-md-3"><div class="input-group"><input type="number" value="<?php echo $injection['activity']?>" class="form-control" autocomplete="off" disabled/><span class="input-group-addon"><?php echo $unit?></span></div></div>
							<div class="col-md-2 col-md-offset-3"><button type="button" class="btn btn-primary" id="rinsing-confirm" onClick="launchRinsing(false)">Lancer le rinçage</button></div>
						</div>
					</div>
				</div>
			</div>
			<div class="panel panel-danger" id="statut-block">
				<div class="panel-heading">
					<?php echo $this->translate('Rinsing progress')?>
				</div>
				<div class="panel-body">
					<p><strong><?php echo $this->translate("Status")?> :</strong> <span id="rinsing-statut">En attente de validation utilisateur...</span></p>
					<div class="row">
						<div class="col-md-12">
							<div class="progress">
								<div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%" id="rinsing-progress-1">
									<span class="sr-only"></span>
								</div>
								<div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%" id="rinsing-progress-2">
									<span class="sr-only"></span>
								</div>
								<div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%" id="rinsing-progress-3">
									<span class="sr-only"></span>
								</div>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-4">
							<button class="btn btn-primary" onClick="pauseRinsing()" id="btn-pause" disabled><span class="glyphicon glyphicon-pause"></span></button>
							<button class="btn btn-primary" onClick="playRinsing()" id="btn-play" disabled><span class="glyphicon glyphicon-play"></span></button>
						</div>
						<div class="col-md-4">
							Règlage du débit:
							<input type="text" id="debit-controller" data-slider-min="1" data-slider-max="10" data-slider-step="1" data-slider-value="5" autocomplete="off">
						</div>
						<div class="col-md-4">
							<div class="input-group">
								<input id="debitVal" type="number" value="0.5" class="form-control ui-keyboard-input input-md ui-keyboard-nokeyboard" autocomplete="off" disabled aria-haspopup="true" role="textbox" />
								<span class="input-group-addon">ml / s</span>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="row" style="margin-top:10px;margin-bottom:10px;">
			<div class="col-md-2 col-md-offset-3">
				<button id="btn-next" type="button" class="btn btn-success btn-block" onclick="location.href='<?php echo $this->url('inject', array('action'=>'patientdisconnection'))?>'" disabled>Suivant</button>
			</div>
			<div class="col-md-2">
				<button id="btn-relaunch" type="button" class="btn btn-primary btn-block" onclick="launchRinsing(true);" disabled>Relancer un rinsage</button>
			</div>
			<div class="col-md-2">
				<button id="btn-exit" type="button" class="btn btn-danger btn-block" onclick="location.href='<?php echo $this->url('operator')?>'">Annuler</button>
			</div>
		</div>
		<script type="text/javascript">
				var value1 = 0;
				var value2 = 0;
				var value3 = 100;
				var rinsed = 0;
				var started = false;

				var timerAnim; // instance of timer used by moveProgressBar
				var frequency = 1000; // value of interval (in ms)

				function moveProgressBar()
				{
					timerAnim = window.setInterval(function(){animProgressBar();}, frequency);
				}

				function	stopProgressBar()
				{
					window.clearInterval(timerAnim);
				}

				function	animProgressBar()
				{
	            	$.ajax({
	              		type: "POST",
	              		url: "<?php echo $this->url('inject', array('action'=>'agetrinsingprogress'))?>",
	              		dataType: "json",
	              		data: {}
	            	}).done(function (result) {
						if(Number(result.progress) <= 50)
						{
							value2 = result.progress * 2;
							value3 = 100 - result.progress * 2;
						}
						else
						{
							value1 = (result.progress - 50) * 2;
							value2 = 100 - (result.progress - 50) * 2;
						}
						$("#rinsing-progress-1").css('width', value1+'%');
						$("#rinsing-progress-2").css('width', value2+'%');
						$("#rinsing-progress-3").css('width', value3+'%');

						if(value1 >= 100)
						{
							stopProgressBar();
							$("#rinsing-progress-1").css('width', '100%');
							$("#rinsing-progress-2").css('width', '0%');
							$("#rinsing-progress-3").css('width', '0%');
							$('#statut-block').removeClass('panel-info panel-success panel-warning').addClass('panel-success');
							$("#rinsing-confirm").removeAttr('disabled');
							$('#rinsing-statut').html('Rinçage terminé ! Appuyez sur le bouton "Lancer le rinçage" pour relancer un rinçage');
							rinsed = 1;
							started = false;
							checkEnableNext();
						}
					});
				}

				function launchRinsing(relaunch)
				{
					$("#rinsing-confirm").attr('disabled', 1);
					$('#statut-block').removeClass('panel-danger panel-success panel-warning').addClass('panel-warning');

					if (relaunch === true) {
						$('#rinsing-statut').html('Nouveau rinçage en cours...');
						value1 = 0;
						value2 = 0;
						value3 = 100;
						var started = false;
					} else {
						$('#collapseOne').collapse('toggle');
						$('#rinsing-statut').html('Rinçage en cours...');
					}

					$.ajax({
		            	type: "POST",
		            	url: "<?php echo $this->url('inject', array('action'=>'alaunchrinsing'))?>",
		            	dataType: "json",
		            	data: {}
					}).done(function (result) {
						if (result.error === false) {
							started = true;
							$('#btn-play').attr('disabled', 1);
							$('#btn-pause').removeAttr('disabled');
							moveProgressBar();
						}				            
		            });
				}

				function	pauseRinsing()
				{
					$('#btn-pause').attr('disabled', 1);
					$('#btn-play').removeAttr('disabled');
					$.ajax({
		            	type: "POST",
		            	url: "<?php echo $this->url('inject', array('action'=>'apauseinjection'))?>",
		            	dataType: "json",
		            	data: {}
		            });
					stopProgressBar();
				}

				function	playRinsing()
				{
					$('#btn-play').attr('disabled', 1);
					$('#btn-pause').removeAttr('disabled');
		          	$.ajax({
		            	type: "POST",
		            	url: "<?php echo $this->url('inject', array('action'=>'aplayinjection'))?>",
		            	dataType: "json",
		            	data: {}
		            });
					moveProgressBar();
				}

		        function sendSpeedInjection(speed)
		        {
					$.ajax({
		           		type: "POST",
		           		url: "<?php echo $this->url('inject', array('action'=>'aspeedinjection'))?>",
		           		dataType: "json",
		          		data: {speed : speed}
		          	});
		        }
		
				function	checkEnableNext()
				{
					if(rinsed == 1)
					{
						$("#btn-relaunch").removeAttr('disabled');
						$("#btn-next").removeAttr('disabled');
					}
				}

				$(function(){
					$('#debit-controller').bootstrapSlider({
						formatter: function(value) {
							return value / 10.0;
						}
					})
					.on("slide", function(slideEvt) {
						$("#debitVal").val(slideEvt.value / 10.0);
					})
					.on("change", function(slideEvt) {
						$("#debitVal").val(slideEvt.value.newValue / 10.0);
					})
					.on('slideStart', function() {
						if (started === true) {
							pauseRinsing();
						}
					})
					.on('slideStop', function(slideEvt) {
						sendSpeedInjection(slideEvt.value);
					});
				});
			</script>
	</div>
</div>
