<?php //TODO Trad high prio ?>
<ol class="breadcrumb">
	<li><a href="<?php echo $this->url('operator')?>"><span class="glyphicon glyphicon-home"></span> <?php echo $this->translate('Operator dashboard')?></a></li>
	<li><?php echo $this->translate('Injection')?></li>
	<li class="active"><?php echo $this->translate('Sample')?></li>
</ol>
<div class="row">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<?php echo $this->translate('Sample')?>
		</div>
		<div class="panel-body">
			<div class="panel-group" id="accordion">
				<div class="panel panel-info">
					<div class="panel-heading">
						<div class="panel-title">
							<a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"><?php echo $this->translate("Patient's data")?><span id="patientResume"></span></a>
						</div>
					</div>
					<div id="collapseOne" class="panel-collapse collapse in">
						<div class="panel-body">
							<div class="row">
								<div class="col-sm-2"><?php echo $this->translate('Lastname')?></div>
								<div class="col-sm-2"><input id="lastname" type="text" value="<?php echo $patient['lastname']?>" class="form-control" autocomplete="off" maxlength="100" disabled/></div>
								<div class="col-sm-2"><?php echo $this->translate('Firstname')?></div>
								<div class="col-sm-2"><input id="firstname" type="text" value="<?php echo $patient['firstname']?>" class="form-control" autocomplete="off" maxlength="100" disabled/></div>
								<div class="col-sm-2"><?php echo $this->translate('Activity to inject')?></div>
								<div class="col-sm-2">
									<div class="input-group">
										<input id="activity" type="number" value="<?php echo $injection['activity']?>" class="form-control" autocomplete="off" disabled/>
										<span class="input-group-addon"><?php echo $unit;?></span>
									</div>
								</div>
							</div>
							<div class="row" style="margin-top: 10px;">
								<div class="col-md-2 col-md-offset-5">
									<button type="button" class="btn btn-primary btn-block" id="dilution-confirm" onclick="launchSampling()"><?php echo $this->translate('Validation')?></button>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="panel panel-danger" id="statut-block">
				<div class="panel-heading">
					<?php echo $this->translate('Sample progression')?>
				</div>
				<div class="panel-body">
					<p><strong><?php echo $this->translate('Status')?> : </strong> <span id="dilution-statut"><?php echo $this->translate("Waiting for patient's datas validation...")?></span></p>
					<div class="row">
						<div class="col-md-12">
							<div class="progress progress-striped active">
								<div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%" id="dilution-progress">
									<span class="sr-only">0% Complete</span>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-2"><p>Activité prélevée</p></div>
				<div class="col-sm-2"><div class="input-group"><input type="number" id="val-add" value="0" class="form-control" autocomplete="off" disabled/><span class="input-group-addon"><?php echo $unit;?></span></div></div>
				<div class="col-sm-2"><p>Activité restante</p></div>
				<div class="col-sm-2"><div class="input-group"><input type="number" id="val-left" value="500" class="form-control" autocomplete="off" disabled/><span class="input-group-addon"><?php echo $unit;?></span></div></div>
				<div class="col-sm-2"><p>Activité demandée</p></div>
				<div class="col-sm-2"><div class="input-group"><input type="number" id="val-asked" value="<?php echo $injection['activity']?>" class="form-control" autocomplete="off" disabled/><span class="input-group-addon"><?php echo $unit;?></span></div></div>
			</div>
			<div class="row" style="margin-top: 10px;">
				<div class="col-md-2 col-md-offset-3">
					<button id="btn-next" type="button" class="btn btn-success btn-block" onclick="gotonext()" disabled><?php echo $this->translate('Next')?></button>
				</div>
				<div class="col-md-2">
					<button id="btn-add-activity" class="btn btn-primary btn-block" disabled><?php echo $this->translate("Adjust");?></button>
				</div>
				<div class="col-md-2">
					<button id="btn-exit" type="button" class="btn btn-danger btn-block" onclick="location.href='<?php echo $this->url('operator')?>'"><?php echo $this->translate('Abort')?></button>
				</div>
			</div>
			<script type="text/javascript">
					var value = 0; // real sampled activity value
					var rate = 0; // rate (in %)
					var animstep = 1; // internal value, used as mockup to simulate "life" between two reads on the automate
					var initial = 0; // tag: 0 = sample is not at precalculated value; 1 = sample is _OR_ was at precalculated value
  
					function moveProgressBar(asked)
					{
						lockui();
						$.ajax({
              				type: "POST",
              				url: "<?php echo $this->url('inject', array('action'=>'agetsamplingprogress'))?>",
              				dataType: "json",
              				data: {}
            			}).done(function (result) {
							animProgressBar(result.progress);
							if (result.progress == 100)
							{
		            			$.ajax({
  	            					type: "POST",
    	        					url: "<?php echo $this->url('inject', array('action'=>'agetsamplingactivity'))?>",
      	        					dataType: "json",
        	      					data: {}
  		      	    			}).done(function (result) {
									$("#val-add").val(result.activity)
									animstep = result.activity;
									animProgressBar(asked);
									//?????????????What ?
								});
							}
							else
							{
								window.setTimeout(function(){ moveProgressBar(asked); }, 2000);
							}
						});					
					}

					function	animProgressBar(progress)
					{
						$("#dilution-progress").css('width', progress+'%');
						if (progress == 100)
						{
							$('#statut-block').removeClass('panel-info panel-success panel-warning').addClass('panel-success');
							$('#dilution-statut').html('Prélèvement terminé !');
							initial = 1;
							unlockui();
						}
					}

					function launchSampling()
					{
						lockui();
						$("#dilution-confirm").attr('disabled', 1);
						$('#statut-block').removeClass('panel-danger panel-success panel-warning').addClass('panel-warning');
						$('#collapseOne').collapse('toggle');
						$('#dilution-statut').html('Prélèvement en cours...');
						$("#val-asked").val(<?php echo $injection['activity']?>);

						var resume = ' : ' + $('#firstname').val() + ' ' + $('#lastname').val() + ', <?php echo $this->translate('Activity to inject')?> : ' + $('#activity').val() + ' <?php echo $unit;?>';
						$('#patientResume').html(resume);
						
						$.ajax({
              				type: "POST",
              				url: "<?php echo $this->url('inject', array('action'=>'alaunchsampling'))?>",
              				dataType: "json",
              				data: {}
            			});

						loadActivityData();
						moveProgressBar(<?php echo $injection['activity']?>);
					}

					function	adjustActivity()
					{
						$('#statut-block').removeClass('panel-danger panel-success panel-warning').addClass('panel-warning');
						$.ajax({
              				type: "POST",
              				url: "<?php echo $this->url('inject', array('action'=>'aadjustsampling'))?>",
              				dataType: "json",
              				data: {}
            			}).done(function(){
							moveProgressBar(<?php echo $injection['activity']?>);
						});
					}

					function  loadActivityData()
					{
						$.ajax({
							type: "GET",
							url: "<?php echo $this->url('setup', array('action'=>'agetavailableactivity'))?>",
							dataType: "json"
						}).done(function(result) {
							var data = result;
							$("#val-left").val(data.activity);
						});

						setTimeout(function() {
							loadActivityData();
						}, 15000);
					}


					function	lockui()
					{
						$("#btn-add-activity").attr('disabled', 1);
						$("#btn-remove-activity").attr('disabled', 1);
						$("#btn-next").attr('disabled', 1);
						$("#btn-exit").attr('disabled', 1);
					}
	
					function	unlockui()
					{
						$("#btn-add-activity").removeAttr('disabled');
						$("#btn-remove-activity").removeAttr('disabled');
						$("#btn-exit").removeAttr('disabled');
						if(initial == 1)
						{
							$("#btn-next").removeAttr('disabled');
						}
					}
	
					function	gotonext()
					{
						var postdata = {
							activity: $('#val-add').val()
						};
						$.ajax({
							type: "POST",
							url: "<?php echo $this->url('inject', array('action'=>'aupdateactivity'));?>",
							dataType: "json",
							data: postdata,
						}).done(function(){
							location.href='<?php echo $this->url('inject', array('action'=>'injection'))?>';
						});
					}
	
					$(function(){
						// listener on buttons
						$("#btn-add-activity").click(function(){adjustActivity();});
					});
			</script>
		</div>
	</div>
</div>
