<ol class="breadcrumb">
	<li><span class=" glyphicon glyphicon-home"></span> Gestion du compte</li>
	<li class="active">Modification du mot de passe</li>
</ol>
<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">
		&times;
	</button>
	<ul><li>')
	->setMessageSeparatorString('</li><li>')
	->setMessageCloseString('</li></ul></div>');

echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<span class="glyphicon glyphicon-edit"></span> Modification du mot de passe
			</div>
			<div class="panel-body">
				<form class="form-horizontal" role="form" action="<?php echo $this->url('log', array('action'=>'changepwd'))?>" method="POST">
					<div class="row">
						<div class="col-md-12">
							<div class="form-group">
								<label for="input3" class="col-sm-4 control-label"><?php echo $this->translate('Old password')?></label>
								<div class="col-sm-8">
									<input type="password" class="form-control input-sm" id="oldpwd" name="oldpwd" autocomplete="off" placeholder="" />
								</div>
							</div>
							<div class="form-group">
								<label for="input3" class="col-sm-4 control-label"><?php echo $this->translate('New password')?></label>
								<div class="col-sm-8">
									<input type="password" class="form-control input-sm" id="newpwd" name="newpwd" autocomplete="off" placeholder="" />
								</div>
							</div>
							<div class="form-group">
								<label for="input3" class="col-sm-4 control-label"><?php echo $this->translate('Confirm password')?></label>
								<div class="col-sm-8">
									<input type="password" class="form-control input-sm" id="confpwd" name="confpwd" autocomplete="off" placeholder="" />
								</div>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-2 col-md-offset-4">
							<input type="submit" class="btn btn-success btn-block" value="<?php echo $this->translate('Confirm')?>"/>
						</div>
						<div class="col-md-2">
							<button type="button" class="btn btn-danger btn-block" onClick="location.href='<?php echo $this->url('operator')?>'"><?php echo $this->translate('Abort')?></button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>