<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">
		&times;
	</button>
	<ul><li>')
		->setMessageSeparatorString('</li><li>')
		->setMessageCloseString('</li></ul></div>');
echo $flash->render('error',	array('alert', 'alert-dismissable', 'alert-danger'));
echo $flash->render('info',		array('alert', 'alert-dismissable', 'alert-info'));
echo $flash->render('default',	array('alert', 'alert-dismissable', 'alert-warning'));
echo $flash->render('success',	array('alert', 'alert-dismissable', 'alert-success'));

if (isset($action) && $action === 'logindone') {
?>
<div class="col-md-4 col-md-offset-4" id="signinform">
	<h2 class="form-signin-heading text-center"><?php echo $this->translate("Enter your password")?></h2>
	<div class="well">
		<form class="form-signin" id="passwordSignIn" name="passwordSignIn" role="form" method="post" action="<?php echo $this->url('log', array('action'=>'signin')); ?>" autocomplete="off">
			<input type="hidden" name="action" value="password" />
			<p class="text-center"><strong><?php echo $login; ?></strong></p>
			<div class="form-group">
				<input id="password" name="password" type="password" class="form-control" placeholder="<?php echo $this->translate("Password")?>" maxlength="100" autocomplete="off" required />
			</div>
			<button class="btn btn-lg btn-primary btn-block" type="submit"><?php echo $this->translate("Sign in")?></button>
			<p class="text-right" style="margin-top: 5px;">
				<a href="<?php echo $this->url('log', array('action'=>'logout')); ?>"><?php echo $this->translate("Change user")?></a>
			</p>
		</form>
	</div>
</div>
<script>
function submitSignIn() {
	console.log("submitSignIn Password");
	$("#passwordSignIn").submit();
}
</script>
<?php } else { ?>
<div class="col-md-4 col-md-offset-4" id="signinform">
	<h2 class="form-signin-heading text-center"><?php echo $this->translate("Please sign in")?></h2>
	<div class="well">
		<form class="form-signin" id="loginSignIn" name="loginSignIn" role="form" method="post" action="<?php echo $this->url('log')?>" autocomplete="off">
			<input type="hidden" name="action" value="login" />
			<div class="form-group">
				<input id="login" name="login" type="text" class="form-control" placeholder="<?php echo $this->translate("Login")?>" autocomplete="off" maxlength="100" required autofocus />
			</div>
			<button class="btn btn-lg btn-primary btn-block" type="submit"><?php echo $this->translate("Next")?></button>
		</form>
	</div>
</div>
<script>
function submitSignIn() {
	console.log("submitSignIn Login");	
	$("#loginSignIn").submit();
}
</script>
<?php } ?>
