<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">
		&times;
	</button>
	<ul><li>')
		->setMessageSeparatorString('</li><li>')
		->setMessageCloseString('</li></ul></div>');
echo $flash->render('error',	array('alert', 'alert-dismissable', 'alert-danger'));
echo $flash->render('info',		array('alert', 'alert-dismissable', 'alert-info'));
echo $flash->render('default',	array('alert', 'alert-dismissable', 'alert-warning'));
echo $flash->render('success',	array('alert', 'alert-dismissable', 'alert-success'));
?>
<form class="form-signin" role="form" method="post" action="<?php echo $this->url('log', array('action'=>'signin'))?>">
	<h2 class="form-signin-heading"><?php echo $this->translate("Please sign in")?></h2>
	<input id="login" name="login" type="text" class="form-control" placeholder="<?php echo $this->translate("Login")?>" required autofocus />
	<input id="password" name="password" type="password" class="form-control" placeholder="<?php echo $this->translate("Password")?>" required />
	<button class="btn btn-lg btn-primary btn-block" type="submit"><?php echo $this->translate("Sign in")?></button>
</form>