<div class="jumbotron">
	<h1><?php echo sprintf($this->translate('S.A.M.I. v %s'), $this->version) ?></h1>
	<p><?php echo sprintf($this->translate('Loading...')) ?> <span id="loading-success" style="display:none"><?php echo sprintf($this->translate('Done')) ?></span></p>
	<div class="progress progress-striped active">
		<div id="loading-progress" class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%"></div>
	</div>
</div>

<script type="text/javascript">
	var value = 0;
	function moveProgressBar()
	{
		if(value < 100)
		{
			value += 10;
			$("#loading-progress").css('width', value+'%');
			window.setTimeout(function(){moveProgressBar();}, 500);
		}
		else
		{
			$("#loading-progress").addClass("progress-bar-success");
			$("#loading-success").show();
			window.setTimeout(function(){gotoindex();}, 2000);
		}
	}
	function gotoindex()
	{
		$(location).attr('href',<?php echo $this->url('log')?>);
	}

	$(function(){
		window.setTimeout(function(){moveProgressBar();}, 500);
	});

</script>