<div class="jumbotron">
	<h1><?php echo sprintf($this->translate('S.A.M.I. v %s'), $this->version) ?></h1>
	<p><?php echo sprintf($this->translate('Loading...')) ?> 
		<span id="loading-success" style="display:none"><?php echo sprintf($this->translate('Done')); ?></span>
		<span id="loading-error" style="display:none"></span>
	</p>
	<div class="progress progress-striped active">
		<div id="loading-progress" class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%"></div>
	</div>
</div>

<script type="text/javascript">
	var value = 0;
	var nbConnectionAttempt = 0;
	var nbConnectionTry = 5;
	
	function moveProgressBar(valToAdd, valueToSet)
	{
		if (typeof(valToAdd) !== 'undefined') {
			value = value + valToAdd;
		}
		if (typeof(valToAdd) !== 'undefined' && valToAdd == 0) {
			value = valueToSet;
		}
		
		if(value < 100) {
			$("#loading-progress").css('width', value+'%');
		} else {
			$.ajax({
				url: "<?php echo $this->url('initsd', array())?>",
			}).done(function(result){
				if (result.error === false) {
					$("#loading-progress").css('width', '100%');
					$("#loading-progress").addClass("progress-bar-success");
					$("#loading-success").show();
					window.setTimeout(function(){gotoindex();}, 1000);
				}
				else {
					$("#loading-progress").addClass("progress-bar-danger");
					$("#loading-error").html("<?php echo sprintf($this->translate('An error occured during setup. Please retry.')); ?><br />" + result.errorMessage);
					$("#loading-error").show();
				}
			});
		}
	}
	
	function gotoindex() {
		$(location).attr('href',<?php echo $this->url('log'); ?>);
	}

	/*
	 * Vérification de la mise sous tension de l'automate STEP 1
	 */
	function initping() {
		if (nbConnectionAttempt >= nbConnectionTry) {
			$("#loading-progress").removeClass("progress-bar-warning");
			$("#loading-progress").addClass("progress-bar-danger");
			$("#loading-error").html("<?php echo sprintf($this->translate('An error occured during setup. Robot is not responding. Please retry or restart system.')); ?>");
			$("#loading-error").show();
			return false;
		}
		
		$.ajax({
			url: "<?php echo $this->url('initping', array()); ?>",
		}).done(function(result){
			if (result.active === false) {
				nbConnectionAttempt++;
				moveProgressBar(0, 10);
				$("#loading-progress").removeClass("progress-bar-warning");
				$("#loading-progress").addClass("progress-bar-warning");
				$("#loading-error").html(nbConnectionAttempt + 1 + "/" + nbConnectionTry + " <?php echo sprintf($this->translate('connections attempt(s)')); ?>");
				$("#loading-error").show();
				//GOTO STEP 1 LOOP
				initping();
			} else {
				if (result.error === true) {
					$("#loading-progress").removeClass("progress-bar-warning");
					$("#loading-progress").addClass("progress-bar-danger");
					$("#loading-error").html("<?php echo $this->translate('An error occured during setup. Robot is returning an error at starting : &laquo;'); ?>" + result.errorMessage + '&raquo;');
					$("#loading-error").show();
					return false;
				} else {
					$("#loading-progress").removeClass("progress-bar-warning");
					$("#loading-error").hide();
					moveProgressBar(0, 15);
					//GOTO STEP 2
					initmu();
				}
			}
		});
	}

	/*
	 * Chargement de l'unité de mesure STEP 2
	 */
	function initmu() {
		$.ajax({
			url: "<?php echo $this->url('initmu', array()); ?>",
		}).done(function(result){
			if (result.error === false) {
				moveProgressBar(15);
				//GOTO STEP 3
				initrn();
			}
			else {
				$("#loading-progress").addClass("progress-bar-danger");
				$("#loading-error").html("<?php echo sprintf($this->translate('Loading of measure unit failed.')); ?> : " + result.errorMessage);
				$("#loading-error").show();
			}
		});
	}
	
	/*
	 * Chargement des radionucléides STEP 3
	 */
	function initrn() {
		$.ajax({
			url: "<?php echo $this->url('initrn', array()); ?>",
		}).done(function(result){
			if (result.error === false) {
				moveProgressBar(15);
				//GOTO STEP 4
				inithml();
			}
			else {
				$("#loading-progress").addClass("progress-bar-danger");
				$("#loading-error").html("<?php echo sprintf($this->translate('Loading of radionuclides failed.')); ?> : " + result.errorMessage);
				$("#loading-error").show();
			}
		});
	}

	/*
	 * Vérification et chargement du médicament STEP 4
	 */
	 function inithml() {
		$.ajax({
			url: "<?php echo $this->url('inithml', array()); ?>",
		}).done(function(result){
			if (result.error === false) {
				moveProgressBar(15);
				//GOTO STEP 5
				initsks();
			}
			else {
				$("#loading-progress").addClass("progress-bar-danger");
				$("#loading-error").html("<?php echo sprintf($this->translate('Check of loaded drug failed.')); ?> : " + result.errorMessage);
				$("#loading-error").show();
			}
		});
	}

	/*
	 * Vérification et chargement du médicament STEP 5
	 */
	function initsks() {
		$.ajax({
			url: "<?php echo $this->url('initsks', array()); ?>",
		}).done(function(result){
			if (result.error === false) {
				moveProgressBar(15);
				//GOTO STEP 6
				initlks();
			}
			else {
				$("#loading-progress").addClass("progress-bar-danger");
				$("#loading-error").html("<?php echo sprintf($this->translate('Check of kit source serial failed.')); ?> : " + result.errorMessage);
				$("#loading-error").show();
			}
		});
	}

	/*
	 * Vérification et chargement du médicament STEP 5
	 */
	function initlks() {
		$.ajax({
			url: "<?php echo $this->url('initlks', array()); ?>",
		}).done(function(result){
			if (result.error === false) {
				moveProgressBar(15);
				//GOTO STEP 6
				initsp();
			}
			else {
				$("#loading-progress").addClass("progress-bar-danger");
				$("#loading-error").html("<?php echo sprintf($this->translate('Check of kit source loading failed.')); ?> : " + result.errorMessage);
				$("#loading-error").show();
			}
		});
	}

	/*
	 * Vérification du point de démarrage STEP 7
	 * PROBABLEMT OBSOLETE
	 */
	function initsp() {
		$.ajax({
			url: "<?php echo $this->url('initsp', array()); ?>",
		}).done(function(result){
			if (result.error === false) {
				moveProgressBar(10);
			}
			else {
				//TODO Rajouter message d'erreur
			}
		});
	}

	$(function() {
		//GOTO STEP 1
		initping();
	});

</script>