<?php //TODO Trad low prio ?>
<div class="panel panel-primary">
	<div class="panel-heading">
		Imported datas
	</div>
	<div class="panel-body">
		<pre>
			<?php var_dump($importer->getHeader())?>
			<?php var_dump($importer->getDataStruct())?>
			<?php var_dump($importer->getPatients())?>
			<?php var_dump($importer->getChecksum())?>
		</pre>
	</div>
</div>
<div class="panel panel-primary">
	<div class="panel-heading">
		Checksum control
	</div>
	<div class="panel-body">
		<pre>
<?php var_dump(md5('file_version,1
compatibility_file_version,1
date,2013/05/15
injector_id,1283485
Type,Time,Activity,DoseStatus,UniqueID,VialID,PatientID,PatientName,Gender,BirthDate,Age,Weight,Height,PatientType,DoctorName
Infuse,11:30,177,,64551,,MR103265,"GAUVIN,Raymond",M,1931/02/09,82,59,167,EXTERNE,310134
checksum,'));?>
<?php var_dump($importer->getChecksum())?>
		</pre>
	</div>
</div>