<?php for($i = 0; $i < 30; $i += 3) {?>
<div class="row">
	<div class="col-sm-6">
		<div id="barcode-<?php echo $i?>"></div>
	</div>
	<div class="col-sm-6">
		<div id="barcode-<?php echo $i+1?>"></div>
	</div>
</div>
<script type="text/javascript">
	$(function(){
		<?php for($k = 0; $k < 2; $k++) {
			$value = '';
			$a_z = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
			for($r = 0; $r < 35; $r++){
				$int = rand(0,61);
				$rand_char = $a_z[$int];
				$value .= $rand_char;
			}
			?>
			$("#barcode-<?php echo $i+$k?>").barcode("<?php echo $value ?>", "code128");
		<?php } ?>
	});
</script>
<?php } ?>