<ol class="breadcrumb">
	<li><a href="<?php echo $this->url('operator')?>"><span class=" glyphicon glyphicon-home"></span> <?php echo $this->translate('Operator dashboard')?></a></li>
	<li class="active"><?php echo $this->translate('Patients overview')?></li>
</ol>
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<span class="glyphicon glyphicon-list"></span> <?php echo $this->translate('Patients overview')?>
			</div>
			<div class="panel-body">
				<table class="table table-condensed table-hover">
					<thead>
						<tr>
							<th><?php echo $this->translate('Patient name')?></th>
							<th><?php echo $this->translate('Injection date')?></th>
							<th><?php echo $this->translate('Injected activity')?></th>
							<th><?php echo $this->translate('Operator name')?></th>
							<th></th>
						</tr>
					</thead>
					<tbody>
					<?php foreach($injections as $injection) { ?>
						<tr>
							<td><?php echo strtoupper($injection->patientlastname)?> <?php echo ucfirst(strtolower($injection->patientfirstname))?></td>
							<td><?php echo $injection->injectiontime?></td>
							<td><?php echo $injection->activity?> <?php echo $unit?></td>
							<td><?php echo strtoupper($injection->operatorlastname)?> <?php echo ucfirst(strtolower($injection->operatorfirstname))?></td>
							<td><button class="btn btn-primary" onclick="printSticker();" title="<?php echo $this->translate('Send to printer'); ?>"><i class="glyphicon glyphicon-print"></i></button></td>
						</tr>
					<?php } ?>
					</tbody>
				</table>
			</div>
		</div>
		<div class="row">
			<div class="col-sm-2"></div>
			<div class="col-sm-4">
				<a href="<?php echo $this->url('auth', array('action'=>'confirmauth')); ?>" class="btn btn-primary btn-block"><?php echo $this->translate('Launch another injection'); ?></a>
			</div>
			<div class="col-sm-4">
				<a href="<?php echo $this->url('inject', array('action'=>'endinject')); ?>" class="btn btn-primary btn-block"><?php echo $this->translate('End of injections'); ?></a>
			</div>
			<div class="col-sm-2"></div>
		</div>
	</div>
</div>
<div class="print-container" id="sticker" style="margin-top: 10px;">
	<div class="content">
		<div class="row">
    		<div class="col-xs-2 no-padding"><span style="font-size: 2.6em; font-weight: normal; line-height: 0.8em;">&#9762;</span></div>
    		<div class="col-xs-6 no-padding" style="margin-top: 1mm;"><?php echo date('d/m/Y'); ?></div>
    		<div class="col-xs-4 no-padding" style="margin-top: 1mm;" id="injectionHour">HH:MM</div>
  		</div>
		<div class="row">
			<div class="col-xs-10 col-xs-offset-2 no-padding" id="drugName">drugname</div>
		</div>
		<div class="row">
			<div class="col-xs-7 col-xs-offset-5 no-padding"><span  id="activity">xx</span><?php echo ' ' . $unit; ?></div>
		</div>
		<div class="row spacer"></div>
		<div class="row">
			<div class="col-xs-5 no-padding" id="code">code</div>
			<div class="col-xs-7 no-padding"><?php echo $this->translate('Serial : '); ?><span id="batchnum">batchnum</span></div>
		</div>
		<div class="row spacer"></div>
		<div class="row">
			<div class="col-xs-5 no-padding">N&ordm; <span id="uniqueId">uniqueId</span></div>
			<div class="col-xs-7 no-padding" id="operatorName"></div>
		</div>
	</div>
</div>
<script type="text/javascript">
function	printSticker() {

	// Récupération des infos de l'injection et du patient	
	$.ajax({
		type: "POST",
		url: "<?php echo $this->url('setup', array('action'=>'agetavailableactivityat')); ?>",
		dataType: "json",
		data: {wantedat : "DT#" + $("#activityattime").val().replace(" ", "-") + ":00"}
	}).done(function(result) {
		// Remplissage de l'etiquette
		$('#injectionHour').html();
		$('#drugName').html();
		$('#activity').html();
		$('#code').html();
		$('#batchnum').html();
		$('#uniqueId').html();
		$('#operatorName').html();
		
		//Impression de l'etiquette
		printElement(document.getElementById("sticker"));
		window.print();
	});
}
</script>