<ol class="breadcrumb">
	<li class="active"><span class=" glyphicon glyphicon-home"></span> <?php echo $this->translate('Operator dashboard')?></li>
</ol>
<div class="well">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<div class="list-group">
				<?php if($step->fileloaded) {?>
				<a href="#" class="list-group-item list-group-item-success">
					<span class="badge badge-success"><span class="glyphicon glyphicon-ok"></span></span>
				<?php } else { ?>
				<a href="<?php echo $this->url('setup', array('action'=>'loadpatient'))?>" class="list-group-item list-group-item-danger">
					<span class="badge badge-danger">!</span>
				<?php } ?>
					<span class="glyphicon glyphicon-import"></span>
					<?php echo $this->translate("Transfering patient's data to robot")?>
				</a>

				<?php if($step->drugspecified) {?>
				<a href="#" class="list-group-item list-group-item-success">
					<span class="badge badge-success"><span class="glyphicon glyphicon-ok"></span></span>
				<?php } else { ?>
				<a href="<?php echo $this->url('setup', array('action'=>'drug'))?>" class="list-group-item list-group-item-danger">
					<span class="badge badge-danger">!</span>
				<?php } ?>
					<span class="glyphicon glyphicon-file"></span>
					<?php echo $this->translate("Filling drug's informations")?>
				</a>

				<?php if($needScan){?>
				<?php if($step->sourcekitscanned) {?>
				<a href="#" class="list-group-item list-group-item-success">
					<span class="badge badge-success"><span class="glyphicon glyphicon-ok"></span></span>
				<?php } else { ?>
				<a href="<?php echo $this->url('setup', array('action'=>'scankitsource'))?>" class="list-group-item list-group-item-danger">
					<span class="badge badge-danger">!</span>
				<?php } ?>
					<span class="glyphicon glyphicon-barcode"></span>
					<?php echo $this->translate('Scan source kit barcode')?>
				</a>
				<?php } ?>

				<?php if($step->sourcekitloaded) {?>
				<a href="#" class="list-group-item list-group-item-success">
					<span class="badge badge-success"><span class="glyphicon glyphicon-ok"></span></span>
				<?php } else { ?>
				<a href="<?php echo $this->url('setup', array('action'=>'loadkitsource'))?>" class="list-group-item list-group-item-danger">
					<span class="badge badge-danger" title="<?php echo $this->translate('Action required')?>">!</span>
				<?php } ?>
					<span class="glyphicon glyphicon-download"></span>
					<?php echo $this->translate('Loading Source kit & Source')?>
				</a>

				<?php if($canInject) { ?>
				<a href="<?php echo $this->url('auth', array('action'=>'confirmauth'))?>" class="list-group-item active">
				<?php } else {?>
				<a href="#" class="list-group-item">
					<span class="badge"><span class="glyphicon glyphicon-lock"></span></span>
				<?php } ?>
					<span class="glyphicon glyphicon-user"></span>
					<?php echo $this->translate('Injection - Operator Authentification')?>
				</a>

				<a href="<?php echo $this->url('bufferspace', array('action'=>'patientlist'))?>" class="list-group-item">
					<span class="glyphicon glyphicon-list"></span>
					<?php echo $this->translate('List of patients injected')?>
				</a>

				<?php if($canUnload) {?>
				<a href="<?php echo $this->url('inject', array('action'=>'unload'))?>" class="list-group-item">
					<span class="badge" title="<?php echo $this->translate('Action required')?>"><span class="glyphicon glyphicon-exclamation-sign"></span></span>
				<?php } else { ?>
				<a href="#" class="list-group-item">
					<span class="badge"><span class="glyphicon glyphicon-lock"></span></span>
				<?php } ?>
					<span class="glyphicon glyphicon-upload"></span>
					<?php echo $this->translate('Unloading')?>
				</a>

				<?php if($canExport) {?>
				<a href="<?php echo $this->url('exportbuffer', array('action'=>'index'))?>" class="list-group-item">
				<?php } else {?>
				<a href="#" class="list-group-item">
					<span class="badge"><span class="glyphicon glyphicon-lock"></span></span>
				<?php } ?>
					<span class="glyphicon glyphicon-export"></span>
					<?php echo $this->translate('Transferting patient\'s data to software')?>
				</a>
			</div>
		</div>
	</div>
</div>
