<?php
use Logger\Model\InputDrug;
?>
<div id="mainContent">
<ol class="breadcrumb">
	<li class="active"><span class=" glyphicon glyphicon-home"></span> <?php echo $this->translate('Operator dashboard')?></li>
</ol>
<?php if ($canWork === false) { ?>
<div class="alert alert-danger" role="alert">
	<strong><i class="glyphicon glyphicon-exclamation-sign"></i> <?php echo $this->translate('Warning');?> <i class="glyphicon glyphicon-exclamation-sign"></i></strong> 
	<p>Une erreur est en cours sur le système veuillez la corriger.</p>
</div>
<?php if ($showGloballErrorMessage === true) { ?>
<div class="well">
	<?php echo $globalErrorMessage; ?>
</div>
<?php } ?>
<p class="text-center">
	<button class="btn btn-primary" onClick="window.location.reload()"><?php echo $this->translate('I\'ve fixed it, reload!')?></button>
</p>
<?php } else if ($hasExams === false) { ?>
<div class="alert alert-danger" role="alert">
	<strong><i class="glyphicon glyphicon-exclamation-sign"></i> <?php echo $this->translate('Warning');?> <i class="glyphicon glyphicon-exclamation-sign"></i></strong> 
	<p><?php echo sprintf('%s <a href="' . $this->url("examination", array("action" => "add")) . '" class="alert-link">%s</a> %s', $this->translate('No exams found in database. Please '), $this->translate('create an exam'), $this->translate(' to start injections.')); ?></p>
</div>
<?php } else { ?>
<div class="full-width-tabs">
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="tab-max-width active"><a href="#preparation" aria-controls="injection" role="tab" data-toggle="tab"><?php echo $this->translate("Preparation"); ?></a></li>
    <li role="presentation" class="tab-max-width"><a href="#injection" aria-controls="injection" role="tab" data-toggle="tab"><?php echo $this->translate("Injection"); ?></a></li>
    <li role="presentation" class="tab-max-width"><a href="#dechargement" aria-controls="dechargement" role="tab" data-toggle="tab"><?php echo $this->translate("Unload/Transfer"); ?></a></li>
  </ul>
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="preparation">
    	<div class="well">
			<div class="row">
				<div class="col-md-8 col-md-offset-2">
					<div class="list-group">
						<?php if ($step->fileloaded) { ?>
						<a href="#" class="list-group-item list-group-item-success">
							<span class="badge badge-success"><span class="glyphicon glyphicon-ok"></span></span>
							<span class="glyphicon glyphicon-import"></span>
							<?php echo $this->translate("Transfering patient's data to robot")?>
						</a>
						<?php } else { ?>
						<a href="<?php echo $this->url('setup', array('action'=>'loadpatient'))?>" class="list-group-item list-group-item-danger">
							<span class="badge badge-danger">!</span>
							<span class="glyphicon glyphicon-import"></span>
							<?php echo $this->translate("Transfering patient's data to robot"); ?>
						</a>
						<?php } ?>
		
						<?php if ($step->drugspecified) { ?>
						<a href="#" class="list-group-item list-group-item-success">
							<?php if (!$step->sourcekitloaded) { ?>
							<span id="removeDrugButton" class="badge badge-danger"><span class="glyphicon glyphicon-remove"></span></span>
							<?php } ?>
							<span class="badge badge-success"><span class="glyphicon glyphicon-ok"></span></span>
							<span class="glyphicon glyphicon-file"></span>
							<?php echo sprintf($this->translate("Receipted drug : <u>%s</u>"), $selectedDrugName); ?>
						</a>
						<?php } else { ?>
						<a href="<?php echo $this->url('setup', array('action'=>'drug'))?>" class="list-group-item list-group-item-danger">
							<span class="badge badge-danger">!</span>
							<span class="glyphicon glyphicon-file"></span>
							<?php echo $this->translate("Filling drug's informations")?>
						</a>
						<?php } ?>
		
						<?php if ($step->sourcekitscanned) { ?>
						<a href="#" class="list-group-item list-group-item-success">
							<?php if (!$step->sourcekitloaded) { ?>
							<span id="removeScanButton" class="badge badge-danger"><span class="glyphicon glyphicon-remove"></span></span>
							<?php } ?>
							<span class="badge badge-success"><span class="glyphicon glyphicon-ok"></span></span>
							<span class="glyphicon glyphicon-barcode"></span>
							<?php echo $this->translate('Scan source kit barcode')?>
						</a>
						<?php } else { ?>
						<a href="<?php echo $this->url('setup', array('action'=>'scankitsource'))?>" class="list-group-item list-group-item-danger">
							<span class="badge badge-danger">!</span>
							<span class="glyphicon glyphicon-barcode"></span>
							<?php echo $this->translate('Scan source kit barcode'); ?>
						</a>
						<?php } ?>
		
						<?php if ($step->sourcekitloaded) { ?>
						<a href="#" class="list-group-item list-group-item-success">
							<span class="badge badge-success"><span class="glyphicon glyphicon-ok"></span></span>
							<span class="glyphicon glyphicon-download"></span>
							<?php echo $this->translate('Loading Source kit & Source'); ?>
						</a>
						<?php } else if ($step->sourcekitscanned && $step->drugspecified) { ?>
						<a href="<?php echo $this->url('setup', array('action'=>'loadkitsource'))?>" class="list-group-item list-group-item-danger">
							<span class="badge badge-danger" title="<?php echo $this->translate('Action required')?>">!</span>
							<span class="glyphicon glyphicon-download"></span>
							<?php echo $this->translate('Loading Source kit & Source'); ?>
						</a>
						<?php } else { ?>
						<a href="#" class="list-group-item">
							<span class="glyphicon glyphicon-download"></span>
							<span class="badge"><span class="glyphicon glyphicon-lock"></span></span>
							<?php echo $this->translate('Loading Source kit & Source'); ?>
						</a>
						<?php } ?>
						<?php if ($step->vialcontrolled === false) { ?>
						<a href="#" class="list-group-item" id="btnCheckVial">
							<span class="fa fa-shield"></span>
							<?php echo $this->translate('Check vial'); ?>
						</a>
						<?php } else { ?>
						<a href="#" class="list-group-item list-group-item-success" id="btnVialResults">
							<span class="fa fa-shield"></span>
							<?php echo $this->translate('See vial check results'); ?>
						</a>
						<?php } ?>
						<a href="<?php echo $this->url('activimeter')?>" class="list-group-item">
							<span class="glyphicon glyphicon-dashboard"></span>
							<?php echo $this->translate('Activimeter'); ?>
						</a>
					</div>
				</div>
			</div>
		</div>
    </div>
    <div role="tabpanel" class="tab-pane" id="injection">
    	<div class="well">
			<div class="row">
				<div class="col-md-8 col-md-offset-2">
				<?php if ($canInject) { ?>
					<?php if ($step->fileloaded === false) { $cssClass = 'list-group-item-warning'; } else { $cssClass = 'active'; } ?>
					<a href="<?php echo $this->url('auth', array('action'=>'confirmauth'))?>" class="list-group-item active">
						<span class="glyphicon glyphicon-user"></span>
						<?php echo $this->translate('Injection - Operator Authentification'); ?>
					</a>
				<?php } else {?>
					<a href="#" class="list-group-item">
						<span class="badge"><span class="glyphicon glyphicon-lock"></span></span>
						<span class="glyphicon glyphicon-user"></span>
						<?php echo $this->translate('Injection - Operator Authentification'); ?>
					</a>
				<?php } ?>
					<a href="<?php echo $this->url('bufferspace', array('action'=>'patientlist')); ?>" class="list-group-item">
						<span class="glyphicon glyphicon-list"></span>
						<?php echo $this->translate('List of patients injected'); ?>
					</a>
				</div>
			</div>
		</div>
    </div>
    <div role="tabpanel" class="tab-pane" id="dechargement">
    	<div class="well">
			<div class="row">
				<div class="col-md-8 col-md-offset-2">
					<?php if ($canUnload) { ?>
					<a href="<?php echo $this->url('inject', array('action'=>'unload'))?>" class="list-group-item">
						<span class="badge" title="<?php echo $this->translate('Action required')?>"><span class="glyphicon glyphicon-exclamation-sign"></span></span>
						<span class="glyphicon glyphicon-upload"></span>
						<?php echo $this->translate('Unloading')?>
					</a>
					<?php } else { ?>
					<a href="#" class="list-group-item">
						<span class="badge"><span class="glyphicon glyphicon-lock"></span></span>
						<span class="glyphicon glyphicon-upload"></span>
						<?php echo $this->translate('Unloading')?>
					</a>
					<?php } ?>

					<?php if ($canExport) { ?>
					<a href="<?php echo $this->url('exportbuffer', array('action'=>'index'))?>" class="list-group-item">
						<span class="badge" title="<?php echo $this->translate('Action required')?>"><span class="glyphicon glyphicon-exclamation-sign"></span></span>
						<span class="glyphicon glyphicon-export"></span>
						<?php echo $this->translate('Transferting patient\'s data to software')?>
					</a>
					<?php } else { ?>
					<a href="#" class="list-group-item">
						<span class="badge"><span class="glyphicon glyphicon-lock"></span></span>
						<span class="glyphicon glyphicon-export"></span>
						<?php echo $this->translate('Transferting patient\'s data to software')?>
					</a>
					<?php } ?>
				</div>
			</div>
		</div>
    </div>
  </div>
</div>
</div>
<?php } ?>
<?php if ($this->partial === false && $canWork === true && $showGloballErrorMessage === false && $hasExams === true) { ?>
<div class="modal fade" id="confirmRemoveDrug" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title"><span class="glyphicon glyphicon-warning-sign"></span> <?php echo $this->translate('Remove receipted drug.');?></h4>
			</div>
			<div class="modal-body">
				<p><?php echo $this->translate("Are you sure to remove selected drug ?"); ?></p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-success" onclick="removeDrug();"><?php echo $this->translate('Confirm');?></button>
				<button type="button" class="btn btn-danger" data-dismiss="modal"><?php echo $this->translate('Cancel');?></button>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="confirmDilution" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title"><?php echo $this->translate('Launch dilution.');?></h4>
			</div>
			<div class="modal-body">
				<div id="msgDilution" style="display: none;">
					<p class="alert alert-info"><?php echo $this->translate("Do you want to launch the dilution ?"); ?></p>
				</div>
				<div id="dilutionProgress" style="display: none;">
					<h5><?php echo $this->translate("Dilution in progress"); ?></h5>
					<div>
						<div class="progress">
  							<div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
    						60%
  							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="modal-footer" id="dilutionFooterConfirm">
				<button type="button" class="btn btn-success" onclick="lauchDilution();"><?php echo $this->translate('Confirm');?></button>
				<button type="button" class="btn btn-danger" data-dismiss="modal"><?php echo $this->translate('Cancel');?></button>
			</div>
			<div class="modal-footer" id="dilutionFooterClose">
				<button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Close');?></button>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="checkVial" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static">
	<div class="modal-dialog">
		<div class="modal-content panel-primary" style="height: 100%;">
			<div class="modal-header panel-heading" style="border-top-left-radius: inherit; border-top-right-radius: inherit;">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 id="modalTitleLaunch" class="modal-title"><span class="glyphicon glyphicon-warning-sign"></span> <?php echo $this->translate('Launch a vial check process');?></h4>
				<h4 id="modalTitleConsult" class="modal-title"><span class="glyphicon glyphicon-info-sign"></span> <?php echo $this->translate('Vial check results');?></h4>
			</div>
			<div class="modal-body">
				<div id="checkVialConfirm" style="display: none;">
					<p><?php echo $this->translate("Do you want to launch a control on the vial ?"); ?></p>
					<div class="row">
						<div class="btn-group col-md-6 col-md-offset-3" role="group">
							<button class="btn btn-lg btn-success col-md-6" onclick="launchVialCheck()">
								<i class="glyphicon glyphicon-ok"></i>
								<?php echo $this->translate('Yes'); ?>
							</button>
							<button class="btn btn-lg btn-danger col-md-6" data-dismiss="modal">
								<i class="glyphicon glyphicon-remove"></i>
								<?php echo $this->translate('No'); ?>
							</button>
						</div>
					</div>
				</div>
				<div id="vialInProgress" style="display: none;">
					<h1 style="font-size: 3em;"><?php echo $this->translate('Vial Control in progress'); ?></h1>
					<div class="alert alert-danger" style="font-size: 2em;">
						<p class="text-center">
							<span class="animate-neon" style="color: #e8bf28; font-size: 3em;">&#9762;</span>
						</p>
						<p>
						<?php echo $this->translate('Please stay at a distance of few meters from the machine during this process.'); ?>
						</p>
					</div>
				</div>
				<div id="vialInError" style="display: none;">
					<h1><i class="glyphicon glyphicon-info-sign"></i> <?php echo $this->translate('Vial control has failed.'); ?></h1>
					<div class="alert alert-danger">
						<p>
						<?php echo $this->translate('The vial control encountered a problem. Try to relaunch a control or see the manual.'); ?>
						</p>
					</div>
					<div class="row">
						<button class="btn btn-default col-md-6 col-md-offset-3" aria-label="Close" data-dismiss="modal"><?php echo $this->translate("Close"); ?></button>
					</div>
				</div>
				<div id="vialResults" style="display: none;">
					<h2><?php echo $this->translate("Results of vial check"); ?></h2>
					<div class="row">
						<div class="col-md-6">
							<div class="panel panel-info" id="panel-operator">
								<div class="panel-heading">
									<h4><?php echo $this->translate("Vial infos setted by operator"); ?></h4>
								</div>
								<div class="panel-body">
									<table class="table table-condensed disabled-blank-input" id="tableSetted" style="min-width: 400px;">
										<tr>
											<td>
												<div class="form-group">
													<label for="i1" class="col-sm-6 control-label"><?php echo $this->translate('Vial Volume')?></label>
													<div class="col-sm-6">
														<div class="input-group">
															<input type="number" class="form-control input-sm input-md" id="dbVolume" disabled="disabled">
															<span class="input-group-addon">ml</span>
														</div>
													</div>
												</div>
											</td>
										</tr>
										<tr>
											<td>
												<div class="form-group">
													<label for="i1" class="col-sm-6 control-label"><?php echo $this->translate('Vial Activity')?></label>
													<div class="col-sm-6">
														<div class="input-group">
															<input type="number" class="form-control" id="dbActivity" disabled="disabled">
															<span class="input-group-addon"><?php echo $unit?></span>
														</div>
													</div>
												</div>
											</td>
										</tr>
										<tr>
											<td>
												<div class="form-group">
													<label for="i1" class="col-sm-6 control-label"><?php echo $this->translate('Volumic Activity')?></label>
													<div class="col-sm-6">
														<div class="input-group">
															<input type="number" class="form-control" id="dbActVol" disabled="disabled">
															<span class="input-group-addon"><?php echo $unit; ?>/ml</span>
														</div>
													</div>
												</div>
											</td>
										</tr>
									</table>
								</div>
							</div>
						</div>
						<div class="col-md-6">
							<div class="panel panel-success" id="panel-system">
								<div class="panel-heading">
									<h4><?php echo $this->translate("Vial infos measured by the system"); ?></h4>
								</div>
								<div class="panel-body">
									<table class="table table-condensed disabled-blank-input" id="tableMeasured">
										<tr>
											<td>
												<div class="form-group">
													<label for="i1" class="col-sm-6 control-label"><?php echo $this->translate('Vial Volume')?></label>
													<div class="col-sm-6">
														<div class="input-group">
															<input type="number" class="form-control input-sm input-md" id="measuredVolume" disabled="disabled">
															<span class="input-group-addon">ml</span>
														</div>
													</div>
												</div>
											</td>
										</tr>
										<tr>
											<td>
												<div class="form-group">
													<label for="i1" class="col-sm-6 control-label"><?php echo $this->translate('Vial Activity')?></label>
													<div class="col-sm-6">
														<div class="input-group">
															<input type="number" class="form-control" id="measuredActivity" disabled="disabled">
															<span class="input-group-addon"><?php echo $unit?>/ml</span>
														</div>
													</div>
												</div>
											</td>
										</tr>
										<tr>
											<td>
												<div class="form-group">
													<label for="i1" class="col-sm-6 control-label"><?php echo $this->translate('Volumic Activity')?></label>
													<div class="col-sm-6">
														<div class="input-group">
															<input type="number" class="form-control" id="measuredActVol" disabled="disabled">
															<span class="input-group-addon"><?php echo $unit; ?>/ml</span>
														</div>
													</div>
												</div>
											</td>
										</tr>
									</table>
								</div>
							</div>
						</div>
					</div>
					<div class="row" id="resultsSimilar" style="display: none;">
						<h3><?php echo $this->translate("Measured infos are equivalent to setted infos."); ?></h3>
						<p><?php echo $this->translate("The system is going to use measured infos."); ?></p>
					</div>
					<div class="row" id="resultsDifferent" style="display: none;">
						<div class="col-md-10 col-md-offset-1">
							<div class="alert alert-warning">
								<h3 style="margin-top: 0;"><?php echo $this->translate("Measured infos are different to setted infos."); ?></h3>
								<p>
									<?php echo $this->translate("The system has detect a signifiant difference between infos setted by the user and those measured."); ?>
									<br />
									<?php echo $this->translate("This difference can be due by : "); ?>
								</p>
								<ul>
									<li><?php echo $this->translate("a bad input of the operator during setup drug process"); ?></li>
									<li><?php echo $this->translate("a delay between the first vial opening and the vial loading in the machine"); ?></li>
									<li><?php echo $this->translate("a wrong information on the vial notice"); ?></li>
								</ul>
							</div>
							<span class="help-block"><?php echo $this->translate("Recommanded choice is to keep measured infos."); ?></span>
						</div>
					</div>
					<div class="row" id="chooseBtns" style="display: none;">
						<div class="col-md-1"></div>
						<div class="col-md-3 text-center">
							<button class="btn btn-info" onclick="acceptMeasure(0);"><?php echo $this->translate("Keep blue panel values"); ?></button>
						</div>
						<div class="col-md-4"><h4><?php echo $this->translate("Please choose what infos you want to keep for injections."); ?></h4></div>
						<div class="col-md-3 text-center">
							<button class="btn btn-success" onclick="acceptMeasure(1);"><?php echo $this->translate("Keep green panel values"); ?></button>
						</div>
						<div class="col-md-1"></div>
					</div>
					<div class="row" id="theChoice" style="display: none;">
						<div class="col-md-10 col-md-offset-1 alert alert-info" id="refuseChoice">
							<p class="text-center"><?php echo $this->translate("You have choose to keep informations setted by the operator about the vial."); ?></p>
						</div>
						<div class="col-md-10 col-md-offset-1 alert alert-success" id="acceptChoice">
							<p class="text-center"><?php echo $this->translate("You have choose to keep informations measured by the system about the vial."); ?></p>
						</div>
						<button class="btn btn-default col-md-4 col-md-offset-4" data-dismiss="modal"><?php echo $this->translate("Close"); ?></button>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<style>

@keyframes flickerAnimation {
  0%   { opacity:1; }
  50%  { opacity:0.5; }
  100% { opacity:1; }
}
@-o-keyframes flickerAnimation{
  0%   { opacity:1; }
  50%  { opacity:0.5; }
  100% { opacity:1; }
}
@-moz-keyframes flickerAnimation{
  0%   { opacity:1; }
  50%  { opacity:0.5; }
  100% { opacity:1; }
}
@-webkit-keyframes flickerAnimation{
  0%   { opacity:1; }
  50%  { opacity:0.5; }
  100% { opacity:1; }
}
.animate-flicker {
	-webkit-animation	: flickerAnimation 1s infinite;
	-moz-animation		: flickerAnimation 1s infinite;
	-o-animation		: flickerAnimation 1s infinite;
	animation			: flickerAnimation 1s infinite;
}

@keyframes neon {
	from {
    	text-shadow:
    	 	0 5px black,  
  	}
  	to {
    	text-shadow:
    		0 0 80px black;
  	}
}

.animate-neon {
	-webkit-animation	: neon 0.75s ease-in-out infinite alternate;
	-moz-animation		: neon 0.75s ease-in-out infinite alternate;
	animation			: neon 0.75s ease-in-out infinite alternate;
}

</style>
<div class="modal fade" id="confirmRemoveScan" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title"><span class="glyphicon glyphicon-warning-sign"></span> <?php echo $this->translate('Remove receipted kit source.');?></h4>
			</div>
			<div class="modal-body">
				<p><?php echo $this->translate("Are you sure to remove selected source kit ?"); ?></p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-success" onclick="removeSourceKit();"><?php echo $this->translate('Confirm');?></button>
				<button type="button" class="btn btn-danger" data-dismiss="modal"><?php echo $this->translate('Cancel');?></button>
			</div>
		</div>
	</div>
</div>
<?php
	$this->inlineScript()->appendScript('
		$(function() {
			setTimeout(function() {
				reloadOperatorScreen();
			}, 10000);
		});
		
		function reloadOperatorScreen() {
			$.ajax({
				type: "GET",
	       		url: "'. $this->url('operator', array('action' => 'areloadoperatorscreen')) . '",
	       		cache: false,
	       		dataType: "json",
			}).done(function (result) {
				if (result.error == false) {
					$("#mainContent").html(result.html);
				}
			
				setTimeout(function() {
					reloadOperatorScreen();
				}, 10000);
			});
		}
	');
?>
<script type="text/javascript">
$(function() {
	$('#removeDrugButton').click(function() {
		$("#confirmRemoveDrug").modal('show');
	});

	$('#removeScanButton').click(function() {
		$("#confirmRemoveScan").modal('show');
	});

	$(document).on("click", "#btnCheckVial", function() {
		$("#checkVial .modal-dialog .modal-content").removeClass("panel-danger").addClass("panel-primary");
		$("#checkVialConfirm").show();
		$("#vialInError").hide();
		$("#vialResults").hide();
		$("#checkVial").modal('show');
	});

	$(document).on("click", "#btnVialResults", function() {
		loadResults();
	});
});

function loadResults() {
	$.ajax({
		url: "<?php echo $this->url('inject', array('action' => 'agetcheckresults'));?>",
		type: "GET",
		cache: false,
		dataType: "json",
	}).done(function(result) {

		$("#modalTitleLaunch").hide();
		$("#modalTitleConsult").show();
		
		$("#dbVolume").val(result.actuals.vol);
		$("#dbActivity").val(result.actuals.actdt);
		$("#dbActVol").val(result.actuals.actvol);

		$("#panel-operator").removeClass("disable-results");
		$("#panel-system").removeClass("disable-results");

		if (result.selected_activity == '<?php echo InputDrug::SELECTED_ACTIVITY_CONTROLLED; ?>') {
			$("#refuseChoice").hide();
			$("#acceptChoice").show();
			$("#panel-operator").addClass("disable-results");
		} else if (result.selected_activity == '<?php echo InputDrug::SELECTED_ACTIVITY_SETTED; ?>') {
			$("#refuseChoice").show();
			$("#acceptChoice").hide();
			$("#panel-system").addClass("disable-results");
		}

		$("#measuredVolume").val(result.controls.vol);
		$("#measuredActivity").val(result.controls.actdt);
		$("#measuredActVol").val(result.controls.actvol);
		
		$("#vialResults").show();
		$("#theChoice").show();	
		$("#checkVial .modal-dialog").css('min-width', '90%');
		$("#checkVial").modal('show');
	});
}

function launchVialCheck() {
	$("#checkVialConfirm").hide();
	$("#vialInError").hide();
	$("#vialResults").hide();

	
	$("#checkVial .modal-dialog").animate({
		'min-width' : '90%',
		'min-height' : '90%',
	}, 500, function() {
		$("#vialInProgress").show();
		$("#checkVial .modal-dialog .modal-content").removeClass("panel-primary").addClass("panel-danger");
		$.ajax({
			url: "<?php echo $this->url('inject', array('action' => 'alaunchcheckvial'));?>",
			type: "GET",
			cache: false,
			dataType: "json",
		}).done(function(result) {
			checkVialResult();
		});
	});
}

var n = 0;

function checkVialResult() {
	$.ajax({
		url: "<?php echo $this->url('inject', array('action' => 'agetcheckvialstatus'));?>",
		type: "GET",
		cache: false,
		dataType: "json",
	}).done(function(result) {
		if (result.status == 'inprogress') {
			setTimeout(function() {
				checkVialResult();
			}, 25);
		} else if (result.status == 'error') {
			$("#vialInError").show();
			$("#vialInProgress").hide();
		} else if (result.status == 'done') {
			$("#modalTitleLaunch").hide();
			$("#modalTitleConsult").show();
			$("#vialInProgress").hide();
			$("#checkVial .modal-dialog .modal-content").removeClass("panel-danger").addClass("panel-success");

			$("#dbVolume").val(result.actuals.vol);
			$("#dbActivity").val(result.actuals.actdt);
			$("#dbActVol").val(result.actuals.actvol);

			$("#measuredVolume").val(result.controls.vol);
			$("#measuredActivity").val(result.controls.actdt);
			$("#measuredActVol").val(result.controls.actvol);

			if (result.mustchoose == true) {
				$("#resultsSimilar").hide();
				$("#resultsDifferent").show();
				$("#chooseBtns").show();
			} else {
				$("#resultsSimilar").show();
				$("#resultsDifferent").hide();
				$("#chooseBtns").hide();
			}
			
			$("#vialResults").show();
		}
	});
}

function acceptMeasure(acceptOrNot) {
	$.ajax({
		type: "POST",
		data: {accept : acceptOrNot},
        url: "<?php echo $this->url('inject', array('action' => 'arejectoracceptvialresult')); ?>",
        cache: false,
        dataType: "json",
	}).done(function (result) {
		if (acceptOrNot == 0) {
			$("#refuseChoice").show();
			$("#acceptChoice").hide();
		} else if (acceptOrNot == 1) {
			$("#refuseChoice").hide();
			$("#acceptChoice").show();
		}
		$("#resultsDifferent").hide();
		$("#chooseBtns").hide();
		$("#theChoice").show();
	});
}

function removeDrug() {
	$.ajax({
		type: "GET",
        url: "<?php echo $this->url('setup', array('action'=>'aunloaddrug'))?>",
        cache: false,
        dataType: "json",
	}).done(function (result) {
		location.reload();
	});
}

function removeSourceKit() {
	$.ajax({
		type: "GET",
		url: "<?php echo $this->url('setup', array('action'=>'aunloadsourcekit'))?>",
		cache: false,
		dataType: "json",
	}).done(function (result) {
		location.reload();
	});
}

function lauchDilution() {
	//TODO Code temporaire

	
	$("#msgDilution").hide();
	$("#dilutionFooterConfirm").hide();
	$("#dilutionProgress").show();
	$("#dilutionFooterClose").show();

	$.ajax({
		type: "GET",
		url: "<?php echo $this->url('inject', array('action'=>'avioldilutionprogess'))?>",
		cache: false,
		dataType: "json",
	}).done(function (result) {
		location.reload();
	});
}
</script>
<?php } ?>