<ol class="breadcrumb">
	<li class="active"><span class=" glyphicon glyphicon-home"></span> <?php echo $this->translate('Operator dashboard')?></li>
</ol>
<?php if ($hasExams === false) { ?>
<div class="alert alert-danger" role="alert">
	<strong><i class="glyphicon glyphicon-exclamation-sign"></i> <?php echo $this->translate('Warning');?> <i class="glyphicon glyphicon-exclamation-sign"></i></strong> 
	<p><?php echo sprintf('%s <a href="' . $this->url("examination", array("action" => "add")) . '" class="alert-link">%s</a> %s', $this->translate('No exams found in database. Please '), $this->translate('create an exam'), $this->translate(' to start injections.')); ?></p>
</div>
<?php } else { ?>
<div class="well">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<div class="list-group">
				<?php if ($step->fileloaded) { ?>
				<a href="#" class="list-group-item list-group-item-success">
					<span class="badge badge-success"><span class="glyphicon glyphicon-ok"></span></span>
					<span class="glyphicon glyphicon-import"></span>
					<?php echo $this->translate("Transfering patient's data to robot")?>
				</a>
				<?php } else { ?>
				<a href="<?php echo $this->url('setup', array('action'=>'loadpatient'))?>" class="list-group-item list-group-item-danger">
					<span class="badge badge-danger">!</span>
					<span class="glyphicon glyphicon-import"></span>
					<?php echo $this->translate("Transfering patient's data to robot"); ?>
				</a>
				<?php } ?>

				<?php if ($step->drugspecified) { ?>
				<a href="#" class="list-group-item list-group-item-success">
					<?php if (!$step->sourcekitloaded) { ?>
					<span id="removeDrugButton" class="badge badge-danger"><span class="glyphicon glyphicon-remove"></span></span>
					<?php } ?>
					<span class="badge badge-success"><span class="glyphicon glyphicon-ok"></span></span>
					<span class="glyphicon glyphicon-file"></span>
					<?php echo sprintf($this->translate("Receipted drug : <u>%s</u>"), $selectedDrugName); ?>
				</a>
				<?php } else { ?>
				<a href="<?php echo $this->url('setup', array('action'=>'drug'))?>" class="list-group-item list-group-item-danger">
					<span class="badge badge-danger">!</span>
					<span class="glyphicon glyphicon-file"></span>
					<?php echo $this->translate("Filling drug's informations")?>
				</a>
				<?php } ?>

				<?php if ($step->sourcekitscanned) { ?>
				<a href="#" class="list-group-item list-group-item-success">
					<?php if (!$step->sourcekitloaded) { ?>
					<span id="removeScanButton" class="badge badge-danger"><span class="glyphicon glyphicon-remove"></span></span>
					<?php } ?>
					<span class="badge badge-success"><span class="glyphicon glyphicon-ok"></span></span>
					<span class="glyphicon glyphicon-barcode"></span>
					<?php echo $this->translate('Scan source kit barcode')?>
				</a>
				<?php } else { ?>
				<a href="<?php echo $this->url('setup', array('action'=>'scankitsource'))?>" class="list-group-item list-group-item-danger">
					<span class="badge badge-danger">!</span>
					<span class="glyphicon glyphicon-barcode"></span>
					<?php echo $this->translate('Scan source kit barcode')?>
				</a>
				<?php } ?>

				<?php if ($step->sourcekitloaded) { ?>
				<a href="#" class="list-group-item list-group-item-success">
					<span class="badge badge-success"><span class="glyphicon glyphicon-ok"></span></span>
					<span class="glyphicon glyphicon-download"></span>
					<?php echo $this->translate('Loading Source kit & Source')?>
				</a>
				<?php } else if ($step->sourcekitscanned && $step->drugspecified) { ?>
				<a href="<?php echo $this->url('setup', array('action'=>'loadkitsource'))?>" class="list-group-item list-group-item-danger">
					<span class="badge badge-danger" title="<?php echo $this->translate('Action required')?>">!</span>
					<span class="glyphicon glyphicon-download"></span>
					<?php echo $this->translate('Loading Source kit & Source')?>
				</a>
				<?php } else { ?>
				<a href="#" class="list-group-item">
					<span class="glyphicon glyphicon-download"></span>
					<span class="badge"><span class="glyphicon glyphicon-lock"></span></span>
					<?php echo $this->translate('Loading Source kit & Source')?>
				</a>
				<?php } ?>
				
				<?php if ($canInject) { ?>
				<?php if ($step->fileloaded === false) { $cssClass = 'list-group-item-warning'; } else { $cssClass = 'active'; } ?>
				<a href="<?php echo $this->url('auth', array('action'=>'confirmauth'))?>" class="list-group-item active">
					<span class="glyphicon glyphicon-user"></span>
					<?php echo $this->translate('Injection - Operator Authentification')?>
				</a>
				<?php } else {?>
				<a href="#" class="list-group-item">
					<span class="badge"><span class="glyphicon glyphicon-lock"></span></span>
					<span class="glyphicon glyphicon-user"></span>
					<?php echo $this->translate('Injection - Operator Authentification')?>
				</a>
				<?php } ?>

				<a href="<?php echo $this->url('bufferspace', array('action'=>'patientlist'))?>" class="list-group-item">
					<span class="glyphicon glyphicon-list"></span>
					<?php echo $this->translate('List of patients injected')?>
				</a>

				<?php if ($canUnload) { ?>
				<a href="<?php echo $this->url('inject', array('action'=>'unload'))?>" class="list-group-item">
					<span class="badge" title="<?php echo $this->translate('Action required')?>"><span class="glyphicon glyphicon-exclamation-sign"></span></span>
					<span class="glyphicon glyphicon-upload"></span>
					<?php echo $this->translate('Unloading')?>
				</a>
				<?php } else { ?>
				<a href="#" class="list-group-item">
					<span class="badge"><span class="glyphicon glyphicon-lock"></span></span>
					<span class="glyphicon glyphicon-upload"></span>
					<?php echo $this->translate('Unloading')?>
				</a>
				<?php } ?>

				<?php if ($canExport) { ?>
				<a href="<?php echo $this->url('exportbuffer', array('action'=>'index'))?>" class="list-group-item">
					<span class="badge" title="<?php echo $this->translate('Action required')?>"><span class="glyphicon glyphicon-exclamation-sign"></span></span>
					<span class="glyphicon glyphicon-export"></span>
					<?php echo $this->translate('Transferting patient\'s data to software')?>
				</a>
				<?php } else { ?>
				<a href="#" class="list-group-item">
					<span class="badge"><span class="glyphicon glyphicon-lock"></span></span>
					<span class="glyphicon glyphicon-export"></span>
					<?php echo $this->translate('Transferting patient\'s data to software')?>
				</a>
				<?php } ?>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="confirmRemoveDrug" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title"><span class="glyphicon glyphicon-warning-sign"></span> <?php echo $this->translate('Remove receipted drug.');?></h4>
			</div>
			<div class="modal-body">
				<p><?php echo $this->translate("Are you sure to remove selected drug ?"); ?></p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-success" onclick="removeDrug();"><?php echo $this->translate('Confirm');?></button>
				<button type="button" class="btn btn-danger" data-dismiss="modal"><?php echo $this->translate('Cancel');?></button>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="confirmRemoveScan" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title"><span class="glyphicon glyphicon-warning-sign"></span> <?php echo $this->translate('Remove receipted kit source.');?></h4>
			</div>
			<div class="modal-body">
				<p><?php echo $this->translate("Are you sure to remove selected source kit ?"); ?></p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-success" onclick="removeSourceKit();"><?php echo $this->translate('Confirm');?></button>
				<button type="button" class="btn btn-danger" data-dismiss="modal"><?php echo $this->translate('Cancel');?></button>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
$(function() {
	$('#removeDrugButton').click(function() {
		$("#confirmRemoveDrug").modal('show');
	});

	$('#removeScanButton').click(function() {
		$("#confirmRemoveScan").modal('show');
	});
});

function removeDrug() {
	  $.ajax({
          type: "GET",
          url: "<?php echo $this->url('setup', array('action'=>'aunloaddrug'))?>",
          cache: false,
          dataType: "json",
        }).done(function (result) {
            location.reload();
        });
}

function removeSourceKit() {
	  $.ajax({
        type: "GET",
        url: "<?php echo $this->url('setup', array('action'=>'aunloadsourcekit'))?>",
        cache: false,
        dataType: "json",
      }).done(function (result) {
          location.reload();
      });
}
</script>
<?php } ?>