<html lang="en">
	<head>
		<meta charset="utf-8">
		<?php echo $this->headTitle($this->translate('S.A.M.I.'))->setSeparator(' - ')->setAutoEscape(false) ?>

		<?php echo $this->headMeta()
			->appendName('viewport', 'width=device-width, initial-scale=1.0')
			->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
		?>

		<!-- Le styles -->
		<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/injection.ico'))
						->prependStylesheet($this->basePath() . '/css/print.css')
		?>
<body>
	<div class="print-container">
		<div class="content">
			<div class="row">
	    		<div class="col-xs-2 no-padding"><span style="font-size: 2.6em; font-weight: normal; line-height: 0.8em;">&#9762;</span></div>
	    		<div class="col-xs-6 no-padding" style="margin-top: 1mm;"><?php echo date('d/m/Y'); ?></div>
	    		<div class="col-xs-4 no-padding" style="margin-top: 1mm;"><?php echo $timeInjection->format('H:i'); ?></div>
	  		</div>
			<div class="row">
				<div class="col-xs-10 col-xs-offset-2 no-padding"><?php echo $drug['name']; ?></div>
			</div>
			<div class="row">
				<div class="col-xs-7 col-xs-offset-5 no-padding"><?php echo $injection['activity'] . ' ' . $unit; ?></div>
			</div>
			<div class="row spacer"></div>
			<div class="row">
				<div class="col-xs-5 no-padding"><?php echo $radionuclide['code']; ?></div>
				<div class="col-xs-7 no-padding"><?php echo $this->translate('Serial : '); ?><span><?php echo $curdrug['batchnum']; ?></span></div>
			</div>
			<div class="row spacer"></div>
			<div class="row">
				<div class="col-xs-5 no-padding">N&ordm; <span><?php echo $injection['unique_id']; ?></span></div>
				<div class="col-xs-7 no-padding"><?php echo strtoupper($operator['lastname']); ?> <?php echo ucfirst(strtolower($operator['firstname'])); ?></div>
			</div>
		</div>
	</div>
</body>
</html>
