<div class="modal-content">
	<div class="modal-header">
		<h4 class="modal-title" id="errordetectedModalLabel"><i class="glyphicon glyphicon-time"></i> <?php echo $this->translate('System error detected'); ?></h4>
	</div>
	<div class="modal-body">
		<div class="alert alert-danger" role="alert">
			<p>Batterie non détectée</p>
			<p>Vérifiez que le sectionneur de batterie et sur la position ON. Si c'est le cas => Appel au S.A.V.</p>
		</div>
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-primary" onclick="location.href='<?php echo $this->url('log', array('action' => 'logout')); ?>'"><i class="glyphicon glyphicon-home"></i> <?php echo $this->translate('Exit'); ?></button>
	</div>
</div>



