<div class="alert alert-danger" role="alert">
	<p>Activité maximale autorisée pour le centre non renseignée</p>
	<p>Superviseur - Menu Système - Saisir l'activité maximale autorisée.</p>
	<img src="/img/tutos/set_maximum_value.gif">
	<div class="row">
			<a class="col-md-8 col-md-offset-2 btn btn-default" href="<?php echo $this->url("system"); ?>"><?php echo $this->translate("Set the maximum activity"); ?></a>
	</div>
</div>
