<?php echo $this->doctype(); ?>
<?php
if ($virtualkeyboardEnable === true) {
	$this->headStyle()->appendStyle('.ui-keyboard { font-size: ' . $virtualkeyboardSize . 'em; }');
}
?>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<?php echo $this->headTitle($this->translate('S.A.M.I.'))->setSeparator(' - ')->setAutoEscape(false) ?>

		<?php echo $this->headMeta()
			->appendName('viewport', 'width=device-width, initial-scale=1.0')
			->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
		?>

		<!-- Le styles -->
		<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/injection.ico'))
						->prependStylesheet($this->basepath() . '/css/keyboard-previewkeyset.css')
						->prependStylesheet($this->basepath() . '/css/keyboard.css')
						->prependStylesheet($this->basePath() . '/css/style.css')
						->prependStylesheet($this->basepath() . '/css/bootstrap-patch.css')
						->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
						->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
						->prependStylesheet($this->basePath() . '/css/signin.css')
						->prependStylesheet($this->basePath() . '/css/bootstrap-datetimepicker.min.css')
						->prependStylesheet($this->basepath() . '/css/bootstrap-slider.css')
		?>

		<!-- Scripts -->
		<?php echo $this->headScript()
			->prependFile($this->basepath() . '/js/jquery.keyboard.layout-french.js')
			->prependFile($this->basepath() . '/js/jquery.keyboard.extension-all.js')
			->prependFile($this->basepath() . '/js/jquery.keyboard.js')
			->prependFile($this->basepath() . '/js/jquery-barcode.min.js')
			->prependFile($this->basePath() . '/js/bootstrap.min.js')
			->prependFile($this->basePath() . '/js/jquery-ui.min.js')
			->prependFile($this->basePath() . '/js/jquery.min.js')
			->prependFile($this->basePath() . '/js/respond.min.js',	'text/javascript', array('conditional' => 'lt IE 9',))
			->prependFile($this->basePath() . '/js/html5shiv.js', 	'text/javascript', array('conditional' => 'lt IE 9',))
		?>
	</head>
	<body>
		<noscript style="width: 100%; height: 100%; position: absolute; background-color: white; z-index: 10000;">
			<div class="col-md-3"></div>
			<div class="col-md-6">
				<div class="alert alert-danger" role="alert">
					<p><?php echo $this->translate('The Javascript of your browser seems to be desactivated.'); ?></p>
					<p><?php echo $this->translate('Please enable it to use S.A.M.I or contact the support.'); ?></p>
				</div>
			</div>
			<div class="col-md-3"></div>
		</noscript>
		<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="sr-only"><?php echo $this->translate('Delphinnove')?></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="<?php echo $this->url('home') ?>">
						<img src="/img/delphinnove_logo.png" style="width:90px;height:30px;position:relative;bottom:2px;"/>
						<?php echo $this->translate('S.A.M.I.') ?>
					</a>
				</div>
				<div class="collapse navbar-collapse">
					<ul class="nav navbar-nav">
					</ul>
				</div><!--/.nav-collapse -->
			</div>
		</nav>
		<div class="container">
			<?php echo $this->content; ?>
		</div> <!-- /container -->
		<nav class="navbar navbar-inverse navbar-fixed-bottom" role="navigation">
			<div class="container">
				<ul class="nav navbar-nav navbar-right">
					<li><p class="navbar-text"><span class="glyphicon glyphicon-copyright-mark"></span> 2013 - <?php echo date('Y'); ?> <?php echo $this->translate('by Delphinnove. All rights reserved.')?></p></li>
				</ul>
			</div>
		</nav>
		<?php
		if ($virtualkeyboardEnable === true) {
			$this->headStyle()->appendStyle('.ui-keyboard { font-size: ' . $virtualkeyboardSize . 'em; }');
			$this->inlineScript()->appendScript('
				$(function(){
					$("input[type=text].form-control,input[type=password].form-control").keyboard({
						autoAccept: true, 
						layout: "french-azerty-1",
						position     : {
    						of : $("form.form-signin"),
    						my : "center top",
    						at : "center bottom",
    						at2: "center bottom",
  						},
					});
				});
			');
		}
		?>
		<?php echo $this->inlineScript() ?>
	</body>
</html>
