<?php echo $this->doctype(); ?>
<?php
if ($virtualkeyboardEnable === true) {
	$this->headStyle()->appendStyle('
			.ui-keyboard-button span { font-size: ' . $virtualkeyboardSize . 'em; }
			.ui-keyboard-button { 
				height: ' . (2 * $virtualkeyboardSize) .'em;
			    min-width: ' . (2 * $virtualkeyboardSize) .'em;
			    margin: ' . (0.1 * $virtualkeyboardSize) .'em;
			    line-height: ' . (2 * $virtualkeyboardSize) .'em;
			}
	');
}
?>
<?php //TODO Trad high prio ?>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<?php echo $this->headTitle($this->translate('S.A.M.I.'))->setSeparator(' - ')->setAutoEscape(false) ?>

		<?php echo $this->headMeta()
			->appendName('viewport', 'width=device-width, initial-scale=1.0')
			->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
		?>

		<!-- Le styles -->
		<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/injection.ico'))
						->prependStylesheet($this->basepath() . '/css/keyboard-previewkeyset.css')
						->prependStylesheet($this->basepath() . '/css/keyboard.css')
						->prependStylesheet($this->basePath() . '/css/style.css')
						->prependStylesheet($this->basePath() . '/css/print.css', 'print')
						->prependStylesheet($this->basepath() . '/css/bootstrap-patch.css')
						->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
						->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
						->prependStylesheet($this->basePath() . '/css/signin.css')
						->prependStylesheet($this->basePath() . '/css/bootstrap-datetimepicker.min.css')
						->prependStylesheet($this->basepath() . '/css/bootstrap-slider.css');
		?>

		<!-- Scripts -->
		<?php echo $this->headScript()
			->prependFile($this->basepath() . '/js/bootstrap-slider.min.js')
			->prependFile($this->basePath() . '/js/jquery-ui.min.js')
			->prependFile($this->basepath() . '/js/jquery.keyboard.layout-french.js')
			->prependFile($this->basepath() . '/js/jquery.keyboard.extension-all.js')
			->prependFile($this->basepath() . '/js/jquery.keyboard.js')
			->prependFile($this->basepath() . '/js/jquery-barcode.min.js')
			->prependFile($this->basePath() . '/js/bootstrap-datetimepicker.min.js')
			->prependFile($this->basePath() . '/js/bootstrap.min.js')
			->prependFile($this->basePath() . '/js/jquery.min.js')
			->prependFile($this->basepath() . '/js/moment-with-langs.min.js')
			->prependFile($this->basePath() . '/js/respond.min.js',	'text/javascript', array('conditional' => 'lt IE 9',))
			->prependFile($this->basePath() . '/js/html5shiv.js', 	'text/javascript', array('conditional' => 'lt IE 9',));
		?>
		<?php echo $this->headStyle(); ?>
	</head>
	<body>
		<div class="non-printable">
			<noscript style="width: 100%; height: 100%; position: absolute; background-color: white; z-index: 10000;">
				<div class="col-md-3"></div>
				<div class="col-md-6">
					<div class="alert alert-danger" role="alert">
						<p><?php echo $this->translate('The Javascript of your browser seems to be desactivated.'); ?></p>
						<p><?php echo $this->translate('Please enable it to use S.A.M.I or contact the support.'); ?></p>
					</div>
				</div>
				<div class="col-md-3"></div>
			</noscript>
			
			<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
				<div class="container">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
							<span class="sr-only"><?php echo $this->translate('Delphinnove')?></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<a class="navbar-brand" href="<?php echo $this->url('home') ?>">
							<img src="/img/delphinnove_logo.png" style="width:90px;height:30px;position:relative;bottom:2px;"/>
							<?php echo $this->translate('S.A.M.I.'); ?>
						</a>
					</div>
					<div class="collapse navbar-collapse">
						<ul class="nav navbar-nav">
							<?php if($this->isAdmin){?>
							<li><a href="<?php echo $this->url('manager') ?>"><?php echo $this->translate('Manager') ?></a></li>
							<?php } ?>
							<li><a href="<?php echo $this->url('operator') ?>"><?php echo $this->translate('Operator') ?></a></li>
						</ul>
						<ul class="nav navbar-nav navbar-right">
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span> <?php echo $this->login;?> <b class="caret"></b></a>
								<ul class="dropdown-menu">
									<li><a href="<?php echo $this->url('log', array('action'=>'changepwd')) ?>"><span class="glyphicon glyphicon-edit"></span> <?php echo $this->translate('Change password') ?></a></li>
									<li><a href="<?php echo $this->url('log', array('action'=>'logout'))?>"><span class="glyphicon glyphicon-log-out"></span> <?php echo $this->translate('Logout') ?></a></li>
								</ul>
							</li>
						</ul>
					</div><!--/.nav-collapse -->
				</div>
			</nav>
			<div class="container">
				<?php $flash = $this->flashMessenger(); ?>
				<?php 
					$flash->setMessageOpenFormat('<div%s>
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">
							&times;
						</button>
						<ul><li>')
					->setMessageSeparatorString('</li><li>')
					->setMessageCloseString('</li></ul></div>');
					
					echo $flash->render('error',	array('alert', 'alert-dismissable', 'alert-danger'));
					echo $flash->render('info',		array('alert', 'alert-dismissable', 'alert-info'));
					echo $flash->render('default',	array('alert', 'alert-dismissable', 'alert-warning'));
					echo $flash->render('success',	array('alert', 'alert-dismissable', 'alert-success'));
				?>
				<?php echo $this->content; ?>
			</div> <!-- /container -->
			<nav class="navbar navbar-inverse navbar-fixed-bottom" role="navigation">
				<div class="container">
					<ul class="nav navbar-nav navbar-right">
						<li><p class="navbar-text"><span class="glyphicon glyphicon-copyright-mark"></span> 2013 - <?php echo date('Y'); ?> <?php echo $this->translate('by Delphinnove. All rights reserved.')?></p></li>
					</ul>
				</div>
			</nav>
		<?php 
		$this->inlineScript()->appendScript("history.pushState(null, null, location.href); window.onpopstate = function(event) { history.go(1); };");
		$this->inlineScript()->appendScript('
			$(function(){
				$("input[role=\'delete\'].btn, a[role=\'delete\'].btn").on("click", function() {
					var title = $(this).data("delete-title");
					var contenu = $(this).data("delete-content");	

					$("#deleteConfirmationOkButton").attr("href", $(this).attr("href"));
					$("#deleteConfirmationTitle").html(title);
					$("#deleteConfirmationBody").html(contenu);
 					
					$("#deleteConfirmation").modal();
					
					return false;
				});
			});
		');
		
		$this->inlineScript()->appendScript('
			function printElement(elem, append, delimiter) 
			{
				var domClone = elem.cloneNode(true);
			
			    var $printSection = document.getElementById("printSection");
			
			    if (!$printSection) {
			        $printSection = document.createElement("div");
			        $printSection.id = "printSection";
			        document.body.appendChild($printSection);
			    }
			
			    if (append !== true) {
			        $printSection.innerHTML = "";
			    } else if (append === true) {
			        if (typeof(delimiter) === "string") {
			            $printSection.innerHTML += delimiter;
			        }
			        else if (typeof(delimiter) === "object") {
			            $printSection.appendChlid(delimiter);
			        }
			    }
			
			    $printSection.appendChild(domClone);
				
			}');
		
		if ($appendSupervisorJsTimeout === true) {
			$this->inlineScript()->appendScript('
					$(function() {
						setTimeout(function(){
							$.ajax({
								url: "'. $this->url('log', array('action'=>'autologout')) . '",
							}).done(function(result){
								$("#modalAutoLogout").modal({
									backdrop: "static",
									keyboard: false,
									show: true,
								});
							});
						}, ' . $supervisorTimeout . '000);
					});
			');
		}
		
		if ($appendOperatorJsTimeout === true) {
			$this->inlineScript()->appendScript('
					$(function() {
						setTimeout(function(){
							$.ajax({
								url: "'. $this->url('log', array('action'=>'autologout')) . '",
							}).done(function(result){
								$("#modalAutoLogout").modal({
									backdrop: "static",
									keyboard: false,
									show: true,
								});
							});
						}, ' . $operatorTimeout . '000);
					});
			');
		}

		if ($disableLinks === true) {
			$this->inlineScript()->appendScript('
				$(function(){
					$("nav.navbar li").addClass("disabled");
					
					$("ol.breadcrumb li a").css("cursor", "not-allowed");
					
					$("nav.navbar a.navbar-brand").css("cursor", "not-allowed");
					
					$("nav.navbar li a").click(function() {
						return false;
					});
			
					$("ol.breadcrumb li").click(function() {
						return false;
					});
			
					$("nav.navbar a.navbar-brand").click(function() {
						return false;
					});
				});
			');
		}
		
		if ($virtualkeyboardEnable === true) {
			$this->inlineScript()->appendScript('
				$(function(){
					$("input[type=text].form-control,input[type=password].form-control").not(".input-date").not(".barcode").not(".number").keyboard({
						autoAccept: true,
					 /**
						display : {
							bksp   : "\u2190",
							accept : "Valider",
							cancel : "Annuler",
							default: "ABC",
							meta1  : ".?123",
							meta2  : "#+=",
						},
						layout: "french-sami",
					**/
						layout: "french-azerty-1",
						css: {
					        input: "form-control input-md",
					        container: "center-block dropdown-menu large-input",
					        buttonDefault: "btn btn-default",
					        buttonHover: "btn-primary",
					        buttonAction: "active",
					        buttonDisabled: "disabled",
					    },
					});
					
					$("input[type=text].form-control.barcode").keyboard({
						autoAccept: true, 
						layout : "custom",
						maxLength : 35,
						customLayout: {
							"normal" : [
								"1 2 3 4 5 {b} {clear}",
								"6 7 8 9 0 {a} {c}"
							]
						},
						css: {
					        input: "form-control input-md",
					        container: "center-block dropdown-menu",
					        buttonDefault: "btn btn-default",
					        buttonHover: "btn-primary",
					        buttonAction: "active",
					        buttonDisabled: "disabled",
					    },
					});
					
					$("textarea.form-control").keyboard({
						autoAccept: true, 
						layout: "french-azerty-1",
						css: {
					        input: "form-control input-md",
					        container: "center-block dropdown-menu",
					        buttonDefault: "btn btn-default",
					        buttonHover: "btn-primary",
					        buttonAction: "active",
					        buttonDisabled: "disabled",
					    },
					});
					
					$("input[type=number].form-control,input[type=text].form-control.number").keyboard({
						layout : "custom",
						customLayout: {
							"normal" : [
								"7 8 9 {b}",
								"4 5 6 {clear}",
								"1 2 3 {a}",
								"0 {dec} - {c}"
							]
						}, 
						autoAccept: true,
						css: {
					        input: "form-control input-md",
					        container: "center-block dropdown-menu",
					        buttonDefault: "btn btn-default",
					        buttonHover: "btn-primary",
					        buttonAction: "active",
					        buttonDisabled: "disabled",
					    },
					});
					
					$("input[type=text].input-date").keyboard({
						layout : "custom",
						customLayout: {
							"normal" : [
								"7 8 9 {b}",
								"4 5 6 {clear}",
								"1 2 3 {a}",
								"0 - : {c}"
							]
						}, 
						autoAccept: true,
						css: {
					        input: "form-control input-md",
					        container: "center-block dropdown-menu",
					        buttonDefault: "btn btn-default",
					        buttonHover: "btn-primary",
					        buttonAction: "active",
					        buttonDisabled: "disabled",
					    },
					});
				});
			');
		}
		
		$this->inlineScript()->appendScript('
			$(function() {
				function checkErrorSystem() {
					setTimeout(function(){
						$.ajax({
							url: "'. $this->url('checkerrorstatus', array()) . '",
						}).done(function(result){
							if (result.error === false) {
								checkErrorSystem();
							} else {
								$("#errorMessageSpan").html(result.errorMessage);
								$("#modalErrorDetected").modal({
									backdrop: "static",
									keyboard: false,
									show: true,
								});
							}
						});
					}, 15000);
				}
				
				checkErrorSystem();
			});
		');
		
		?>
		<?php echo $this->inlineScript() ?>
		<?php if ($this->login == "DelphInnove") {
				echo '<H1 style="z-index: 5000;position: absolute; top: 0px; left: 40%; border: 2px; border-color: red; border-style: dashed;color:red; margin:3px; padding:3px;"> <u>/!\</u> MODE DEMO <u>/!\ </u></H1>'; 
		};?>
		
		<div id="deleteConfirmation" class="modal fade" tabindex="-1" role="dialog" aria-labbeledby="deleteConfirmationTitle" aria-hidden="true">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal">
							<span aria-hidden="true">&times;</span>
							<span class="sr-only">Close</span>
						</button>
						<h4 class="modal-title" id="deleteConfirmationTitle"></h4>
					</div>
					<div class="modal-body" id="deleteConfirmationBody"></div>
					<div class="modal-footer">
						<button class="btn btn-default" data-dismiss="modal">Annuler</button>
						<a id="deleteConfirmationOkButton" href="#" class="btn btn-primary">OK</a>
					</div>
				</div>
			</div>
		</div>
		
<?php if ($appendOperatorJsTimeout === true) { ?>
		<div class="modal fade" id="modalAutoLogout" tabindex="-1" role="dialog" aria-labelledby="autologoutModalLabel">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<h4 class="modal-title" id="autologoutModalLabel"><i class="glyphicon glyphicon-time"></i> <?php echo $this->translate('Locking protection system'); ?></h4>
					</div>
					<div class="modal-body">
						<div class="alert alert-warning" role="alert">
							<p><?php echo sprintf($this->translate('No activity has been detect on this screen since %s seconds.'), $operatorTimeout); ?></p>
							<p><?php echo $this->translate('You have been deconnected.'); ?></p>
							<br />
							<p><?php echo $this->translate('Please proceed to Sign-In button to be reconnected.'); ?></p>
						</div>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-primary" onclick="location.href='<?php echo $this->url('log'); ?>'"><i class="glyphicon glyphicon-home"></i> <?php echo $this->translate('Sign In'); ?></button>
					</div>
				</div>
			</div>
		</div>
<?php } ?>
<div class="modal fade" id="modalErrorDetected" tabindex="-1" role="dialog" aria-labelledby="errordetectedModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title" id="errordetectedModalLabel"><i class="glyphicon glyphicon-time"></i> <?php echo $this->translate('System error detected'); ?></h4>
			</div>
			<div class="modal-body">
				<div class="alert alert-danger" role="alert">
					<p><?php echo $this->translate('An error has been raised by the robot :'); ?></p>
					<p><?php echo $this->translate('Error message : ');?><span id="errorMessageSpan"></span></p>
					<br />
					<p><?php echo $this->translate('Please check the manual for instructions.'); ?></p>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary" onclick="location.href='<?php echo $this->url('log'); ?>'"><i class="glyphicon glyphicon-home"></i> <?php echo $this->translate('Sign In'); ?></button>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="modalAutoLogout" tabindex="-1" role="dialog" aria-labelledby="autologoutModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title" id="autologoutModalLabel"><i class="glyphicon glyphicon-time"></i> <?php echo $this->translate('Locking protection system'); ?></h4>
			</div>
			<div class="modal-body">
				<div class="alert alert-warning" role="alert">
					<p><?php echo sprintf($this->translate('No activity has been detect on this screen since %s seconds.'), $supervisorTimeout); ?></p>
					<p><?php echo $this->translate('You have been deconnected.'); ?></p>
					<br />
					<p><?php echo $this->translate('Please proceed to Sign-In button to be reconnected.'); ?></p>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary" onclick="location.href='<?php echo $this->url('log'); ?>'"><i class="glyphicon glyphicon-home"></i> <?php echo $this->translate('Sign In'); ?></button>
			</div>
		</div>
	</div>
</div>
		</div>
	</body>
</html>
