<?php

class PatientHistory {
// `id` INT NOT NULL AUTO_INCREMENT,
// `patient_id` VARCHAR(25) NULL,
// `lastname` VARCHAR(100) NOT NULL,
// `firstname` VARCHAR(100) NOT NULL,
// `gender` ENUM('M', 'F', 'U') NOT NULL,
// `birthdate` DATE NOT NULL,
// `weight` DECIMAL(5,2) NOT NULL,
// `height` DECIMAL(3,0) NULL,
// `patient_type` VARCHAR(25) NULL,
// `doctor_name` VARCHAR(100) NULL,
// `injection_type` VARCHAR(6) NULL,
// `injection_time` TIME NOT NULL,
// `injection_activity` INT(11) NOT NULL,
// `injection_prescription_id` VARCHAR(255) NULL,
// `injection_dose_status` VARCHAR(255) NULL,
// `injection_val_id` INT(11) NULL,
// `injection_location` VARCHAR(255) NOT NULL,
// `injection_comments` TEXT NULL,
// `examination_name` VARCHAR(255) NOT NULL,
// `examination_dci` VARCHAR(255) NOT NULL,
// `examination_rate` FLOAT NOT NULL,
// `examination_min` FLOAT NOT NULL,
// `examination_max` FLOAT NOT NULL,
// `drug_name` VARCHAR(255) NOT NULL,
// `drug_dci` VARCHAR(255) NOT NULL,
// `drug_radionuclide_id` INT(11) NOT NULL,
// `drug_input_date` DATETIME NOT NULL,
// `drug_input_operator_name` VARCHAR(200) NOT NULL,
// `drug_input_batchnum` VARCHAR(255) NULL,
// `drug_input_calibration_time` DATETIME NOT NULL,
// `drug_input_expiration_time` DATETIME NOT NULL,
// `drug_input_vialvol` FLOAT NOT NULL,
// `drug_input_activity` FLOAT NOT NULL,
// `drug_input_activity_conc` FLOAT NOT NULL,
// `drug_input_activity_calib` FLOAT NOT NULL,
// `patient_kit_serial` VARCHAR(35) NOT NULL,
// `source_kit_serial` VARCHAR(35) NOT NULL,
// `radionuclide_id` INT(11) NOT NULL,
// `radionuclide_code` VARCHAR(8) NOT NULL,
// `radionuclide_name` VARCHAR(255) NOT NULL,
	
}