<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Operator\Module'                        => __DIR__ . '/Module.php',
    'Operator\Controller\OperatorController' => __DIR__ . '/src/Operator/Controller/OperatorController.php',
    'OperatorTest\Framework\TestCase'        => __DIR__ . '/tests/Operator/Framework/TestCase.php',
    'OperatorTest\SampleTest'                => __DIR__ . '/tests/Operator/SampleTest.php',
);
