<ol class="breadcrumb">
	<li><a href="<?php echo $this->url('operator')?>"><span class=" glyphicon glyphicon-home"></span> <?php echo $this->translate('Operator dashboard')?></a></li>
	<li class="active"><?php echo $this->translate("User account confirmation")?></li>
</ol>
<div class="row">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<span class="glyphicon glyphicon-user"></span> <?php echo $this->translate("User account confirmation")?>
		</div>
		<div class="panel-body">
			<div class="row">
				<div class="col-md-12">
					<p><?php echo $this->translate('Please confirm the current account or login to your own account')?> :</p>
				</div>
			</div>
			<form role="form" method="POST" action="<?php echo $this->url('auth', array('action'=>'confirmauth'))?>">
				<div class="row">
					<div class="col-md-6 col-md-offset-3">
							<div id="inputgroup" class="form-group">
								<label for="input1"><?php echo $this->translate('User')?> :</label>
								<input type="text" class="form-control" id="login" name="login" value="<?php echo $this->current_user;?>" autocomplete="off" maxlength="100" readonly/>
							</div>
							<div id="inputgroup" class="form-group">
								<label for="input1"><?php echo $this->translate('Password')?> :</label>
								<input type="password" class="form-control" id="password" name="password" placeholder="" autocomplete="off" maxlength="100" />
							</div>
					</div>
				</div>
				<div class="row" style="margin-top:10px">
					<div class="col-md-4 col-md-offset-2">
						<input id="btn-next" type="submit" class="btn btn-success btn-block" value="<?php echo $this->translate('Next')?>"/>
					</div>
					<div class="col-md-4">
						<button id="btn-exit" type="button" class="btn btn-danger btn-block" onClick="location.href='<?php echo $this->url('auth', array('action'=>'swapauth'))?>'"><?php echo $this->translate('Change user account')?></button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>