<ol class="breadcrumb">
	<li><a href="<?php echo $this->url('operator')?>"><span class=" glyphicon glyphicon-home"></span> <?php echo $this->translate('Operator dashboard')?></a></li>
	<li class="active"><?php echo $this->translate("User account confirmation")?></li>
</ol>
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<span class="glyphicon glyphicon-user"></span> <?php echo $this->translate("User account confirmation")?>
			</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-md-12">
						<p><?php echo $this->translate("Please sign in")?></p>
					</div>
				</div>
				<?php
				$flash = $this->flashMessenger();
				$flash->setMessageOpenFormat('<div%s>
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">
						&times;
					</button>
					<ul><li>')
						->setMessageSeparatorString('</li><li>')
						->setMessageCloseString('</li></ul></div>');
				echo $flash->render('error',	array('alert', 'alert-dismissable', 'alert-danger'));
				echo $flash->render('info',		array('alert', 'alert-dismissable', 'alert-info'));
				echo $flash->render('default',	array('alert', 'alert-dismissable', 'alert-warning'));
				echo $flash->render('success',	array('alert', 'alert-dismissable', 'alert-success'));
				?>
				<div class="row">
					<div class="col-md-6 col-md-offset-3">
						<form class="form-signin" role="form" method="post" action="<?php echo $this->url('auth', array('action'=>'swapauth'))?>">
							<input id="login" name="login" type="text" class="form-control" placeholder="<?php echo $this->translate("Login")?>" required autofocus />
							<input id="password" name="password" type="password" class="form-control" placeholder="<?php echo $this->translate("Password")?>" required />
							<button class="btn btn-lg btn-primary btn-block" type="submit"><?php echo $this->translate("Sign in")?></button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>